### ISSUE TITLE
Capitalize<T>

### ISSUE THREAD

**Issue by antfu** [type-challenges/type-challenges#110]
> This requires https://github.com/microsoft/TypeScript/pull/40336 to work (you can try it now with the "preview" badge below)

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Capitalize<T>
tags: template-string
tsconfig: 
  ts: 4.1.0-pr-40336-88
```

## Question

Implement `Capitalize<T>` which converts the first letter of a string to uppercase and leave the rest as-is.

For example

```ts
type capitalized = Capitalize<'hello world'> // expected to be 'Hello world'
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Capitalize<S extends string> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Capitalize<'foobar'>, 'Foobar'>>,
  Expect<Equal<Capitalize<'FOOBAR'>, 'FOOBAR'>>,
  Expect<Equal<Capitalize<'foo bar'>, 'Foo bar'>>,
  Expect<Equal<Capitalize<''>, ''>>,
]
```

**Comment by Manu1400** [comment]
@antfu [My very quick solution (not support Unicode)](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/C4TwDgpgBAsglgOwPYCcoF4oG8BQUoBEAhgQFxQDkAghQNx6EBGZlAQnQwQMYsEDCBevgIATXgBFBnCLwCiU4QDNeAMQWEA5rwDi6ggAteACT1xeAST0ArXgCk9Aa14BpKQF8cOUJCgq4KAGdgPn0iFAAeAGVgNAgAD2AIBBEAqCCURA0APgwoaNiEpJSoAAMAEixERQg0P0DgNwqqmryILiRktxKoAH5SirqgrqhyAgIvcGgAdThgfSQAV2BB4NCI-Kh4xOTU9MyczA2totTyyoRq2v8hpouWyLaOkWG+s4f2zu7R8YmfPiIwLMiAAbOAALwgUU2hR2aRi+1yKxCYSiOWOsIcEBASEUsEQqF6-Sw8GQKAA2ki1qiALqNLAzOaLZbXVYoyJZYbkSKeAD0ACooAB9YUi0UiqAAFQgQSg-wC0qFYqVgqgfJ5ODgAFswKhgNgoLIAI4LEEAGgNcUgXD1bigihQSE1lAAAt4IABaLihYHApIaaU8pZwYEBCieN1QLhEeWpTBkhiyS1tYDhI0m4Hhf6A4Ag8GQiiKJBIRhhChZc0UFRFksoMvlhNJ62p40gzMAoGgiHhSsAeR7rCoACUyxWVH2B8OsvX8ImrSm062sx2893C0goDWR5Qq+vN1PTQ2583023s7muxQt5f9zhqTggA)

**Comment by Manu1400** [comment]
you could add a other test case :
`Expect<Equal<Capitalize<'édouard'>, 'Édouard'>>,`
