### ISSUE TITLE
110 - Capitalize without any built-in tools!!!!

### ISSUE THREAD

**Issue by man-fish** [type-challenges/type-challenges#1125]
```ts
// your answers
type AlphaMap = {
    a: 'A';
    b: 'B';
    c: 'C';
    d: 'D';
    e: 'E';
    f: 'F';
    g: 'G';
    h: 'H';
    // ...more alphas
};

type Alphas = keyof AlphaMap;

export type Space = ' ';

export type Split<T extends string, D extends string> = T extends ''
    ? []
    : T extends `${infer L}${D}${infer R}`
    ? L extends ''
        ? []
        : [L, ...Split<R, D>]
    : [T];

export type Replace<T extends string> = T extends `${infer L}${infer R}`
    ? L extends Alphas
        ? `${AlphaMap[L]}${R}`
        : R
    : '';

export type JoinWithReplace<T extends any[], D extends string> = T extends [
    infer F,
    ...infer R
]
    ? F extends string
        ? R[0] extends string
            ? `${Replace<F>}${D}${JoinWithReplace<R, D>}`
            : `${Replace<F>}`
        : ''
    : '';

export type Capitalize<T extends string> = JoinWithReplace<
    Split<T, Space>,
    Space
>;
```

**Comment by man-fish** [comment]
> type AlphaMap = {
> a: 'A';
> b: 'B';
> c: 'C';
> d: 'D';
> e: 'E';
> f: 'F';
> g: 'G';
> h: 'H';
> // ...more alphas
> };
> 
> type Alphas = keyof AlphaMap;
> 
> export type Space = ' ';
> 
> export type Split<T extends string, D extends string> = T extends ''
> ? []
> : T extends `${infer L}${D}${infer R}`
> ? L extends ''
> ? []
> : [L, ...Split<R, D>]
> : [T];
> 
> export type Replace = T extends `${infer L}${infer R}`
> ? L extends Alphas
> ? `${AlphaMap[L]}${R}`
> : R
> : '';
> 
> export type JoinWithReplace<T extends any[], D extends string> = T extends [
> infer F,
> ...infer R
> ]
> ? F extends string
> ? R[0] extends string
> ? `${Replace<F>}${D}${JoinWithReplace<R, D>}`
> : `${Replace<F>}`
> : ''
> : '';
> 
> export type Capitalize = JoinWithReplace<
> Split<T, Space>,
> Space
> 
> > ;
> 
> ```ts
> // your answers
> ```

**Comment by hauseyo** [comment]
Wow! That's really cool!

**Comment by Skylooker-hub** [comment]
type AlphaMap = {
  a: "A";
  b: "B";
  c: "C";
  d: "D";
  e: "E";
  f: "F";
  g: "G";
  h: "H";
  i: "I";
  j: "J";
  k: "K";
  l: "L";
  m: "M";
  n: "N";
  o: "O";
  p: "P";
  q: "Q";
  r: "R";
  s: "S";
  t: "T";
  u: "U";
  v: "V";
  w: "W";
  x: "X";
  y: "Y";
  z: "Z";
};

type Alpha = keyof AlphaMap;

type MyCapitalize<S extends string> = S extends `${infer F}${infer R}`
  ? F extends Alpha
    ? `${AlphaMap[F]}${R}`
    : S
  : S;

**Comment by I-am-tk** [comment]
type MyCapitalize<S extends string> =
  S extends `${infer F extends Alpha}${infer R}` ? `${AlphaMap[F]}${R}` : S;
