### ISSUE TITLE
Pipe

### ISSUE THREAD

**Issue by gideonoludeyi** [type-challenges/type-challenges#1202]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes. 
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Function Composition LTR
#tags: arguments, array, infer
```

## Question

Write a generic type that takes a non-empty array of *single-parameter* functions and returns a function
with the same parameter type and return type as the first and last functions
in the array respectively, if and only if the parameter type of each function matches
the return type of the function before it (*left-to-right*).

```ts
type composed = Compose<[(x: number) => string, (y: string) => boolean]> // (x: number) => boolean
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Compose<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Compose<[(x: number) => string, (y: string) => boolean]>, (x: number) => boolean>,
  Expect<NotEqual<Compose<[(x: boolean) => number, (y: string) => boolean]>, (y: string) => number>>,
  Expect<NotEqual<Compose<[(x: number) => string, (y: number) => number, (z: number) => boolean]>, (x: number) => boolean>,
  Expect<Equal<Compose<[(x: number) => string, (y: string) => number, (z: number) => boolean]>, (x: number) => boolean>,
  Expect<Equal<Compose<[(x: 0) => false]>, (x: 0) => false>,
  Expect<NotEqual<Compose<[(x: 0) => false, (y: boolean) => 10]>, (x: 0) => 10>>,
]
```

**Comment by antfu** [comment]
For the naming, how about "Invert Function"?

**Comment by gideon-oludeyi** [comment]
I think the name "Invert Function" would be misleading as it suggests swapping the parameter and return type of a function.

**Comment by antfu** [comment]
Oh sorry, I misread your question. So it more like function chaining right, while the first function's return should be matched with next fn's argument. I am wondering what's the use case in the real world, and does this type accepts one or multiple functions?

**Comment by gideon-oludeyi** [comment]
1. I suggested this as a fun challenge, if I must justify with a use case, then maybe as a reverse [Ramda compose](https://ramdajs.com/docs/#compose).
2. The type accepts multiple functions that have single parameters. (I'll specify the question)

**Comment by antfu** [comment]
Still think this name is a bit too long and unclear without reading the question. 

And it will be great if you can add cases for zero and more functions as parameters.

Thank you

**Comment by Beraliv** [comment]
@antfu @gideon-oludeyi maybe `Pipe`?

Ramda `pipe` – https://github.com/typed-typings/npm-ramda/blob/master/templates/pipe.md

**Comment by gideon-oludeyi** [comment]
> @antfu @gideon-oludeyi maybe `Pipe`?
> 
> Ramda `pipe` – https://github.com/typed-typings/npm-ramda/blob/master/templates/pipe.md

Yeah, the name is short.
Works for me

**Comment by Beraliv** [comment]
@gideonoludeyi can I help you here?
