### ISSUE TITLE
8 - Readonly 2

### ISSUE THREAD

**Issue by heappynd** [type-challenges/type-challenges#12066]
```ts
// 你的答案
type MyReadonly2<T,K extends keyof T = keyof T> = {
  readonly [ P in K ]: T[P]
} & {
  -readonly [ P in Exclude<keyof T,K>]: T[P]
}
```

**Comment by heappynd** [comment]
```ts
type MyReadonly2<T,K extends keyof T = keyof T> = {
  readonly [ P in K ]: T[P]
} & {
  -readonly [ P in keyof T as P extends K ? never : P]: T[P]
}
```

**Comment by ZhanghaoH** [comment]
-readonly是什么意思

> ```ts
> type MyReadonly2<T,K extends keyof T = keyof T> = {
>   readonly [ P in K ]: T[P]
> } & {
>   -readonly [ P in keyof T as P extends K ? never : P]: T[P]
> }
> ```

**Comment by ZhanghaoH** [comment]
K extends keyof T = keyof T  这句话为什么要在这里加上 = keyof T呢

**Comment by heappynd** [comment]
-readonly  `-`是映射类型里面的修饰符 我这里是想把原来的只读属性变成普通属性

相关资料 [mapping-modifiers](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#mapping-modifiers)

**Comment by heappynd** [comment]
`=` 是我想通过第一个测试用例 `Expect<Alike<MyReadonly2<Todo1>, Readonly<Todo1>>>`

注意这里是没有第二个参数的，所以给上了默认值。这样所有属性都是只读属性了！

**Comment by pkc918** [comment]
你这里不是只把 `K` 里只读了么，没在 `K` 的也没只读啊，相反这里 `- readonly` 会把我 `T`中原本是 `readonly` 的属性变成`非readonly`🧐
