### ISSUE TITLE
Camelize

### ISSUE THREAD

**Issue by denchiklut** [type-challenges/type-challenges#1252]
## Question

Implement Camelize<T> which converts object from snake_case to to camelCase 

## For example

```ts

Camelize<{
  some_prop: string, 
  prop: { another_prop: string },
  array: [{ snake_case: string }]
}> 

// expected to be
// {
//   someProp: string, 
//   prop: { anotherProp: string },
//   array: [{ snakeCase: string }]
// }
```

**Comment by denchiklut** [comment]
My solution was:

type CamelCase<S> = S extends `${infer H}_${infer T}`
  ? `${H}${CamelCase<Capitalize<T>>}`
  : S


type Camelize<T> = {
  [P in keyof T as CamelCase<P>]: T[P] extends object ? Camelize<T[P]> : T[P]
}

**Comment by dvlden** [comment]
Can you make a TS playground with test cases?
What happens if you get a record with multiple `_` in a single property?

```ts
Camelize<{
  some_prop: string, 
  one_very_long_prop_that_could_occur: string,
  prop: { another_prop: string },
  array: [{ snake_case: string }],
}> 
```

**Comment by denchiklut** [comment]
@dvlden yes it will work fine

https://codesandbox.io/s/camelize-5uuol?file=/src/index.ts

**Comment by antfu** [comment]
Please follow the template to create the proposal, thanks.
