### ISSUE TITLE
15 - 最后一个元素

### ISSUE THREAD

**Issue by ZhanghaoH** [type-challenges/type-challenges#12949]
```ts
// 你的答案
// 好傻啊 还以为...只能放最后呢
// type Last<T extends any[]> = T extends [infer A, ...infer B] ? B extends [] ? A: Last<B>  : never
// type Last<T extends any[]> = T extends [...infer A, infer B] ? B  : never
// 这个方法巧改变数组长度 用length取值
type Last<T extends any[]> = [any, ...T][T['length']]
```

**Comment by yongsheng-xia** [comment]
我这边是不行的：
![image](https://user-images.githubusercontent.com/7240786/184504669-d7265d0f-37c0-4556-8b10-45b5a2d92baa.png)

![image](https://user-images.githubusercontent.com/7240786/184504701-205ac573-5297-40c7-a962-4c28e3e29f6f.png)

**Comment by fulvaz** [comment]
T['length'] 是 number，你这是匹配了数组的任意元素

[1, 2, 'string'] 这个用例就不行了
