### ISSUE TITLE
10 - 元组转合集

### ISSUE THREAD

**Issue by ZhanghaoH** [type-challenges/type-challenges#12946]
```ts
//这个比T[number]好  说实话一直没查到T[number]的用法
type TupleToUnion<T> = T extends [infer A, ...infer B] ? A |  TupleToUnion<B> : never
```

**Comment by ivan0525** [comment]
> ```ts
> //这个比T[number]好  说实话一直没查到T[number]的用法
> type TupleToUnion<T> = T extends [infer A, ...infer B] ? A |  TupleToUnion<B> : never
> ```

可以看看这个：[Conditional Types](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html#handbook-content:~:text=Another%20example%20of%20indexing%20with%20an%20arbitrary%20type%20is%20using%20number%20to%20get%20the%20type%20of%20an%20array%E2%80%99s%20elements.%20We%20can%20combine%20this%20with%20typeof%20to%20conveniently%20capture%20the%20element%20type%20of%20an%20array%20literal%3A)

**Comment by ZhanghaoH** [comment]
wow,  官网文档是宝藏，就是太多了...thx,buddy

**Comment by ZhanghaoH** [comment]
> > ```ts
> > //这个比T[number]好  说实话一直没查到T[number]的用法
> > type TupleToUnion<T> = T extends [infer A, ...infer B] ? A |  TupleToUnion<B> : never
> > ```
> 
> 可以看看这个：[Conditional Types](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html#handbook-content:~:text=Another%20example%20of%20indexing%20with%20an%20arbitrary%20type%20is%20using%20number%20to%20get%20the%20type%20of%20an%20array%E2%80%99s%20elements.%20We%20can%20combine%20this%20with%20typeof%20to%20conveniently%20capture%20the%20element%20type%20of%20an%20array%20literal%3A)

wow, 官网文档是宝藏，就是太多了...thx,buddy

**Comment by Nnadozie** [comment]
Hi @ZhanghaoH @ivan0525 你们是地方人吗？我 学习中文，和。。。找中文朋友 😅

我觉得这个 

`type TupleToUnion<T> = T extends [infer A, ...infer B] ? A |  TupleToUnion<B> : never`

是很聪明·

**Comment by ZhanghaoH** [comment]
> 



> Hi @ZhanghaoH @ivan0525 你们是地方人吗？我 学习中文，和。。。找中文朋友 😅
> 
> 我觉得这个
> 
> `type TupleToUnion<T> = T extends [infer A, ...infer B] ? A | TupleToUnion<B> : never`
> 
> 是很聪明·
yeah， It is great for me  to have a foreign friend
