### ISSUE TITLE
62 - Type Lookup

### ISSUE THREAD

**Issue by ZhanghaoH** [type-challenges/type-challenges#12974]
```ts
//我这种方法真是个小可爱......
// type LookUp<U, T> = U extends { type: string } ? U['type'] extends T ? U: never :never
type LookUp<U, T> = U extends { type: T } ? U: never 
```

**Comment by caolinjian** [comment]
type LookUp<U, T> = U extends { type: infer V } ? V extends T ? U: never :never. 
  比你的好一点

**Comment by ZhanghaoH** [comment]
> type LookUp<U, T> = U extends { type: infer V } ? V extends T ? U: never :never.  比你的好一点

我注释的才是我的方法，说可爱也是说那个的，就是说我自己有点憨的意思，没注释的答案是看别人的，发现确实简洁点
