### ISSUE TITLE
296 - Permutation

### ISSUE THREAD

**Issue by ZhanghaoH** [type-challenges/type-challenges#12994]
```ts
// 官方文档中，介绍了一种操作，叫 Distributive conditional types
// 简单来说，传入给T extends U中的T如果是一个联合类型A | B | C，则这个表达式会被展开成
// (A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)
// [U] extends [never] 而不是 U extends never 因为  U是联合类型 条件类型会走分配得到的是一个联合类型  不符合期望
type Permutation<T, U = T> = [U] extends [never] ? [] : (T extends U  ? [T, ...Permutation<Exclude<U, T>>] : [])
```

**Comment by zhangzhuang15** [comment]
> ```ts
> // 官方文档中，介绍了一种操作，叫 Distributive conditional types
> // 简单来说，传入给T extends U中的T如果是一个联合类型A | B | C，则这个表达式会被展开成
> // (A extends U ? X : Y) | (B extends U ? X : Y) | (C extends U ? X : Y)
> // [U] extends [never] 而不是 U extends never 因为  U是联合类型 条件类型会走分配得到的是一个联合类型  不符合期望
> type Permutation<T, U = T> = [U] extends [never] ? [] : (T extends U  ? [T, ...Permutation<Exclude<U, T>>] : [])
> ```

I also find an interesting insight:
```ts
type M<T> = T extends never ? 1 : 0

type N<T> = [T] extends [never] ? 1 : 0

//  P = never
type P = M<never>

//  Q = 1
type Q = N<never>
```

I don't know why, someone who can explain it ?
