### ISSUE TITLE
1097 - IsUnion  most answers cannot satisfy the last case

### ISSUE THREAD

**Issue by ZhanghaoH** [type-challenges/type-challenges#13276]
```ts
type IsUnion<T, F = T> =( T extends F ? F extends T ? true : false : never) extends true ? false : true
```
这里不能交换true false的位置，我曾尝试 `type IsUnion<T, F = T> =( T extends F ? F extends T ? false : true : never) extends true ? true : false`，失败；分步尝试后发现 是联合类型的前半部分得到的结果是 `boolean`,而基础类型由于是自身相互比较得到true

**Comment by childrentime** [comment]
可以详细解释一下吗大哥

**Comment by ZhanghaoH** [comment]
> 



> 可以详细解释一下吗大哥
解释哪一点？

**Comment by cpWhitecat** [comment]
> 可以详细解释一下吗大哥
如果传入的是union , 代码没有对泛型T 和 U 做约束,所以就会开始分配类型

当泛型T为string | number 时
我帮你把原作者的( T extends F ? F extends T ? true : false : never)展开了
```ts
type isUnion = (string extends number | string 
  ? (string extends number ? true :false) | (string extends string ? true :false) 
  :never) 

| (number extends number | string 
  ? (number extends number ? true :false) | (number extends string ? true :false) 
  :never)
```

如有错误欢迎指出

**Comment by cpWhitecat** [comment]
> > 可以详细解释一下吗大哥
> > 如果传入的是union , 代码没有对泛型T 和 U 做约束,所以就会开始分配类型
> 
> 当泛型T为string | number 时 我帮你把原作者的( T extends F ? F extends T ? true : false : never)展开了
> 
> ```ts
> type isUnion = (string extends number | string 
>   ? (string extends number ? true :false) | (string extends string ? true :false) 
>   :never) 
> 
> | (number extends number | string 
>   ? (number extends number ? true :false) | (number extends string ? true :false) 
>   :never)
> ```
> 
> 如有错误欢迎指出

@childrentime

**Comment by Gu-Miao** [comment]
@ZhanghaoH 可以交换位置，但需要这样写：

```ts
type IsUnion<T, F = T> = (T extends F ? (F extends T ? false : true) : never) extends false
  ? false
  : true
```

上面这样写括号内的结果只会是 `false`(非联合类型)，`boolean`(联合类型)以及`never`(`T` 为 `never`)，因此需要判断是否为 `false` 而非 `true`。
