### ISSUE TITLE
新题目

### ISSUE THREAD

**Issue by Stan-BK** [type-challenges/type-challenges#13532]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: easy

# 题目标题
title: 扁平化类型

# 题目标签
tags: union, array
```

## 题目

将嵌套多种类型的数组扁平化为联合类型
```
type Arr = [string, [number, boolean]]
type Result = Flat<Arr> // expect string | number | boolean
```

## 题目模版

以下是给予挑战者开始做题的代码模版，在大部分情况下你只需要修改类型名称使其符合你的题目与判题测试，实现的部分保持 `any` 即可。

```ts
type Flat<T> = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Flat<[string, [number]]>, string | number>>,
  Expect<Equal<Flat<[string, [number, boolean]]>, string | number | boolean>>,
  Expect<Equal<Flat<[string, [number], [boolean, () => void]]>, string | number | boolean | (() => void)>>
]
```

**Comment by jiangshanmeta** [comment]
@Stan-BK  Actually there is a [similar challenge](https://github.com/type-challenges/type-challenges/blob/main/questions/00459-medium-flatten/README.md)

**Comment by Stan-BK** [comment]
> 

Oops, I haven't noticed that, sry.

**Comment by Stan-BK** [comment]
> @Stan-BK Actually there is a [similar challenge](https://github.com/type-challenges/type-challenges/blob/main/questions/00459-medium-flatten/README.md)

Oops, I haven't noticed that, sry.
