### ISSUE TITLE
ArrayValues

### ISSUE THREAD

**Issue by sebmeister2077** [type-challenges/type-challenges#13666]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Implement a generic ArrayValues<T> which returns the values of a given array

```yaml
difficulty: medium
title: ArrayValues
# tags: exclude, array 
```

## Question

For example: 

```
type MyArr = ["hello","world",1,1]
type T0 = ArrayValues<MyArr> // "hello" | "world" | 1;

const arrVariable = ["hello","world",1]
type T1 = ArrayValues<typeof arrVariable> // string | number;
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type ArrayValues<T>= any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

const arrayVariable = ["number",3]
type cases = [
  Expect<Equal<ArrayValues<["hi","there"]>, "hi" | "there">>,
  Expect<Equal<ArrayValues<[]>, never>>,
  Expect<Equal<ArrayValues<typeof arrayVariable>, string | number>>,
]
```

**Comment by jiangshanmeta** [comment]
@sebmeister2077  Your proposal is duplicated with [Tuple to Union](https://github.com/type-challenges/type-challenges/blob/main/questions/00010-medium-tuple-to-union/README.md). As a result, I will close this pr. Anyway, thanks for your contribution.
