### ISSUE TITLE
Missing Test Case in 14

### ISSUE THREAD

**Issue by FlorianWendelborn** [type-challenges/type-challenges#137]
14 is missing a crucial test case:

```typescript
Expect<Equal<First<[undefined]>, undefined>>
```

The following solution should **not** be allowed:

```typescript
type First<T extends any[]> = T[0] extends undefined ? never : T[0]
```

While this should be one of the few that are accepted: #18

**Comment by kaleb** [comment]
What if you have an array of undefined?

**Comment by FlorianWendelborn** [comment]
@kaleb That’s exactly the issue I’m raising here. `undefined[]` would be detected as `never` with the solution above. Solution #18 implements this properly and should be one of the few that pass the tests.

**Comment by antfu** [comment]
Thanks!
