### ISSUE TITLE
645 - Diff

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#13908]
采用 Exclude 排除掉两个相同的部分，也就是 O | O1，再从 O&O1 （全部）中获取相应的 value 即可
```ts
type Diff<O, O1> = {
  [K in Exclude<keyof (O & O1), keyof(O | O1)>]: (O & O1)[K]
}
```

**Comment by Gu-Miao** [comment]
看下这个用例：

```ts
type A = {
  a: string
  b: number
  c: boolean
}

type B = {
  a: string
  c: string
}

type AB = A & B
```

此时 `A` 中的 `c` 是 `boolean` 类型，`B` 中的 `c` 是 `string` 类型，他们没有交集，因此 `AB` 为 `nenver` 类型。

挑战中给出的用例没有涉及到这一点，实际应该用之前的 `Merge<F, S>` 更好吧。

**Comment by ayu-exorcist** [comment]
> 看下这个用例：
> 
> ```ts
> type A = {
>   a: string
>   b: number
>   c: boolean
> }
> 
> type B = {
>   a: string
>   c: string
> }
> 
> type AB = A & B
> ```
> 
> 此时 `A` 中的 `c` 是 `boolean` 类型，`B` 中的 `c` 是 `string` 类型，他们没有交集，因此 `AB` 为 `nenver` 类型。
> 
> 挑战中给出的用例没有涉及到这一点，实际应该用之前的 `Merge<F, S>` 更好吧。

```ts
type Diff<O, O1> = {
  [K in (keyof O | keyof O1) as K extends keyof O ?  K extends keyof O1 ? never : K : K]: K extends keyof O ? O[K] : K extends keyof O1 ? O1[K] : never
}
```
