### ISSUE TITLE
9 - 深度 Readonly

### ISSUE THREAD

**Issue by zhenzhenChange** [type-challenges/type-challenges#13912]
```ts
type DeepReadonly<T> = keyof T extends never ? T : { readonly [key in keyof T]: DeepReadonly<T[key]> }
```

**Comment by Taneros** [comment]
what does never check in your base case?

```keyof T extends never```

does it check whether there are own keys? like primitives and functions don't have them?

**Comment by nikolausliu** [comment]
不理解为什么`keyof T extends never`可以作为判断条件，下面的a是false，但是测试用例确实过了
```ts
type a = keyof string extends never ? true : false // false
```

**Comment by 15200596294git** [comment]
为啥我看第二个测试用例没过

**Comment by 15200596294git** [comment]
`type DeepReadonly<T, U = T> = U extends any ? {
  readonly [P in keyof U]: keyof U[P] extends never ? U[P] : DeepReadonly<never, U[P]>
} : never`
