### ISSUE TITLE
12 - 可串联构造器

### ISSUE THREAD

**Issue by Ardear** [type-challenges/type-challenges#13951]
```TypeScript
type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ?
    V extends T[K] ? never : K
    : K, value: V) => Chainable<Omit<T, K> & Record<K, V>>
  get: () => T
}
```
前三步基于： https://github.com/type-challenges/type-challenges/issues/13879
1. 可以使用 T = {} 来作为默认值，甚至默认参数与默认返回值，再通过递归传递 T 即可实现递归全局记录
 2. option 是一个函数接收两个值：K 和 V，为了约束 key 不可重复必须范型传入，value 是任意类型范型不做约束直接透传
```TypeScript
type Chainable<T = {}> = {
  option: <K extends string, V>(key: K, value: V) => Chainable<T & Record<K, V>>
  get: () => T
}
```
 3. 先验证重复 key，实现传入相同 key 报错
```TypeScript
type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ? never : K, value: V)
    => Chainable<T & Record<K, V>>
  get: () => T
}
```

 4.然后发现案例3无法通过，案例3是传入了相同的 key 但类型不同，因此在 `K extends keyof T`  后面增加验证只有类型相同才返回 never
```TypeScript
type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ?
    V extends T[K] ? never : K
    : K, value: V) => Chainable<T & Record<K, V>>
  get: () => T
}
```
 5.最后直接 & 联合并不能将相同 key 的类型覆盖，因此用 `Omit` 去掉前一个类型中相同的 key
```TypeScript
type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ?
    V extends T[K] ? never : K
    : K, value: V) => Chainable<Omit<T, K> & Record<K, V>>
  get: () => T
}
```

**Comment by hnustwjj** [comment]
好清晰，赞！泛型传入是为了将它作为变量使用嘛

**Comment by Ardear** [comment]
> 好清晰，赞！泛型传入是为了将它作为变量使用嘛

也可以这么理解吧

**Comment by gdrkbones** [comment]
A minor fix my friends
`type Chainable<T = {}> = {
    option: <K extends string, V>(
        key: K extends keyof T ? never : K,
        value: V
    ) => Chainable<Omit<T, K> & Record<K, V>>;
get: () => T;
};
`

**Comment by Mario-Marion** [comment]
> A minor fix my friends
> 
> ```ts
> type Chainable<T = {}> = {
>     option: <K extends string, V>(
>         key: K extends keyof T ? never : K,
>         value: V
>       ) => Chainable<Omit<T, K> & Record<K, V>>;
>     get: () => T;
> };
> ```
@gdrkbones 
Niubility plus

**Comment by iamzjt-front-end** [comment]
最新的题目，要求同key不同类型的value也一样报错，但是结果仍被覆盖。

type Chainable<T extends Record<string, any> = {}> = {
  option: <K extends string, V>(
      key: K extends keyof T ? never : K,
      value: V,
  ) => Chainable<Omit<T, K> & Record<K, V>>
  get(): T
}

**Comment by sheben404** [comment]
> 最新的题目，要求同key不同类型的value也一样报错，但是结果仍被覆盖。
> 
> type Chainable<T extends Record<string, any> = {}> = { option: <K extends string, V>( key: K extends keyof T ? never : K, value: V, ) => Chainable<Omit<T, K> & Record<K, V>> get(): T }

可以这么该：
```TypeScript 
type Chainable<T = {}> = {
  option: <K extends string, V>(
    key: K extends keyof T ? never : K,
    value: V)
  => K extends keyof T ? Chainable<Omit<T, K> & Record<K, V>> : Chainable<T & Record<K, V>>
  get: () => T
}
```

**Comment by ydaydayup** [comment]
[#](https://github.com/type-challenges/type-challenges/issues/13951#issuecomment-1654887250)
我来解释下原理 （最新的题目，要求同key不同类型的value也一样报错，但是结果仍被覆盖）

`type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ? never : K, value: V) => Chainable<Record<K, V> & Omit<T, K>>
  get: () => T
}
`
ps: 基本思想和楼主一样, 主要解释 同key不同类型的value也一样报错

Typescript类型语法规则：
1. TypeScript 有两个“顶层类型”（any和unknown），但是“底层类型”只有never唯一一个。
2. never类型可以赋值给其他任意类型，但是其他类型不能复制给never

当K在T存在，返回never类型，此时其他类型传入就会报错
` key: K extends keyof T ? never : K`

**Comment by Qzhor** [comment]
answer of latest version:
`type Chainable<T = {}> = {
  option: <K extends string, V>(key: K extends keyof T ? (V extends T[K] ? K : never) : K, value: V) => Chainable<Omit<T, K> & Record<K, V>>;
  get: () => T;
};`

just alert error when calling same key and diff type value, not effect the return value which were covered.

**Comment by ms-mayya** [comment]
`type Chainable<T = {}> = {
  option<K extends PropertyKey, V>(key: K extends keyof T ? never : K, value: V): Chainable<Omit<T, K> & { [P in K]: V }>
  get(): {
    [P in keyof T]: T[P]
  }
}`

**Comment by 15200596294git** [comment]
// AKA螃蟹前来学习
```
type Chainable<T = {}> = {
  option<K extends PropertyKey, V>(key: K extends keyof T ? never : K, value: V): Chainable<Omit<T, K> & Record<K, V>>
  get(): T
}
```

**Comment by yurnery** [comment]
`type Chainable<T = {}> = {
  option<K extends string, V>(
    key: K extends keyof T ? (T[K] extends NonNullable<any> ? never : K) : K,
    value: V
  ): Chainable<Omit<T, K> & Record<K, V>>
  get(): T
}`

`T[K] extends NonNullable<any>` 这里应该是判断只有有过值就应该报错,  
`const result3 = a
  .option("name", "another name")
  // @ts-expect-error
  .option("name", 123)
  .get()` 要不然这里会报错

**Comment by goddnsgit** [comment]
有没有可能这题目是错误的.
type Chainable<T = {}> = {
  option<K extends keyof any, V>(key: K extends keyof T ? never : K, value: V)
    : Chainable<Omit<T, K> & { [key in K]: V }>
  get(): T
}
这样它就过了,可是! 这符合逻辑吗?option可是允许覆盖的不是吗????这是什么既要有要的逻辑.什么土匪逻辑?出错了还要正确答案?我的天,这题作者是要错误还是要正确?

**Comment by alirezaprime** [comment]
> type Chainable<T = {}> = {
>   option: <K extends string, V>(key: K extends keyof T ?
>     V extends T[K] ? never : K
>     : K, value: V) => Chainable<Omit<T, K> & Record<K, V>>
>   get: () => T
> }
> 前三步基于： [#13879](https://github.com/type-challenges/type-challenges/issues/13879)
> 
> 1. 可以使用 T = {} 来作为默认值，甚至默认参数与默认返回值，再通过递归传递 T 即可实现递归全局记录
> 2. option 是一个函数接收两个值：K 和 V，为了约束 key 不可重复必须范型传入，value 是任意类型范型不做约束直接透传
> 
> type Chainable<T = {}> = {
>   option: <K extends string, V>(key: K, value: V) => Chainable<T & Record<K, V>>
>   get: () => T
> }
> 3. 先验证重复 key，实现传入相同 key 报错
> 
> type Chainable<T = {}> = {
>   option: <K extends string, V>(key: K extends keyof T ? never : K, value: V)
>     => Chainable<T & Record<K, V>>
>   get: () => T
> }
> 4.然后发现案例3无法通过，案例3是传入了相同的 key 但类型不同，因此在 `K extends keyof T` 后面增加验证只有类型相同才返回 never
> 
> type Chainable<T = {}> = {
>   option: <K extends string, V>(key: K extends keyof T ?
>     V extends T[K] ? never : K
>     : K, value: V) => Chainable<T & Record<K, V>>
>   get: () => T
> }
> 5.最后直接 & 联合并不能将相同 key 的类型覆盖，因此用 `Omit` 去掉前一个类型中相同的 key
> 
> type Chainable<T = {}> = {
>   option: <K extends string, V>(key: K extends keyof T ?
>     V extends T[K] ? never : K
>     : K, value: V) => Chainable<Omit<T, K> & Record<K, V>>
>   get: () => T
> }

/////////////////////////////////////////////////////////////////////////////////////
// I hope you're doing well! I came across your code and found it really useful. While testing it, I noticed a small error, so I took the liberty to fix it and made a slight improvement. I hope you don’t mind!

type Chainable<T = {}> = {
  option: <K extends string, V>(
    key: K extends keyof T
      ? V extends T[K]
        ? never 
        : never 
      : K,
    value: V
  ) => Chainable<Omit<T, K> & Record<K, V>>;
  get: () => T;
};

**Comment by pangxie231** [comment]
```ts
type Chainable<T = {}> = {
  option<K extends PropertyKey,V>(key: K extends keyof T ? never : K, value: V): Chainable<Omit<T,K> & Record<K,V>>
  get(): T
}
```

**Comment by cmtlyt** [comment]
我直接莽一手

```ts
type Chainable<R = {}> = {
	option: <K extends string, V>(
		key: K extends keyof R ? never : K,
		value: V,
	) => Chainable<{ [P in keyof R as P extends K ? never : P]: R[P] } & { [key in K]: V }>;
	get(): R;
};
```

**Comment by Gravity2333** [comment]
按照这个约束 option无法传入重复的key 那么Omit<T,K> 还有必要吗?

**Comment by bytemanxie** [comment]
```
type Chainable<T={}> = {
  option<K extends string, V>(key: K extends keyof T ? 
    never : K, value: V): Chainable<Omit<T, K> & Record<K, V>>;
  get: () => T;
}
```

**Comment by bytemanxie** [comment]
> 按照这个约束 option无法传入重复的key 那么Omit<T,K> 还有必要吗?

```
const result3 = a
  .option('name', 'another name')
  // @ts-expect-error
  .option('name', 123)
  .get()
```
有必要的，这个样例的name键类型是number

**Comment by HoseaGuo** [comment]
<img width="757" height="263" alt="Image" src="https://github.com/user-attachments/assets/02fc4db0-1e5b-4ee9-a67a-c2635afbb266" />

```typescript

// 
type Chainable<Object = {}> = {
  option: <K extends string, V>(key: K, value: V) => Chainable<K extends keyof Object ? Object : Object & Record<K, V>>;
  get: () => Object
}
```

**Comment by XinXiaoIsMe** [comment]
这样应该就行了，不需要对K做额外的处理了。

```typescript
type Chainable<T = {}> = {
  option<K extends string, V = any>(key: K, value: V): Chainable<Omit<T, K> & Record<K, V>>
  get(): T
}
