### ISSUE TITLE
3188 - Tuple to Nested Object

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14085]
这题需要通过 `infer` 结合递归来实现，不断的递归数组的余项，不断的嵌套对象。这里需要注意指定对象 `key` 的方法，可以通过 `K in key` ，但是需要指定 `key` 的类型为 `PropertyKey`
```typescript
type TupleToNestedObject<T extends Array<unknown>, U> = 
  T extends [infer R, ...infer Rest] 
    ? {
      [K in R as R extends PropertyKey ? R : never]: TupleToNestedObject<Rest, U>
    }
  : U
```

**Comment by RainMaker-Q** [comment]
ts小白学习中... 大佬，[K in R as R extends PropertyKey ? R : never]， PropertyKey应该是内置的 string | number| symbol， 有什么情况会命中 never吗？  命中后会是什么情况呢，{[never]: TupleToNestedObject<Rest, U>} 真实情况会返回什么呢
