### ISSUE TITLE
4425 - Greater Than By linjunc

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14098]
这道题需要我们实现 `GreaterThan<T, U>` 判断 `T > U` 是 `true` 还是 `false`

有几个特殊测试用例
```ts
GreaterThan<2, 1> //should be true
GreaterThan<1, 1> //should be false
GreaterThan<10, 100> //should be false
GreaterThan<111, 11> //should be true
```

看到这题，在 JS 中非常的简单，直接就能有答案，但是 TS 是没有计算能力的，也不支持大小判断

那么我们还能怎么做呢？巧用数组，通过**数组的 `length` 来进行比较**，

有两种可行的方法

- 第一种就是递归，但是通过实践我们会知道，当参数过大时，很容易爆栈
- 第二种方法就是构造两个长度为 `T` 和 `U` 的数组，通过数组判断哪个数组更长

这里我们先看第一种方法

### 递归法
可以采用递归来实现，前面我们也有说过了，数组的很容易爆掉，但是测试用例还算温柔，这题能过

-   思路是拿一个新数组，和 `T`,`U` 进行对比，哪个先追上新数组的长度，哪个就小
-   简单一点来说就是，两个不一样长的木棍放在一起，我们从一端开始不断往前走，先摸到的那个木棍就是短一点的

看到具体实现上

通过引入新的变量 `R extends any[] = []` ,来进行辅助的计算，接着依次判断 `T`，`U` 和 `R['length]` 是否相等，这时候，如果 `T` 和 `R['length`] 相等了而 U 还没有相等，那就说明了 `T < U` ，如果都不相等，那就继续加大数组 `R` 的长度

怎么加大数组 `R` 呢？

递归的时候，往数组中多加一个值即可，`GreaterThan<T, U, [...R, 1]>` 这里的 `1` 就是塞进去把 `length` 整大的

这样就完成了这道大小判断

```ts
// 答案
type GreaterThan<T extends number, U extends number, R extends any[] = []> = 
  T extends R['length']
    ? false
    : U extends R['length']
      ? true
      : GreaterThan<T, U, [...R, 1]>
```
### 构造数组

我们还有一种很巧妙的方法

先看几段小代码

```ts
[1, 1, 1, 1] extends [1, 1] ? true : false // false
[1, 1] extends [1, 1, 1] ? true : false // false
```
上面的例子中，两个数组长度不等，很显然都会返回 `false` 

那么我们抽象一下，这同样会返回 `false`，因为很显然多了 `...any` 嘛
```ts
// 伪代码
A extends [...A, ...any] ? true : false
```
那么我们就可以有这样的思路，例如比较 2 和 3

我们就可以比较数组 A`[1, 1]` 和数组B `[1, 1, 1]` 

我们就可以这么来看，**数组 B 可以表示为 `[...A, 1]` 所以 B 大于 A**，A 没有办法这样表示 B 所以更小

显然我们这个思路没啥问题！

如何实现呢？**关键在于怎么构造长度为 T 和 U 的数组**

写一个生成长度为 N 的数组的方法，需要接受长度 `T`，还需要使用辅助变量 `A` 来保存当前的数组并作为返回值

采用递归的方式往数组中添加新的元素，这样数组的 `['length']` 就会不断的变长，当等于 `T` 时，就结束循环，返回数组 `A`

```ts
type newArr<T extends number, A extends any[] = []> = 
  A['length'] extends T
    ? A
    : newArr<T, [...A, '']>
```
验证一下，没啥毛病
```ts
type A = newArr<4> // type A = ["", "", "", ""]
```

![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9c027a42157f4480b2562ea62ff03a9d~tplv-k3u1fbpfcp-watermark.image?)

接下来就好办了，我们比较这两个数组就好了，为了美观抽出一个 type 来，这个就是我们前面讲到的逻辑

```ts
type GreaterArr<T extends any[], U extends any[]> = U extends [...T, ...any] ? false : true
```

最后调用它进行比较,KO
```ts
type GreaterThan<T extends number, U extends number> = GreaterArr<newArr<T>, newArr<U>>
```

**Comment by rattonlzh** [comment]
I can't understand why `A['length'] extends T` can succeed while `T extends A['length']` would tell me "Type instantiation is excessively deep and possibly infinite" 
``` ts
type newArr<T extends number, A extends any[] = []> =
  T extends A['length']
  ? A
  : newArr<T, [...A, '']>
type GreaterArr<T extends any[], U extends any[]> = U extends [...T, ...any] ? false : true
type GreaterThan<T extends number, U extends number> = GreaterArr<newArr<T>, newArr<U>>
```
![image](https://user-images.githubusercontent.com/35805617/230963277-02e6203b-34be-479e-bc0c-d587e52a2210.png)

**Comment by linjunc** [comment]
hello，如果采用 `T extends A['length']` 的写法可能会存在问题，例如 传入的是不是纯数字，而是 number，`number 是 extends number` 的，满足限制。
但是，在 newArr 的 判断中，如果使用 `T extends A['length']`，此时的 T 是 number，number extends 0 是 false，并且一直都是 false，因此会出现死循环
如果想要使用 `T extends A['length']` 的话，可以改成 `[T] extends [A['length']` 

```ts
type newArr<T extends number, A extends any[] = []> = [T] extends [A['length']] ? A : newArr<T, [...A, '']>
```

**Comment by linjunc** [comment]
> 



> I can't understand why `A['length'] extends T` can succeed while `T extends A['length']` would tell me "Type instantiation is excessively deep and possibly infinite"
> 
> ```ts
> type newArr<T extends number, A extends any[] = []> =
>   T extends A['length']
>   ? A
>   : newArr<T, [...A, '']>
> type GreaterArr<T extends any[], U extends any[]> = U extends [...T, ...any] ? false : true
> type GreaterThan<T extends number, U extends number> = GreaterArr<newArr<T>, newArr<U>>
> ```
> 
> ![image](https://user-images.githubusercontent.com/35805617/230963277-02e6203b-34be-479e-bc0c-d587e52a2210.png)

I replied above

**Comment by clf17222592** [comment]
这样过不了大数测试,要转成字符串比较
```
type ParseInt<S extends string> = S extends `${infer N extends number}` ? N : 0

type GreaterThanBySmallNumber<
  T extends number,
  U extends number,
  Arr extends any[] = [],
> = T extends Arr['length']
  ? false
  : U extends Arr['length']
  ? true
  : GreaterThanBySmallNumber<T, U, [...Arr, any]>

type StringToArray<S extends string> = S extends `${infer First}${infer Rest}`
  ? [First, ...StringToArray<Rest>]
  : []

type UnShift<T extends string[]> = T extends [string, ...infer Rest] ? Rest : []
type GreaterThanByArray<T extends string[], U extends string[]> = T[0] extends U[0]
  ? T['length'] extends 1
    ? false
    : GreaterThanByArray<UnShift<T>, UnShift<U>>
  : GreaterThanBySmallNumber<ParseInt<T[0]>, ParseInt<U[0]>>

type GreaterThan<
  T extends number,
  U extends number,
  TArr extends string[] = StringToArray<`${T}`>,
  UArr extends string[] = StringToArray<`${U}`>,
> = TArr['length'] extends UArr['length']
  ? GreaterThanByArray<TArr, UArr>
  : GreaterThanBySmallNumber<TArr['length'], UArr['length']>
```

**Comment by hesoso** [comment]
为了过大数额外多出来了很多代码，感觉写的有点丑陋
```ts
type GetSymbol<A extends string, B extends string, F extends any[] = []> =
  `${F['length']}` extends A
    ? `${F['length']}` extends B ? '=' : '<'
    : `${F['length']}` extends B ? '>' : GetSymbol<A, B, [...F, 1]>

type GreaterThan<T extends number | string, U extends number | string, S extends '>' | '<' | '=' = '='> =
  `${T}` extends `${infer A}${infer R1}`
    ? `${U}` extends `${infer B}${infer R2}`
      ? GreaterThan<R1, R2, S extends '=' ? GetSymbol<A, B> : S> : true
    : `${U}` extends `${any}${any}` ? false : S extends '>' ? true : false
```

**Comment by L9m** [comment]
我的思路比较笨，全转成 Array 再逐位比较
```
type BuildArr<T extends number, A extends any[] = []> = A["length"] extends T
  ? A
  : BuildArr<T, [...A, ""]>

type StringToArray<S extends string> = S extends `${infer F}${infer R}`
  ? [
      F extends `${infer D extends number}` ? D : never,
      ...(R extends "" ? [] : StringToArray<R>),
    ]
  : []

type NumberToArray<N extends number> = StringToArray<`${N}`>

type RecursiveArray<N extends number[]> = {
  [K in keyof N]: K extends `${number}` ? BuildArr<N[K]> : never
}

type GreaterThanSmall<A extends number, B extends number> =
  BuildArr<B> extends [...BuildArr<A>, ...infer _] ? false : true

type AnyOf<T extends readonly any[]> = T extends [infer First, ...infer Rest]
  ? First extends true
    ? true
    : AnyOf<Rest>
  : false

type CompareArrays<T1 extends any[][], T2 extends any[][]> =
  GreaterThanSmall<T1["length"], T2["length"]> extends true
    ? true
    : AnyOf<{
        [K in keyof T1]: K extends keyof T2
          ? GreaterThanSmall<T1[K]["length"], T2[K]["length"]>
          : false
      }>

type GreaterThan<T extends number, U extends number> = CompareArrays<
  RecursiveArray<NumberToArray<T>>,
  RecursiveArray<NumberToArray<U>>
>
```
