### ISSUE TITLE
3376 - InorderTraversal

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14093]
这题看上去很难，TS 怎么还能遍历树呢，其实是可以的，非常简单，和 JS 的思路是一致的，我们先看看 JS 是如何实现中序遍历的呢？

```javascript
const inorderTraversal = (root) => {
  if(!root) return []
  const res = []
  while(root) {
    inorderTraversal(root.left)
    res.push(val)
    inorderTraversal(tree.right)
  }
  return res
}
```

JS 是在 root 为 `null` 时结束，对于 `TS` 来说，实现递归，需要 `extends TreeNode` 而不是 `null` 来结束

不能使用 `null` 来判断是因为 `TS` 不能判断类型 `T` 是否符合 `TreeNode` 类型

```typescript
// 答案
interface TreeNode {
  val: number
  left: TreeNode | null
  right: TreeNode | null
}
type InorderTraversal<T extends TreeNode | null> = 
  [T] extends [TreeNode] 
    ? (
      [
        ...InorderTraversal<T['left']>,
        T['val'],
        ...InorderTraversal<T['right']>
      ]
    )
    : []
```

**Comment by zhaoyao91** [comment]
要点是 `[T] extends [TreeNode] ` 要用 `[]` 将 extends 两端包起来，避免 distributive conditional type

**Comment by misterhomer1992** [comment]
Hi. Could you please explain, why did you use [T] extends [TreeNode] over just T extends TreeNode, whats the point?

**Comment by ETRick** [comment]
> 

Use [T] extends [TreeNode]  to avoid triggers "distribution" of  T.
