### ISSUE TITLE
4803 - Trim Right By linjunc

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14113]
通过 `infer` 把末尾的空格清掉，递归前面的字符串

```typescript
type TrimRight<S extends string> = 
  S extends `${infer R}${' '}`
    ? TrimRight<R>
    : S
```

还有两个用例过不了，`\n` 和 `\t` 都需要清掉，那就补充一下过滤条件

```typescript
type TrimRight<S extends string> = 
  S extends `${infer R}${' ' | '\n' | '\t' }`
    ? TrimRight<R>
    : S
```

**Comment by jzllove9** [comment]
type TrimRight<S extends string> = S extends `${infer Left}${infer Right}` ? Right extends ' ' | '\n' | '\t' ? TrimRight<Left> : S : S; 为什么这种方式不可以呢？

**Comment by WweiweiSmile** [comment]
> type TrimRight<S extends string> = S extends `${infer Left}${infer Right}` ?
>  Right extends ' ' | '\n' | '\t' ? 
>     TrimRight<Left> 
>     : S 
> : S;
> 为什么这种方式不可以呢？

因为 Left是第一个字符，Right是剩下所有的字符。
