### ISSUE TITLE
5153 - IndexOf By linjunc

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14122]
又是一道关于数的题目，这种题大概率需要引入数组来计算它的 `length`，递归判断是否匹配

```typescript
type IndexOf<T, U, Count extends any[] = []> = 
  T extends [infer L, ...infer R]
    ? L extends U
      ? Count['length'] extends 0
        ? '-1'
        : Count['length']
      : IndexOf<R, U, [...Count, 0]>
    : -1 
```

但是挂了几个，其实写的时候就发现有坑了，这题的测试用例里有字符串，数字，布尔，因此单纯采用 `extends` 判断大概率挂了

因为 `1 extends number` 是返回 `true` 的，因此需要使用 `Equal` 来判断是否相等

```typescript
// 答案
type IndexOf<T, U, Count extends any[] = []> = 
  T extends [infer L, ...infer R]
    ? Equal<L, U> extends true
      ? Count['length'] extends 0
        ? '-1'
        : Count['length']
      : IndexOf<R, U, [...Count, 0]>
    : -1 
```

**Comment by nemo-shen** [comment]
这个看起来应该是有问题的，试试这个用例
`Expect<Equal<IndexOf<[1, 2, 3], 1>, 0>>`
期望是返回 `index === 0` 但实际上由于你代码里写了 `Count['length'] extends 0 ? -1` 则直接变成了-1

**Comment by nemo-shen** [comment]
我是用了两个值去存下标，一个是真正的下标，一个是计数的数组
```ts
type IndexOf<T extends any[], U extends number, L extends any[] = [], Idx extends number = -1>
  = T extends [infer F, ...infer R]
    ? Equal<F, U> extends true
      ? L['length']
      : IndexOf<R, U, [...L, F]>
    : Idx
```

**Comment by panjiangyi** [comment]
`1 extends number` is true, but `number extends 1` won't.

**Comment by unknowntocka** [comment]
判断数组长度是否为0那一步感觉有点多余噢  不能正确得到0下标了
my answer
`type IndexOf<T, U, C extends any[] = []> =
T extends [infer A, ...infer Rest]
  ? Equal<A, U> extends true
    ? C['length']
    : IndexOf<Rest, U, [...C, 1]>
  : -1`

**Comment by goddnsgit** [comment]
这题 any 类型是坑. 需要Equal可以轻松解决, 可是 ... 用原生的还玩什么 类型体操啊.

**Comment by goddnsgit** [comment]
type IndexOf<T extends any[], U, R extends any[] = []> =
    T extends [infer A, ... infer B extends any[]]
    ? A extends U
    ? [any] extends A
    ? IndexOf<B, U, R>
    : IndexOf<B, U, [...R, A]>
    : IndexOf<B, U, R>
    : R['length'] extends 0 ? -1 : R['length']

**Comment by Hencky** [comment]
> 这个看起来应该是有问题的，试试这个用例 `Expect<Equal<IndexOf<[1, 2, 3], 1>, 0>>` 期望是返回 `index === 0` 但实际上由于你代码里写了 `Count['length'] extends 0 ? -1` 则直接变成了-1

```ts
 Expect<Equal<IndexOf<[1, 2, 3], 2>, 1>>,
```

**Comment by cppHusky** [comment]
> type IndexOf<T extends any[], U, R extends any[] = []> = T extends [infer A, ... infer B extends any[]] ? A extends U ? [any] extends A ? IndexOf<B, U, R> : IndexOf<B, U, [...R, A]> : IndexOf<B, U, R> : R['length'] extends 0 ? -1 : R['length']

琢磨了一下你的写法，感觉不得要领，所以我又写了几个例子想测试一下，却发现似乎存在一些问题。

```ts
type IndexOf<T extends any[], U, R extends any[] = []> =
T extends [infer A, ... infer B extends any[]]
	? A extends U
		? [any] extends A
			? IndexOf<B, U, R>
			: IndexOf<B, U, [...R, A]>
		: IndexOf<B, U, R>
	: R['length'] extends 0 ? -1 : R['length']
const a:IndexOf<[string,1,number,'a',any],any>=4
const b:IndexOf<[any,1],1>=1
const c:IndexOf<[0,any,1],1>=1
const d:IndexOf<[0,any,1],any>=2
const e:IndexOf<[0,-1,any,1],1>=1
const r:IndexOf<[0,-1,any,1],any>=3
```

这里的预期情况是 `c=2; d=1; e=3; f=2;`，但是 `IndexOf` 都求错了。

这个做法可能是因为运气好，刚好通过了题目的例子；但是它仍然不对。

我试图修正这段代码，但因为对 `any` 了解十分有限，暂时没有头绪。

**Comment by djdidi** [comment]
```ts
type StrictEquals<T, U> = T extends U ? U extends T ? true : false : false;

type IndexOf<T extends unknown[], U, Count extends unknown[] = []> =
  T extends [infer F, ...infer Rest]
    ? StrictEquals<F, U> extends true
      ? Count['length']
      : IndexOf<Rest, U, [...Count, unknown]>
    : -1;
```

这个更简洁哦
