### ISSUE TITLE
5360 - Unique By linjunc

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14151]
这题需要借助辅助数组，通过递归的方式，依次把数组中没有的内容塞进去

```typescript
Includes<R, U> extends true
      ? Unique<F, [...U]>
      : Unique<F, [...U, R]>
```

这里就是递归的核心逻辑，如果数组 `U` 中不包含该元素，就塞进去，有就不塞

一开始判断数组中是否存在该元素，采用的是 `R extends U[number]` 但是发现有很多 case 没有考虑到

因此需要实现一个 `Includes` 方法来判断是否有该值，这个方法也是常规的递归实现，不多赘述

```typescript
// 答案
type Includes<T, U> = U extends [infer F, ...infer Rest] 
  ? Equal<F, T> extends true 
    ? true 
    : Includes<T, Rest> 
  : false;

type Unique<T, U extends any[] = []> = 
  T extends [infer R, ...infer F]
    ? Includes<R, U> extends true
      ? Unique<F, [...U]>
      : Unique<F, [...U, R]>
    : U
```

**Comment by linxiaowu66** [comment]
> Equal 工具函数有点看不懂，有没有大佬解释一下

参考：https://github.com/type-challenges/type-challenges/discussions/9100#discussioncomment-6896958.

**Comment by shx123qwe** [comment]
> Equal 工具函数有点看不懂，有没有大佬解释一下

```
type Equal<X, Y> = (<T>() => T extends X ? 1 : 0) 
                                extends 
                                (<T>() => T extends Y ? 1 : 0)
                                ? true
                                : false;
```
Equal工具类型的源代码是这个，它采用了一种函数的结构来对两个类型进行比较，在上述代码中，T会被TS的类型推断机制推断为任何可能的类型，也就是所有你熟知的类型，当T extends X和T extends Y两个条件类型得出来的结果总是一样的，那么X和Y就一定是相同的类型，否则，有一种结果不同，那就是不同的。
例如，当X为string类型，Y为字面类型'ABC'时，当T被推断为number类型时，两者都是0，那么是一样的，当T被推断为string时，那么第一个就是0，第二个就是1，那就是不一样的。如果以后遇到需要判断两个类型是否一致，那就可以一直使用这个工具类型。

**Comment by meetAndEgg** [comment]
为什么我把第四行中的`Unique<Rest, [...U, P]>`改为`Unique<Rest, [P,...U]>`就不行了
```typescript
type Unique<T extends unknown[], U extends unknown[] = []> = T extends [infer P, ...infer Rest]
  ? Include<U, P> extends true
    ? Unique<Rest, U>
    : Unique<Rest, [...U, P]> // 这里改为 Unique<Rest, [P,...U]> 会失效
  : U
```
![image](https://github.com/user-attachments/assets/0ef8002f-e1a9-46c6-80ba-8ef9c052d497)

**Comment by ChenJiZhou** [comment]
> 为什么我把第四行中的`Unique<Rest, [...U, P]>`改为`Unique<Rest, [P,...U]>`就不行了
> 
> type Unique<T extends unknown[], U extends unknown[] = []> = T extends [infer P, ...infer Rest]
>   ? Include<U, P> extends true
>     ? Unique<Rest, U>
>     : Unique<Rest, [...U, P]> // 这里改为 Unique<Rest, [P,...U]> 会失效
>   : U
> ![image](https://github.com/user-attachments/assets/0ef8002f-e1a9-46c6-80ba-8ef9c052d497)

最后返回的结果，顺序错了
