### ISSUE TITLE
7544 - Construct Tuple 【小丞同学】

### ISSUE THREAD

**Issue by linjunc** [type-challenges/type-challenges#14153]
这题非常有意思，如果不追求完美的话，非常简单，我们只需要用 `infer` + 递归 就可以了

```typescript
type ConstructTuple<L extends number, U extends unknown[] = []> = 
  U['length'] extends L
    ? U
    : ConstructTuple<L, [...U, unknown]>
```

但是 TS 中递归最多只能 1000 次，因此入参到了 `1000` 就会挂掉，测试用例最后有一个边界 case 就是 1000，那就说明有其他方法实现

既然没有办法递归这么多次，那么我们可以换个思路，怎么把递归次数降下来

我们想想 `9999 = 9 * 100 + 99 * 10 + 9 * 10 + 9`,那么我们是不是可以通过这样的方法来递归呢

每次取数字的第一位，返回该长度的数组，例如 `23`,第一次就返回 `[unknown, unknown]`,

递归第二个数字的时候，我们需要**把上一次的`数组长度 * 10`**，怎么实现呢

```typescript
[...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T]
```

我们可以接受数组 T，展开 10 次，这样就实现了，那么本次的数字（3）就是在它后面加几个 `unknown`

```typescript
[...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown],
```

这样第一次 返回的 `T` 是 `[unknown, unknown]`,第二次解构后，就会得到 20 个，再加上 3 个本次的，`length` 就达到了，递归的次数也大大的缩减了

那么我们就需要构造 `0-9` 数字对应的展开搭配，就有了下面的答案，其中 `N<Count>[keyof N & F]` 中 `[keyof N & F]` 就是数字，例如 `9` 就是 `N<Count>[9]`,也就对应 `N['9']`

```typescript
// 本题答案
type ConstructTuple<L extends number, O extends string = `${L}`, Count extends unknown[] = []> =
  O extends `${infer F}${infer R}` ? (
    ConstructTuple<L, R, N<Count>[keyof N & F]>
  ) : Count

type N<T extends unknown[] = []> = {
  '0': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T],
  '1': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown],
  '2': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown],
  '3': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown],
  '4': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown],
  '5': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown],
  '6': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown],
  '7': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
  '8': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
  '9': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
}
```

**Comment by alexfung888** [comment]
while it is a superior answer, it fails the last test:

```
  // @ts-expect-error
  Expect<Equal<ConstructTuple<1000>['length'], 1000>>
```
which is meant to result in error.

**Comment by linjunc** [comment]
> while it is a superior answer, it fails the last test:
> 
> ```
>   // @ts-expect-error
>   Expect<Equal<ConstructTuple<1000>['length'], 1000>>
> ```
> 
> which is meant to result in error.

No ! I just tried it and it is correct! Pass the test! Including 9999, that's right!

**Comment by alexfung888** [comment]
> > while it is a superior answer, it fails the last test:
> > ```
> >   // @ts-expect-error
> >   Expect<Equal<ConstructTuple<1000>['length'], 1000>>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is meant to result in error.
> 
> No ! I just tried it and it is correct! Pass the test! Including 9999, that's right!

The problem is that it passes the 1000 test, which the question asked it to be failed.

**Comment by WisestCoder** [comment]
```typescript
type ConstructTupleUnit<T extends number | string, U extends any[] = []> = `${U['length']}` extends `${T}` ? U : ConstructTupleUnit<T, [unknown, ...U]>
type X10<T extends unknown[] = []> = [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T]
type ConstructTuple<T extends number | string, U extends unknown[] = []> = `${T}` extends `${infer L}${infer R}`
  ? ConstructTuple<R, [...ConstructTupleUnit<L>, ...X10<U>]>
  : U
```

**Comment by Qzhor** [comment]
nb

**Comment by Qzhor** [comment]
> 这题非常有意思，如果不追求完美的话，非常简单，我们只需要用 `infer` + 递归 就可以了
> 
> ```ts
> type ConstructTuple<L extends number, U extends unknown[] = []> = 
>   U['length'] extends L
>     ? U
>     : ConstructTuple<L, [...U, unknown]>
> ```
> 
> 但是 TS 中递归最多只能 1000 次，因此入参到了 `1000` 就会挂掉，测试用例最后有一个边界 case 就是 1000，那就说明有其他方法实现
> 
> 既然没有办法递归这么多次，那么我们可以换个思路，怎么把递归次数降下来
> 
> 我们想想 `9999 = 9 * 100 + 99 * 10 + 9 * 10 + 9`,那么我们是不是可以通过这样的方法来递归呢
> 
> 每次取数字的第一位，返回该长度的数组，例如 `23`,第一次就返回 `[unknown, unknown]`,
> 
> 递归第二个数字的时候，我们需要**把上一次的`数组长度 * 10`**，怎么实现呢
> 
> ```ts
> [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T]
> ```
> 
> 我们可以接受数组 T，展开 10 次，这样就实现了，那么本次的数字（3）就是在它后面加几个 `unknown`
> 
> ```ts
> [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown],
> ```
> 
> 这样第一次 返回的 `T` 是 `[unknown, unknown]`,第二次解构后，就会得到 20 个，再加上 3 个本次的，`length` 就达到了，递归的次数也大大的缩减了
> 
> 那么我们就需要构造 `0-9` 数字对应的展开搭配，就有了下面的答案，其中 `N<Count>[keyof N & F]` 中 `[keyof N & F]` 就是数字，例如 `9` 就是 `N<Count>[9]`,也就对应 `N['9']`
> 
> ```ts
> // 本题答案
> type ConstructTuple<L extends number, O extends string = `${L}`, Count extends unknown[] = []> =
>   O extends `${infer F}${infer R}` ? (
>     ConstructTuple<L, R, N<Count>[keyof N & F]>
>   ) : Count
> 
> type N<T extends unknown[] = []> = {
>   '0': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T],
>   '1': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown],
>   '2': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown],
>   '3': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown],
>   '4': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown],
>   '5': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown],
>   '6': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown],
>   '7': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
>   '8': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
>   '9': [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown],
> }
> ```

nb，递归次数下降到数字的个数

**Comment by Qzhor** [comment]
nb，递归次数下降到数字的个数

**Comment by alexfung888** [comment]
Please look at the question carefully.
```ts
type cases = [
  Expect<Equal<ConstructTuple<0>, []>>,
  Expect<Equal<ConstructTuple<2>, [unknown, unknown]>>,
  Expect<Equal<ConstructTuple<999>['length'], 999>>,
  // @ts-expect-error
  Expect<Equal<ConstructTuple<1000>['length'], 1000>>,
]
```
The answer need to succeed with 999 and must fail with 1000. Your solution works fine with 1000, and that's why it is not a correct answer.

**Comment by tototi5997** [comment]
> Please look at the question carefully.
> 
> ```ts
> type cases = [
>   Expect<Equal<ConstructTuple<0>, []>>,
>   Expect<Equal<ConstructTuple<2>, [unknown, unknown]>>,
>   Expect<Equal<ConstructTuple<999>['length'], 999>>,
>   // @ts-expect-error
>   Expect<Equal<ConstructTuple<1000>['length'], 1000>>,
> ]
> ```
> 
> The answer need to succeed with 999 and must fail with 1000. Your solution works fine with 1000, and that's why it is not a correct answer.

Maybe you didn't understand what he meant, He just wants to find a perfect solution for values ​​outside the bounds

**Comment by goddnsgit** [comment]
作者做这道题的时候是不是没有尾递归? 忘了以前怎么做的,但是现在直接使用尾递归轻松搞定.
type ConstructTuple<L, A extends any[] = []>
  = A['length'] extends L ? A : ConstructTuple<L, [...A, unknown]>

**Comment by sciencefunq** [comment]
The solution performs better. However, the maximum array length allowed to be constructed is 9999.
