### ISSUE TITLE
2257 - MinusOne (explanation with other's code)

### ISSUE THREAD

**Issue by baeharam** [type-challenges/type-challenges#14499]
I couldn't solve so I studied @Chen0x00 's [answer](https://github.com/type-challenges/type-challenges/issues/2586).

1. To check current string is `0-9`, let's define digit type.
```ts
type Digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
```

2. To get number from string, we need array because can get `length` from array. This is the key of this problem. So, we need converter to convert digit type to array.

```ts
type ConvertDigitToArray<N extends Digit, DigitArray extends any[] = []>
  = `${DigitArray['length']}` extends N ? DigitArray : ConvertDigitToArray<N, [...DigitArray, 0]>;
```
`0` can be any value because it just for `length` property.

3. To express 10, 100, 1000.. digits, we need util type to multiply 10 type element.

```ts
type Multiply10<T extends any[]> = [...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T, ...T];
```

4. To convert number to array, let's combine above types into single util type. In this type, we use recursive typing with template literal string. At each digit, we use `Multiply10` to get proper digit and conver it to digitarray to express proper number.

```ts
type ToArray<S extends string | number, T extends any[] = []>
  = `${S}` extends `${infer F}${infer L}` ? F extends Digit ? ToArray<L, [...Multiply10<T>, ...ConvertDigitToArray<F>]> : never
  : T;
```

5. Finally, let's destruct number which is converted to array and compute "minus 1".

```ts
type Minus<S extends number, T extends number>
  = ToArray<S> extends [...ToArray<T>, ...infer L] ? L['length'] : 0;

type MinusOne<S extends number> = Minus<S, 1>;
```

**Comment by likepeach789** [comment]
This is a great explanation! Thank you so much.
