### ISSUE TITLE
2688 - StartsWith

### ISSUE THREAD

**Issue by Stan-BK** [type-challenges/type-challenges#14676]
```ts
// your answers
type StartsWith<T extends string, U extends string> = 
T extends `${infer J}${infer K}` ? U extends `${infer N}${infer M}` 
                                   ? J extends N
                                      ? StartsWith<K, M> 
                                      : false 
                                   : true
                                 : false
```

**Comment by Stan-BK** [comment]
// new answer, cover the case Equal<StartsWith<'abc', 'abc'>, true>
T extends `${infer J}${infer K}` ? U extends `${infer N}${infer M}` 
                                   ? J extends N
                                      ? StartsWith<K, M> 
                                      : false 
                                   : true
                                 : T extends U ? true : false

**Comment by Gu-Miao** [comment]
Why judge character by character? 🤔 `` T extends `${U}${infer R}` `` maybe better.

**Comment by Stan-BK** [comment]
Sure, thanks for advice.> Why judge character by character? 🤔 `` T extends `${U}${infer R}` `` maybe better.

**Comment by Stan-BK** [comment]
type StartsWith<T extends string, U extends string> = T extends `${U}${string}`? true : false
