### ISSUE TITLE
Definition of `Equal`?

### ISSUE THREAD

**Issue by Means88** [type-challenges/type-challenges#153]
```ts
type A = { a: string; b: string };
type B = { a: string };
type C = { b: string };

// type Equal<X, Y> = <T>() => (T extends X ? 1 : 2) extends <T>() => (T extends Y ? 1 : 2) ? true : false;
/** --- Error --- */
type E0 = Expect<Equal<A, B & C>>; // Type 'false' does not satisfy the constraint 'true'.(2344)
/** ------------- */
type E1 = Expect<A extends B & C ? true : false>;
type E2 = Expect<B & C extends A ? true : false>;
```

https://github.com/microsoft/TypeScript/issues/27024#issuecomment-421529650
> ...which fails because the definition of "identical" doesn't allow an intersection type to be identical to an object type with the same properties.

Is there any negative case `T` that `T extends A` different from `T extends B & C`?

**Comment by Means88** [comment]
related https://github.com/type-challenges/type-challenges/issues/9#issuecomment-687403405

**Comment by antfu** [comment]
Thanks, I made an update to the utils. `Equal` refers to "Strictly equal" while `Alike` refers to "Strcuturely equal". So in this case `Expect<Alike<A, B & C>>` would be true while `Expect<Equal<A, B & C>>` will still fail.
