### ISSUE TITLE
5 - Get Readonly Keys

### ISSUE THREAD

**Issue by kalivaslime** [type-challenges/type-challenges#15850]
```ts
type MyReadonly<T> = {
    readonly [K in keyof T]: T[K];
};
```

**Comment by kalivaslime** [comment]
Get ReadOnly Keys Solution

**Comment by trinhvinhtruong96** [comment]
this is Readonly solution, not get readonly key bro

**Comment by m7mdtiger** [comment]
> this is Readonly solution, not get readonly key bro

Please, would you explain the difference?

**Comment by trinhvinhtruong96** [comment]
type GetReadonlyObject<T> = {
  [Properties in keyof T as Equal<Pick<T, Properties>, Readonly<Pick<T, Properties>>> extends true ? Properties : never]: T[Properties]
}

type GetReadonlyKeys<T> = keyof GetReadonlyObject<T>

you can take a look at this solution @m7mdtiger
