### ISSUE TITLE
14 - First of Array --->三种答案

### ISSUE THREAD

**Issue by Macrohoo** [type-challenges/type-challenges#16315]
```ts
// your answers
//answer1
type First<T extends any[]> = T extends [] ? never : T[0]

//answer2
type First<T extends any[]> = T['length'] extends 0 ? never : T[0]

//answer3
type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never
```

**Comment by fourpixels** [comment]
Hey guys, can I ask why `T extends []` works?

**Comment by Macrohoo** [comment]
> Hey guys, can I ask why `T extends []` works?

T extends [] means "is T  an empty array"

**Comment by f0nar** [comment]
one more
`type First<T extends any[]> = T[number] extends never ? never : T[0];`

**Comment by 1181982511** [comment]
> Hey guys, can I ask why `T extends []` works?

no thanks，make your brain work and stand in the coner all day bro

**Comment by lhy14160** [comment]
只想到了infer其它没想到hhh

**Comment by patwadeepak** [comment]
One more -
```typescript
type First<T extends any[]> = '0' extends keyof T ? T[0] : never
```

**Comment by idonteatcookie** [comment]
May I know the reason behind receiving 'never' in this situation, please?

```ts
type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never

const arr = [1, 2, 3];
type ArrType = typeof arr
type ArrFirstType = First<ArrType>; // never
```

**Comment by OmerGBlink** [comment]
another one: 

type First<T extends any[]> = T[number] extends never ? never : T[0]

**Comment by mrlectus** [comment]
> Hey guys, can I ask why `T extends []` works?

Yeah it is not intuitive why it works.... You would think T extends [] should mean T extends an Array? but it actually mean T extends an "empty" Array.

**Comment by 425824365** [comment]
> 多一个 `type First<T extends any[]> = T[number] extends never ? never : T[0];`
Exception output occurred

type First<T extends any[]> = T[number] extends never ? never : T[0];
type ArrFirstType = First<any[]>; // string

**Comment by 425824365** [comment]
> one more `type First<T extends any[]> = T[number] extends never ? never : T[0];`


type First<T extends any[]> = T[number] extends never ? never : T[0];
let number: First<[1]> = 1
There seems to be a problem

**Comment by gjssss** [comment]
```
type First<T extends any[]> = T[number] extends never ? never : T[0]
```

**Comment by gjssss** [comment]
@ogzhanolguncu There is a Test `Expect<Equal<First<[]>, never>>`, it means you should return `never` when you get then empty array. But in this condition, `T[0]` returns `undefined`.
By the way, you can run it in playground and find the error info.

**Comment by GodAraden** [comment]
> May I know the reason behind receiving 'never' in this situation, please?
> 
> ```ts
> type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never
> 
> const arr = [1, 2, 3];
> type ArrType = typeof arr
> type ArrFirstType = First<ArrType>; // never
> ```

The type of arr is number [], and the question is to perform a type conversion on a tuple type such as [1,2,3]

arr 的类型是 number[]，题目中是对 [1,2,3] 这样的一个元组类型做类型转换

**Comment by daqic** [comment]
> May I know the reason behind receiving 'never' in this situation, please?
> 
> ```ts
> type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never
> 
> const arr = [1, 2, 3];
> type ArrType = typeof arr
> type ArrFirstType = First<ArrType>; // never
> ```

ArrType meanings （ 1 ｜ 2 ｜ 3 ）

**Comment by XueshenWu** [comment]
My solution is type First<T extends any[]> = T extends {0:any}?T[0]:never;. Quite similar as type First<T extends any[]> = T['length'] extends 0 ? never : T[0].

**Comment by 4674ghkbvgy** [comment]
> My solution is: 我的解决方案是： ` type First<T extends any[]> = T extends {0:any}?T[0]:never;` Quite similar as 与 `type First<T extends any[]> = T['length'] extends 0 ? never : T[0];`

type First<T extends any[]> = T extends { 0:any} ? T[0]:never
type First<T extends any[]> = T extends {0 :T[0]} ? T[0]:never
type First<T extends any[]> = T['length'] extends 0? never:T[0]
type First<T extends any[]> = T extends {length:0}? never:T[0]
Did some combinations on the code

**Comment by jamesbarrett95** [comment]
Here's how I finished it:

`type First<T> = T extends [any, ...any[]] ? T[0] : never;`

Answer 3 is my favourite though since it uses `infer` :)

**Comment by timrutter** [comment]
please could someone give me a reason why you would actually want to do this?  I can't really see how this would ever be useful.

**Comment by shx123qwe** [comment]
> Hey guys, can I ask why `T extends []` works?

so why not?if T null ,it extends []

**Comment by Paxton233** [comment]
What's the difference between
`type First<T extends any[]> = '0' extends keyof T ? T[0] : never;`
and
`type First<T extends any[]> = 0 extends keyof T ? T[0] : never;`

Why did the latter one go wrong?

**Comment by xifeng-jin** [comment]
> ```ts
> // your answers
> //answer1
> type First<T extends any[]> = T extends [] ? never : T[0]
> 
> //answer2
> type First<T extends any[]> = T['length'] extends 0 ? never : T[0]
> 
> //answer3
> type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never
> ```

第三个是不是有点问题，换成这样会不会好点
type A61<T extends any[]> = T extends (infer U)[] ? U : never;

**Comment by bubokko** [comment]
My solution:

```typescript
type First<T extends any[]> = T extends [x: any, ...rest: any[]] ? T[0] : never
```

**Comment by timgent** [comment]
How about: 
```
type First<T extends [first: any, ...rest: any[]]> = T[0]
```
It doesn't pass the `First<[]>` test though because it doesn't allow it at all

**Comment by nanaMonsoon** [comment]
> What's the difference between这两者之间有什么区别？ `type First<T extends any[]> = '0' extends keyof T ? T[0] : never;` and 和 `type First<T extends any[]> = 0 extends keyof T ? T[0] : never;`
> 
> Why did the latter one go wrong?后者为什么会出错？

because TS allow it use string key to check, I think

**Comment by Lovely-Ruby** [comment]
```ts
type First<T extends any[]> = T extends [infer A, ...infer rest] ? A : never
// ide tell me: 'rest' is declared but its value is never read.ts(6133)
```

```ts
// isn't it ok?
type First<T extends any[]> = T extends [infer A, ...any] ? A : never
```

**Comment by maximgatilin** [comment]
> please could someone give me a reason why you would actually want to do this? I can't really see how this would ever be useful.

Because the whole reason of these typescript challenges is to do weird things to learn typescript deeper, rather than write production-like code
