### ISSUE TITLE
3376 - InorderTraversal

### ISSUE THREAD

**Issue by CodeDesign99** [type-challenges/type-challenges#17527]
```ts
interface TreeNode {
  val: number
  left: TreeNode | null
  right: TreeNode | null
}
```
```ts
// T extends TreeNode
type InorderTraversal<T extends TreeNode | null> = T extends TreeNode
  ? T['left'] extends TreeNode
    ? T['right'] extends TreeNode
      ? [...InorderTraversal<T['left']>, T['val'], ...InorderTraversal<T['right']>]
      : [...InorderTraversal<T['left']>, T['val']]
    : T['right'] extends TreeNode
      ? [T['val'], ...InorderTraversal<T['right']>]
      : [T['val']]
  : []
```
```ts
// [T] extends [TreeNode]
type InorderTraversal<T extends TreeNode | null> = [T] extends [TreeNode]
  ? [...InorderTraversal<T['left']>, T['val'], ...InorderTraversal<T['right']>]
  : []
```

**Comment by ARTurnerGit** [comment]
Can I just ask what the difference is between `T extends TreeNode` and `[T] extends `[TreeNode]`. I have been trying to figure this out for a while and can't even find the right terms to search for.

**Comment by CodeDesign99** [comment]
> Can I just ask what the difference is between `T extends TreeNode` and `[T] extends [TreeNode]` for that first ternary? I have been trying to figure this out for a while and can't even find the right terms to search for.
> 
> I know that this is useful for checking if something is `never` as well, but can't completely get my head around why. It looks to me like we're comparing tuples, but I can't quite see why the two cases are different here. Any help appreciated.

[microsoft/TypeScript#31751](https://github.com/microsoft/TypeScript/issues/31751)
[distributive-conditional-types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)

hope this can help you.
