### ISSUE TITLE
8 - Readonly 2

### ISSUE THREAD

**Issue by santosmarco-caribou** [type-challenges/type-challenges#18130]
```ts
type MyReadonly2<T extends Record<PropertyKey, any>, K extends keyof T = keyof T> = {
  readonly [Key in K]: T[Key]
} & {
  [Key in Exclude<keyof T, K>]: T[Key]
}
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBAcELQQEoFMCGATA9gOwDYE8IAmSeOci0gI0IEFsAXACx0IDEBXCACgAFVGAMw4BKCAGIAtsnQBLDpIkAnNFjyFxmKgCtkAYwZwA1snwBnUqXHWIARQ7IzDWTktQAkpIAOuZNMYQqBAA5sjYyEqyehAABgCy+CgYOAREADwAKgA0EADSAHwxEADuTFFMEAyoJmaVxZiV+F7IgUrBCmEMsRlFAuixuTEAdG4DRWbNerKChMwtZshdmIIQXkqYzUrOjhDL3UXMqF1mLBy4-QtdDA1JagRDEADqTGFjELK12Jhda5gAbrJ0DIcrJjqdzhBJNUWqhcLhVutNttaipkuoINoOE4ILhZCZKi8IF8lFD4TFbil8JlCiMoKQ2JglBBkAAPVDeXyjGLchgWKCyRgRQSoPQtDKYLAQADepCgzgYvgAXBAnJFsMFZRAgWY9JEvM4cMrVQKNVAoHpMBzFjJlVRMJhfAJSABfUYW7DY65YZUJCnqdLirA5ADk8t8wYgAB8IMHtbrZPqXNhg-kIABeaWasPIZUAIgAEqZc1lNXG9QbsHnBPaqKglMXNRarQwbRBhbgFiWoK66XKJZghtn0xAC8g4ZhcxBgMAIABRJTrJTKvQCL5dVFmMyyYLYQIQVF3Qi-JH4UhegdlhMV4e52tKBkTqcz+eL5er777tCb7e7oIHykIhsEQMKefZYEMTY+Na-QZgwSgOE+EAAPK5KQ3IxKMqYAGqyMgxS7LuADioL5hwVDKkwDAMF4ZiKtOvJ6EwQzaGYQyMsEwDQGAIDAGAfGgBAAD6wkiaJIkQAAmpgHBMgAwhKLSFioQliapgkQDxfEgc0EC+qolIBsyLIttg6C1CgFpKOgaQAAqIsB+C5KYOQCPg+Q5LkRkmWZEAmPgewZMOfkBamGYylA-7ogA2k5hACnkAC6yoZDFpgJWAzoQAAZJmUCpXFu6ziyei4BwQJpMFKzZHk+RJRAKWxelrr8SAKlqaJ9WOF0smoAstTtWJGm8bI3iMlcTQtFKEC0LiJg5EVkxdJlgjrIowa8NpyBwIxsK+OqjjABwzgdsGWkTRAK59cOUWkAt+gMGkM14sgaR6WiqSZP2ACM7lIPp6ifVgP35O5t0sotj2zS9b2HgG30htmEbRrGjjxomOApvN4P3TIINdnO2MGJDz2vYk-0fYGmBEAjoLhlGMaXujya-XdBi46D6VgNOEAbWYcCsot-MLoyYCbcywtMhmMMGYDmBfTTCrIEjMYCn8sKAimfECi2SjCqK9XfbllS0zmKpwSapCMxWAD8Rrm+qpCQb4LboLa9qOtgGVa4KusimK-ZEEbkUEMbit22qppaqj5ZJrbZsR47lpQS7bsOmgnvNdrQp+wTi0yEH5OzCb4cWxFhdRzqMc4HHxoO+aSfO62dpp06zUtW1A3qZwWwvEyADKLY0R3A1DVz4BQKmfdMHWLT+TJKoOkdSa0RAlHUbR9E6kxLFsW0nHAAIZjFBEpDYbh+FmIvFYr2vNF0cADHb6x7H75fpXX6fumMi0snT3CYShBvlRO+m9GLMWfm0bivEwBAA)

**Comment by YqxLzx** [comment]
cool

**Comment by ImTemporaryHere** [comment]
pls help to understand this part  = keyof T

**Comment by santosmarco-caribou** [comment]
> pls help to understand this part  = keyof T 

`= keyof T` is a default for the generic parameter so that, if not passed, we default to transform every key to readonly. However, if passed, we transform only those keys.
