### ISSUE TITLE
All

### ISSUE THREAD

**Issue by cutefcc** [type-challenges/type-challenges#18142]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

```yaml
difficulty: medium
title: All
author:
  github: cutefcc
  name: cutefcc
tags: array
```

## Question

Returns true if all elements of the list are equal to the second parameter passed in, false if there are any mismatches.

For example

```ts
type Test1 = [1, 1, 1]
type Test2 = [1, 1, 2]

type Todo = All<Test1, 1> // should be same as true
type Todo2 = All<Test2, 1> // should be same as false
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type All = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<All<[1, 1, 1], 1>, true>>,
  Expect<Equal<All<[1, 1, 2], 1>, false>>,
  Expect<Equal<All<["1", "1", "1"], "1">, true>>,
  Expect<Equal<All<["1", "1", "1"], 1>, false>>,
  Expect<Equal<All<[number, number, number], number>, true>>,
  Expect<Equal<All<[number, number, string], number>, false>>,
  Expect<Equal<All<[null, null, null], null>, true>>,
  Expect<Equal<All<[[1], [1], [1]], [1]>, true>>,
  Expect<Equal<All<[{}, {}, {}], {}>, true>>,
];
```

**Comment by jiangshanmeta** [comment]
@cutefcc 
Does "match the predicate" mean that the second parameter in type ```All``` is the predicate and every element in the list is the subset ( or equal ) of the predicate ?

All的第二个参数是predicate？match的含义是子集还是相等？ 描述不太清楚呢

**Comment by cutefcc** [comment]
@jiangshanmeta    I think it should be equal

**Comment by cutefcc** [comment]
@jiangshanmeta   I will modify the description and resubmit the issue

**Comment by jiangshanmeta** [comment]
> @jiangshanmeta I will modify the description and resubmit the issue

You can edit directly. Dont't submit a new issue.

**Comment by cutefcc** [comment]
@jiangshanmeta  updated
