### ISSUE TITLE
43 - Exclude

### ISSUE THREAD

**Issue by mefengl** [type-challenges/type-challenges#18522]
```ts
// extends can be used in two ways
// one is a real extends
// another is a question with the traverse of T, called Distributive Conditional Types
// second one can be used in a fun way, like Flatten
// type Flatten<T> = T extends any[] ? T [number]: T;
type MyExclude<T, U> = T extends U ? never : T
// https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
```

**Comment by loia5tqd001** [comment]
Distributivity. Indeed a very important concept here.

**Comment by f0nar** [comment]
is it all the time applied only to first generic parameter?

**Comment by mwashief** [comment]
> is it all the time applied only to first generic parameter?

Normally how `extends` keyword works, it distributes both operands. If you need to prevent distribution any of the operands, then use square brackets. For example- `[T] extends U` or `T extends [U]`. Also, `[T] extends [U]` won't distribute any of the operands.
