### ISSUE TITLE
2757 - PartialByKeys

### ISSUE THREAD

**Issue by santosmarco-caribou** [type-challenges/type-challenges#18604]
```ts
type PartialByKeys<T, K extends keyof T = keyof T> = {
  [Key in Exclude<keyof T, K>]: T[Key]
} & {
  [Key in K]?: T[Key]
} extends infer R
  ? {
      [Key in keyof R]: R[Key]
    }
  : never
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBBMDsCssIFoIAUCGAnALgSwwBsAhATwGkBTUgZ0hWUafoCNSIArAgOwHMaAFhm4QAFAAEuw-kO4BbSjgwBKCAGIFAEzwBXOeoD2LDpQDGOevTXWIARR2Ua+A90tQAknIAOhSgu44EBgQvJTclFh4phAABpi4BCQU1DQAPAAqADQQ5AB8MRAA7gJRAhBKANaO5YUG5aRelEFYvHphgTHpBcKaseQxAHRufQU0jaZ4AGbsOAJNNIoQBpMQXlgGjQnVy7Fd5UKBggY6hL0LgTh1LE0bztxEAxAA6nMiMf0QeDQQ3AaBawYAG54TSUTTZPCHATHU4QOQYKpBQiEVbrTb4bZeO5ETg6JwQQh4RGzJq-LDwlFxbD4IgZfJDKD0ABiBiwEEoAA8MN5fMMYvycA1HKZIlj6HgAhFJhhTE0AKoLNkAb3oUHuCgAXBAnJE+KqgqEtdw9NcsPqMJpNFhHDQtTqJbx6ABfYaCxoQBUReI0wgAOW5TQAvOhqYkyFRaKlPVhsgBydWUWO5CDAYAQJU-AMAfg19r4AG4DZQNca5KbCxarTbczhdbwIC6oPyYsNkwA1PCUQpLEQAcUhAAkdCwtQIcDgvLbUzgaKYBAMODQBqzeMA4IgwCBgGAd6AIAB9Q9H49HiAATWObIAwgZQRABxEmifn4eIFud26mt6w8lI1kcuyHI4GEmjfFUpA7OkEDBuBkHJsGKpQAA2hGnwiAAohypiEDooKpLBKz-nkAC6WrpCh1DEWAToQAAZOm9AUewEo5MROYQOREZUTRnLAdwoFoZMEQQAASvQWYMVAUkQExaEQARomkaJTFUdJjYQEalCAhEO5gHuL7PhxjiBFeGALN8Bknm+254N4rIXEK6YQOhACOOhENkmHjIENGTOs+ixuIn7IHORC+HwjjADo+CEDQsY7hKwFYNKsoeoqkmZpq2q1g69AYIaPwmjpUCVtaNC2tldbUQlkrJTK8qKt+RD+goGUJuxeaOiVBWlqaeWWmVFWddVYCJVK9VpV6obNQGACC-GzaEbXZnaOV6t1lDsb1xVBAN1aVblLpgJ+ECmGZ1TBkh9BeWYOCpK57mEKkTVJBGaTRnGCZJtk0YvS1lC5LkmTXRy3n3W5tIveGKRRoqn0BrGEAAD4QLG+WJkDk1YH9c0LaEgPA1AN3mODj3PdNr0w9GmMvbDESA0D9CphAQU0MgnLeezWDrGaROg7dpOQxT0ORh9qNfcjqM6NwFS-IU3DfVjOMKATYBUbp+mWaeTI6LgcxsgAysBk4Hlrr7vqA9DJgbQjWhAEG69qBg4XcFVjhOU7ADOc4LkuK5rggsDAMINCFDt7adt2NDO9FeAuG746Thq06zvOi7Li0AeIMA0cu3H3B0FAyYALKsk0V5CMiYShAnHvJ17qe+xnjrvmAQA)

**Comment by dlrandy** [comment]
@santosmarco-caribou Hello, why we need this condition?:{
  [Key in K]?: T[Key]
} extends infer R

**Comment by chenbowu** [comment]
> @santosmarco-caribou Hello, why we need this condition?:{ [Key in K]?: T[Key] } extends infer R
``` TS
({
  [Key in Exclude<keyof T, K>]: T[Key]
} & {
  [Key in K]?: T[Key]
})
```
Because this is a Intersection Types

We need to remap it to a new object type

**Comment by dlrandy** [comment]
> > @santosmarco-caribou Hello, why we need this condition?:{ [Key in K]?: T[Key] } extends infer R
> 
> ```ts
> ({
>   [Key in Exclude<keyof T, K>]: T[Key]
> } & {
>   [Key in K]?: T[Key]
> })
> ```
> 
> Because this is a Intersection Types
> 
> We need to remap it to a new object type

Does it mean intersection type only have known property,  in fact we need a object type which have more properties than intersection?
