### ISSUE TITLE
5153 - IndexOf

### ISSUE THREAD

**Issue by santosmarco-caribou** [type-challenges/type-challenges#18777]
```ts
type IsEqual<A, B> = (<T>() => T extends A ? 1 : 0) extends <T>() => T extends B ? 1 : 0 ? true : false

type _IndexOf<T, U, Acc extends unknown[]> = T extends []
  ? -1
  : T extends [infer Head, ...infer Tail]
  ? IsEqual<Head, U> extends true
    ? Acc['length']
    : _IndexOf<Tail, U, [...Acc, Head]>
  : never

type IndexOf<T, U> = _IndexOf<T, U, []>
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBCsCM0GYIFoIEkB2ATApgDwHkAzSFZci0gIwE8IAFASwxwEMAHdgGxwgAoAAkxYduOAAwBOWJICUEAMQBbHFkYBXJYtYAnHaxqlSCkxACK6nAGcALowD2GI1DRKxKjDYg2AFrxs07LwAbjg6Vg4YEPZEEACCegYAdMy4hEQANBCp+MQAPAAqWQCqAHzerADW1hCsUQn6dEW1GHTFLVgQOjg26joYVt5+2dj40bG+vESM4V7tzPGJTUnOEAAGGzZWpAFBEABKNQC86KPpeQDasFkATFkIALq3pQDcEMDAEPhBAMY2qt57BAqLxYDtArxDlZYBATpg0vkLncAGz3DIADgyABYMtcAOxoyRPCAIV7vT7fHB-AE2IEgiA3cF7KE3WGnBFES7iLLciDiYk3MkfL54X7-Tq04G8ZBgqAbNarcoANUYOAA7tEogBxRg2AAS6ioAC4ID4bDZ2FYjR8tj8fEkAFZWJL2HQAc2AcEQYBAwDA-tAEAA+iHQ2HQxAAJr2PoQADC9lwED1YV44fTIYgvv9u14aCsAFEAI7qVhcPJxLIAIXKJz4hVKfHkR3KBRF-2wgziEAA-BAYSbxPJ8B2sIMG03Ya32zhOxAq73+xBB4ubDpLMuIEQy1YcDmIcH4blOc1ilk4j8fjO5+oMJUMPY1RgLg9axA2yPZ2OIC-SH2ZaQJofngo6DBczBEGEyZsFgWRJPBEFQQUrCMFwDx-ughYlmWeQpqwsEQGU17fmulikFAfYXj8FwAOQ8Bgbq+DR6FQFAJpBke5zIahJRZBc8FJFRWR4Vgr6ARALChDo+57Jx+Snm+HFnPJvE-mJAYgMGGbhu+1heHGrC7oM2k6dmjBuK6Xi5hAADeEDFqWXBZAWopUl4AC+W46PYWg0QIubIHaZb0W61jAOodhcFYNEybwPyGccP6kC5Yp5A5OFyZyVy3PcAqlFksClPlyWuX8aXYeWmWXHcECoiSWSYhAOL9lkBL1RARL3PlDJFRkJWpellXKVlvKjXlWQyr1-VueVjl5FVFy2DozBugVWQYJoII6FkNGsMx62bWE3WCsVUApTNg3zcNlxLSta0SYd20QLtNFZHUNDEu93VYlNZ2lTYs0Zddi1rndz17cSL3dYVp32f9gNDRylzvQVxKFQVU3of6YCBiZYYQAAYn0kw6BAADK-yWlpeNBlmfqgKQ5Rkz4ui8DQMak1Y9hcBFkRWqa5qWtawC2vaTouu6nrwAgwB1FYaphIzEAquqEBczzdiOPzZoWlaNpWHajrOq6HpejL6u81rSsALKurwcYs1wIXWCaOtC-rhviybPp+mAQA)

**Comment by YigaoFan** [comment]
Hello Marco,

I am new to typescript challenge. Could you explain why use template function type to check equal, not use extends operator directly?

**Comment by Oxygen66** [comment]
Ping @santosmarco-caribou  👍
