### ISSUE TITLE
300 - String to Number

### ISSUE THREAD

**Issue by santosmarco-caribou** [type-challenges/type-challenges#18836]
```ts
type ToNumber<S extends string> = S extends `${infer N extends number}` ? N : never
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBDMAMsQLQQMoBcBOBLAdgcwjQHsIA5AVwFsAjAUw0iUWZceoE8IAFLAgMQCG+CAAoAAnkQAHADZDaASggBiABYCMAExVpalWQN2IZWXRgEzGjZTYgBFcrQDOaLERxWoAYXcA3emgQAhAu2MImZhaEJME4VHQYADQQAO6qWADGqhB06v5OECYA1rQQAAYUNPQAdFIaTrQAkjhoZdWeEAB8EABqWLQpEO4QAOKmABLk1ABcEKpoaFJO08DAaE5Z1QBWTtVEGHjAcLBgIMBgF6AQAPq3d-d3EACaROQYED6apeP0pQ--twgZwuaHYUlKABUiJUEgAeFAQWgAD10OE0BVCuDw3QAvKhESjaGiCmUACQAb1wADN6GQCaj0RA4lUMABfMoQAD8dNmOFo-gYlxANwBDwgEOcgS8AgaBVFYuBWH0+0CoPBEHJEAAogBHcgWZJapHgjKBVkQKkYIiUCAAcjEatoiCyFhkRLwzmA5FcMictpBYNKGRlzggeIA2owjSa0LDdfqZLCoTD6LDbbBbZ1krBOlmo8baKa43qLEnofFU7aAKyZ5JV3OJfMx4sJsspjBpgCMACZaxAew2m4XY-HS8mKx3bd2AOx9meDqDR4ctsfllldgAcYmn11JAFI+3yBYOALoXIUi+WAvhvNCqWnoWhLS9XoHnUCMboodQYUrsV7vE4RAyN6bg4MscwLEsKxrBsqjbLs+yHMcwBCE4KT0J+vT9IMQEga47gQfMizLKs6ybDsewHEc8DAHhoGEVhACy+ylF46gyG6+DOLMxHQWRcEIVReCnOcYBAA)

**Comment by lvjiaxuan** [comment]
Crazy. I had too much over think.

**Comment by xzxldl55** [comment]
This will lose the concrete type

`ToNumber<'1'>; // number`

I think the expected answer would be: `ToNumber<'1'>; // 1`

**Comment by yankeeinlondon** [comment]
> This will lose the concrete type
> 
> `ToNumber<'1'>; // number`
> 
> I think the expected answer would be: `ToNumber<'1'>; // 1`

It was a typo, the narrow type literal is preserved.
