### ISSUE TITLE
SnakeCase

### ISSUE THREAD

**Issue by gvergnaud** [type-challenges/type-challenges#19458]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: SnakeCase
tags: template-literal,string
```

## Question

Create a `SnakeCase<T>` generic that turns a string formatted in **camelCase** into a string formatted in **snake_case**.

A few examples:

```ts
type res1 = SnakeCase<"hello">; // => "hello"
type res2 = SnakeCase<"userName">; // => "user_name"
type res3 = SnakeCase<"getElementById">; // => "get_element_by_id"
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type SnakeCase<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<SnakeCase<"hello">, "hello">>,
  Expect<Equal<SnakeCase<"userName">, "user_name">>,
  Expect<Equal<SnakeCase<"getElementById">, "get_element_by_id">>,
  Expect<Equal<SnakeCase<"getElementById" | "getElementByClassNames">, "get_element_by_id" | "get_element_by_class_names">>,
]
```

**Comment by gvergnaud** [comment]
Possible solution: [Playground](https://www.typescriptlang.org/play?#code/PQKgUABBCMCcAsBWAHBAtBAygOwIYGsBTAYVwGdDJ00baqAjATwgHFd6AnAS0IBsIAaoQ4BzPAFcAJhAAUAAREA3YWNxSAlBADEhAB4AXDoQC2hbfpMAHXrgtpeXCx1z8tZQ12wiqVLX4gAiuKE7lwA9tg+UMRGtma4EAAGOAQk5IQAPAAqAHyJECKE2MJcAMYQ+gAWthXiHNhkEAnu3F4QAGZhHMa2FtKeECAgpbimvKQUQxVhTRAtniIdXT36fRADQ2R4RAD6I5MgAHRREACCHYQA7hB6o9YhAFwniS-6ZFT6jJZmRmTQEABeLDbNIUDIAIkqfF4YXBOQA3BBgMBATkIJDobCPl8fiEAEyA4GpCaZcHiCgcAByo0IcMRyNR6PJwh2eFM4Ox3wgvwAzISUkQSRDCvoAKK8ExFfQAIUYAElJHSkSiAWjwSKdnxJdh9DsmDsuIqqC9Eic0QIeNcIqxHAAJcT0B4QSqrSxkB7It6lSqHABWZEOXREwDgSGQYBAwDA0dAEB28YTiYTEAAmmE6hBiGFJGZbcIzEnC-HBlHo1AwJ8uQLQZkWmigQAZMKXYT7TIAKTCngymGsjgyLQANBAAKqWb4cNsNwirYQ5YfgnZwhHRytmMcTqczpz8vv6CGnaXEAAiooAYixbXL2wBpBsAWUpAHkAAoBABKmCyI4EAHUABopgAWuCC5wgA2tg4jGPQwgALrwquOJYHuGRUEO6GEJYuDOPoXQ3AYRSSI08xeIOVClHURg6sQlTiNg+AERY2DEXMHhtEC4KgRRdEMY0ejMaxuDYIw4FwYSYlgPW6GGExRGNIkAAkADenjtMIHRcBw7hySxJHsSIAC+KlqRpvz6IZppQFAAD8EDgRQ2G4V04kCfJ9lcXBVDWRAdm9g4+7eT51nmeRwXBY5OG2F0YXhdZ7Rae4sVxRAlEcNR+i0fRjFuXp6Lgr5qW8fgjROuBhwVd62VkMOaUZVlDFeSlORBVAToJdp+i6axkXORwrWFf5-ahXMWFRXhHDDh1SX2RVhxVXxtVUVKDX4HBLXhU6Q37iNvXRZNSQqXVK3FcZynTRZiS1cVZAbdZZVzQtJVLelJ3ZQhSFcp23ZUA4SWYU5+3dfprQiLF6b6JY4hdblPUGYSXFSYSf0w4ReXgaZHCaZ1wNsaDw5zZj3IhPoTWFd92BoeFoUDXtE3JdZSnKRDUMWSpLPQ7jXGFdzTp010Z0XZZQV3U6HP6IhMYgHGRZJhAWQk5m6SNLLcuRmAXDGJYXRdWuEDKRAooAI7iC4w6iro3ylF1hkdBwYTGBAADkchrmg3ouBKXghMA0NcLwZBO59Zhto0QLgVQFtW-uxum7wPYgkKGK8DCcILlCKewjk86R5bhDWxkscuAnxLpBCzJUjSadMhSrJV9nsVR-nMcm8X1ZJyK4rajK8qKvO6Ialqpg6nqjAGn3OdQE3BdF-H7dl+qM5d8PPcKgVAA+A9LxKK+ysQNhkGQ1KmGQ1eL7qQ9SqP48b1vF871f+qlAfZB1yfy5eVLMuq8WZ51FUGlMAWDdN-H+JYwCgCoGiTA1QjAQEYOmLGZAwi8D9hEd0zpXTuk9GQb0foAxBhDAgFAwBhJkBbP1KA5pLRzBQWghoToXSQ2wcAL0Pp-SBlEEQsMwBkGoP0OEBoUCID3i6GYWinsiiFAwUwt0HpWG4PYQQ0QEZSxAA)

**Comment by L2jLiga** [comment]
Possible solution: [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAogRwK4CGANgDTYAeqAxvAL5wBmUEIcA5AAJKoC0VAFsSIoAdgHMUAZwD0eGMCKS2AKGXc0AZREEA1igDCBSSgA8AFQB8cALxwzcFORiiAJpLgADACTpgIhihQcABiwFCSMLQ+fgFBAEpSkR7KcKkA-CFhEQ5Oru4AqmCoUFRGpqHhMBYpqemeAPo+ADIQAO6BpcYmFREWUehaugZlJgm9tMm1qQBcnj49kT6DeoZdY1UTNXCzbGwA3KrqcJ1SNnAA2jVYlCg0JriERCbLw10ARPwoREQQbxZkHy+Pz+-yuNzuD2Iz20KxGbzwxigADkCCAUH8AQjAvVtGiQSQwdQYPd8FCXqtTG8JDAsMI0SIYAAhRAASRcGLgVJQMHqXxQ9J5ACNEPVgOyLKDUtciSTHtChhSTFyaXTREzWey4AAfTnU2n8tXM-REIySFFoyQc5W81UM+rC0WanXWvkC+0iqgmySSHGoqT45QAXSAA)
