### ISSUE TITLE
189 - Awaited | using a custom PromiseLike with recursion

### ISSUE THREAD

**Issue by kennysliding** [type-challenges/type-challenges#19864]
```ts
interface MyPromiseLike<T> { then: (onfulfilled: (arg: T) => any) => any }

type MyAwaited<T extends MyPromiseLike<any>> = 
  T extends MyPromiseLike<infer R> ?
    R extends MyPromiseLike<any> ?
      MyAwaited<R> :
      R
  : T;

```

A custom `MyPromiseLike` to mimic `PromiseLike` interface provided in Typescript 3.7.7 found [here](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.promiselike.html)

It is then used to determine whether a type passed in is a promise, and true even if it is an object with keys similar to a promise, in `MyAwaited`

**Comment by Stan-Stani** [comment]
I think I unintentionally did something similar: 

```ts
type MyAwaited<T> = T extends Promise<infer U> ? MyAwaited<U> : T extends { then(arg0: (arg0: infer V) => any): any } ? MyAwaited<V> : T
```

I guess I have a bit of needless redundancy in mine.
