### ISSUE TITLE
898 - Includes | with recursion, and a note for undefined type when accessing the types array

### ISSUE THREAD

**Issue by kennysliding** [type-challenges/type-challenges#19872]
```ts
type Includes<T extends readonly any[], U> =
  T extends [infer P, ...infer R] ? 
    Equal<U, P> extends true ? true : Includes<R, U>
    : false
```

we first parse `T` and check if it satisfies the type `[infer P, ...infer R]`, thus getting the first element, if this cannot be parsed, i.e. no element in the array, return false

the parsed `P` will be later used to compare against `U`, and return true if there is a match, if there is not, recursively call `Includes` to check the remaining types

an interesting note is that the following code does not work for every case

```ts
type Includes<T extends readonly any[], U> =
  Equal<U, T[0]> extends true ? true 
    : T extends [any, ...infer R] ? Includes<R, U> : false;
```

although they look similar, with the difference being the order reversed, i.e. check if `U` matches the first type of `T` first, then recursively call `Includes`, it cannot work for the following case

```ts
Expect<Equal<Includes<[null], undefined>, false>>, // will not work
Expect<Equal<Includes<[undefined], null>, false>>, // work
```

this is because when the array is empty, when we access by `T[0]`, we will actually get back `undefined`, which matches the first case, instead of return false

**Comment by Drincann** [comment]
with a small modification:
```ts
type Includes<T extends readonly any[], U> =
  T['length'] extends 0 ? false 
    : Equal<U, T[0]> extends true ? true 
      : T extends [any, ...infer R] ? Includes<R, U> : false;
```
