### ISSUE TITLE
43 - Exclude | using distributive nature

### ISSUE THREAD

**Issue by kennysliding** [type-challenges/type-challenges#19943]
```ts
type MyExclude<T, U> = T extends U ? never : T;
```

by extending each type `T` over each type of `U`, we check whether each type can be assigned to `U`, and exclude the type if so since we want to exclude the types in `U`, and include otherwise

this is a more advanced question requiring an understanding of ts

docs can be found [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types)

**Comment by erhant** [comment]
Woah glad I tried this challenge, didn't know about this!
