### ISSUE TITLE
191 - Append Argument

### ISSUE THREAD

**Issue by g-plane** [type-challenges/type-challenges#203]
```ts
type AppendArgument<Fn extends (...args: any[]) => any, A> = (arg: A, ...args: Parameters<Fn>) => ReturnType<Fn>
```

**Comment by JounQin** [comment]
This is incorrect, `append` is not `prepend`.

**Comment by antfu** [comment]
The description of this challenge was wrong at that time and fixed later on. This answer is out-of-date. Closing for now.
