### ISSUE TITLE
9286 - FirstUniqueCharIndex

### ISSUE THREAD

**Issue by santosmarco** [type-challenges/type-challenges#20488]
```ts
type FirstUniqueCharIndex<
  T extends string,
  _Acc extends string[] = []
> = T extends ''
  ? -1
  : T extends `${infer Head}${infer Rest}`
  ? Head extends _Acc[number]
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : Rest extends `${string}${Head}${string}`
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : _Acc['length']
  : never
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBCcBMAcA2CBaCAxAlgJwM4BcBVAO0wEcBXAUwGEALAQ2wEliATKgD0lRT-54AjAJ4QAVpgbEA5rkbEIACgACEqbPkBbKvgYBKCAGJtbTBU1GC2TDJ49DDiAEVqBTAHtidqAHFMANyoFBggrG2lQgBoIADMbNgh8OipYnAIIYk8UbCoAByoGfHCIAGNGbAYS-CpsCBs6-AgpBJz8CmwFTHxcOvYuADoIZhiGiDZ3Kh7Mxq5MAmjW9oUUAEZBxVZcXJwqBJEIAG0AGyodEvcOCABmeAB2AF1FOnx8XNwALmBgE7OLqn7zppgLlsO5BCdNLhgHE8PgUBRSJQqCgykxKtVsCgbCgGCgwjJgHo9N4IAA+CAANUwVAA7hBPBA-PgABIUQTvCDPV4fL7dMr9MS4frubDSYBwJBgEDAMCy0AQAD6SuVKuVEAAmu52hAaH8IMyailVcalRBpbL8MJ8hg0kREdR6ExWBxOAAeHgAFQgXGq7B6+OkkR4CoAgiUSt7OL62P78NYZAd7hAALyHe5gcmpr0+oIxiAAcnzPAA-KgVjwOdmo7megADAAkAG8bDEavqCmwAL5NlttgBKk3wndrJfbDASOb9irDJQOxHMghq6agUFLWFhJHIDvKzq4roH80O-WPofD0QN4-upJ4UA5B5m1anDcbAe7jYvXabr5HK4ga9tm5Io6LB9G697RAcx79KeJTnh2V43hAHIwQc+YnDIST5suSEZFQgTYLKYDyiaxoQB6g46gwuCTIqJEqmaMqYJouQio0lrWo2EAAKKUAwRzRFxnD5FUECdrEoIWPmyjsciqJHOh0iTMAFBFEcuBFmAMmlFRNGpgcPCCcJ+CujxFB8a664EIB25OqBrpoac+DnBw+aktEAAMpJuQZQlUFUJm8UcFkAfatA7nZaHuIEPxOX8rnRLAXlBlAhl+cZpnmZZdpbmFtkuvZDAMIIgjxWWSU+UZAVmUFWXWblIH5YWblld56aEcRdFqug7RJG2ADK1RvLRnUKgxRHgFA5J9eUKTCFqtS4O4RwqR4xAfJyLxvJ8wB8nQApCiKYoSogwBSLgNI1Dw5JUrSoRLStnjrVyW28rg-KCsKoriggJ2LctRSPVdEAALIiikjryUEilPZtPI7W9e0fYdUoymAQA)

**Comment by Qzhor** [comment]
cool，稍微简化一下
`type FirstUniqueCharIndex<
  T extends string,
  _Acc extends string[] = []
> = T extends `${infer Head}${infer Rest}`
  ? Head extends _Acc[number]
    ? FirstUniqueCharIndex<Rest, _Acc>
    : Rest extends `${string}${Head}${string}`
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : _Acc['length']
  : -1
`

**Comment by Qzhor** [comment]
cool，稍微简化一下
`
type FirstUniqueCharIndex<
  T extends string,
  _Acc extends string[] = []
> = T extends `${infer Head}${infer Rest}`
  ? Head extends _Acc[number]
    ? FirstUniqueCharIndex<Rest, _Acc>
    : Rest extends `${string}${Head}${string}`
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : _Acc['length']
  : -1
`

**Comment by Qzhor** [comment]
`type FirstUniqueCharIndex<
  T extends string,
  _Acc extends string[] = []
> = T extends `${infer Head}${infer Rest}`
  ? Head extends _Acc[number]
    ? FirstUniqueCharIndex<Rest, _Acc>
    : Rest extends `${string}${Head}${string}`
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : _Acc['length']
  : -1
`

**Comment by Qzhor** [comment]
cool，稍微简化下
```typescript
type FirstUniqueCharIndex<T extends string, _Acc extends string[] = []> = T extends `${infer Head}${infer Rest}`
  ? Head extends _Acc[number]
    ? FirstUniqueCharIndex<Rest, _Acc>
    : Rest extends `${string}${Head}${string}`
    ? FirstUniqueCharIndex<Rest, [..._Acc, Head]>
    : _Acc['length']
  : -1;
```

**Comment by shx123qwe** [comment]
nice code,geinus!
