### ISSUE TITLE
Drop the specified chars in the string.

### ISSUE THREAD

**Issue by CaptainOfPhB** [type-challenges/type-challenges#2059]
## Info

```yaml
difficulty: hard
title: Drop String
tags: template-literal, infer
```

## Question

Drop the specified chars in a string.

For example:

```ts
type Butterfly = DropString<' b u t t e r f l y ! ', ' '> // 'butterfly!'
```

## Template

```ts
type DropString<S, R> = any;
```

## Test Cases

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<DropString<'butter fly!', ''>, 'butter fly!'>>,
  Expect<Equal<DropString<'butter fly!', ' '>, 'butterfly!'>>,
  Expect<Equal<DropString<'butter fly!', 'but'>, 'er fly!'>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', 'but'>, '     e r f l y ! '>>,
  Expect<Equal<DropString<'    butter fly!        ', ' '>, 'butterfly!'>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', ' '>, 'butterfly!'>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', 'but'>, '     e r f l y ! '>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', 'tub'>, '     e r f l y ! '>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', 'b'>, '  u t t e r f l y ! '>>,
  Expect<Equal<DropString<' b u t t e r f l y ! ', 't'>, ' b u   e r f l y ! '>>,
]
```

**Comment by antfu** [comment]
Think we could simply have a generic type like `DropString<' b u t t e r f l y ! ', 'b'>`

**Comment by CaptainOfPhB** [comment]
@antfu I accept your suggestion and modified the demo. Can you review it again? `DropString` is inspired by [`TrimLeft`](https://github.com/type-challenges/type-challenges/blob/master/questions/106-medium-trimleft/README.md) and [`Trim`](https://github.com/type-challenges/type-challenges/blob/master/questions/108-medium-trim/README.md).

**Comment by antfu** [comment]
Do the second arg accept multiple chars? e.g. `DropString<' b u t t e r f l y ! ', 'but'>`

**Comment by CaptainOfPhB** [comment]
Yes, I spent an hour to match your case 😭，you can view demo [here](https://www.typescriptlang.org/play?ssl=14&ssc=14&pln=14&pc=15#code/C4TwDgpgBAIgTgezAZWHAlgOwOYB5kA0UASlBAB7ASYAmAzlHWltkcQExmXX2PM5QAvFADkIgHxCSXKrQYADACQBvLADMIcKADF0cJgGEAFgEM4AXxXrNUE5hDAjLc-IBQUKAH4oyGTwVWmBpayACMlsq6+sDGZhHWIewu7h5esIgo-HhKymERyEnyRFGGpnBEAOIQwMgArgBGTHAAgmpUcLjExXqlZuLiKR4AXOlIqBg4+GzsA8M+ANyurqCQUFU1DU2t7VM+m2h+cnwT2JLCvhSyvDl1jWjxQTbbmi5pz1ojyItLAPQAVFAAPrAkGgkFQAAqECYUAMJjo0KBYORgKgfx+S3QAFswAg4MAoMooABRACOtRMABsiMTyJAAMYE8xQNSILGiAACKwgAFp6aZKZTqNhoT9asB0JS6CJvtyoPT4YjhABtFK0hnAXBkimU3DwMZZXAieri9osykgACEIiIIlE4ltJuA7TUFut-QIarpEEZWvJVL1GXGLCNTrNrqtNtEToktpsEfdDq9Gr9OsDBpORtSUDD8bd2ezUbtsejps0CYkSY86p9mu1Af1mUzdvqUFqUAJBOgWjUUEpUBAUEtolt9sdZbgFY9ydrqYbQcNLbbHZX3ZZfYHQ5H0ZLduXnbIUB7G8Hw8rnur3t99d1jeDkyX7YPa97-dP25EwF3OeXHhfJ63c9XAAXVcIA).

**Comment by antfu** [comment]
Then I think it would be better for we can add those test cases

**Comment by CaptainOfPhB** [comment]
@antfu Done, demo updated(here is [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIgTgezAZWHAlgOwOYB5kA0UASlBAB7ASYAmAzlHWltkcQExmXX2PM5QAvFADiEYMgCuAIyZwAggDMqcXMSJjgAMXRwmAYQAWAQ1XEAfJaEkuVWgwAGAEgDeWRRDhQde4EdMAvq7unlDGmCDAhiwBDgBQUFAA-FDItjyOwZgeXsgAjEEuPgYmcIUhueyxCYnJsIgo-HjOLvmFyFUORMV+pWzs5jWJAFz1SKgYOPj9gyOpANxxcaCQouI9-qrI5tZpFHa8LRXe5dmh4ZHROLF1WlCjyIsr0JpSsmhKKtOpMnLp9nxJtgdsI9twAS03nJTjkoJ9PDcUvCvA9FnEAPQAKigAH08fiCfioAAVCBMKD6Yx0Mm4wl0nFQTHopboAC2YAQcGAUBcUAAogBHSTGAA2RD55EgAGNuQEoIpEKyoAByAACzwAtFKTCKRdRsGT0ZJgOgRXRlWjnlApVSacIANo1CXS4C4QXCkW4eDjJq4ZXSY0qeUikAAQmVRGVKvMkYDwBUihD4csBCdkogMrdQtFXoaExYfrjQcTYYjKrjypjKtCJeTMbTLqzHtzPqBfqg0igkig3O50C8iigIqgICgoZVseNlcjtUS-flQ5HY+j9cSzozrvdOe9jTbUdqRZrSdns7LUen5cDnlrldX-PTma3np3+amUc73d7ZCgA8Xo-HZ7RpO8bXkmt6pmuD6btmz55r675dj2SHzoOw7-hOl7ABe+61Chf7LuBDYbk225wXuHaIV+eFoQRkbADI2EntRS4ASmRGPjBLa7gWCGfshP4LjRAGxoxlH8b+QkrhB96Nk+XGvngvFIX2AmoSxGHKlhVZKXOqn4ax9YALpxEAA)).

**Comment by antfu** [comment]
Great, thanks. I have changed it to `hard`. If you want, I think maybe we could have another question as your previous one for only dropping one char and call it `DropChar<>`?

**Comment by CaptainOfPhB** [comment]
@antfu Agree with you.
