### ISSUE TITLE
9 - Deep Readonly

### ISSUE THREAD

**Issue by StephanieTM** [type-challenges/type-challenges#2082]
```ts
// your answers
type DeepReadonly<T> = {
  readonly [P in keyof T]: keyof T[P] extends undefined ? T[P] : DeepReadonly<T[P]>;
}
```

The key point here is to check whether a property is an object so that we can decide when to stop recursion.

My solution is to use `keyof T[P] extends undefined`, considering the `function` situation.

**Comment by nikolausliu** [comment]
为什么`keyof T[P] extends undefined` 可以决定某个属性是否是一个对象？下面的代码不管是string类型还是对象类型，计算得到的属性都是false

```ts
type a = keyof string extends undefined ? true : false // false
type b = keyof {a: 1} extends undefined ? true : false // false
```
