### ISSUE TITLE
FindAll

### ISSUE THREAD

**Issue by tunamagur0** [type-challenges/type-challenges#21104]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: FindAll
tags: template-literal, string
```

## Question

Given a pattern string P and a text string T, implement the type `FindAll<T, P>` that returns an Array that contains all indices (0-indexed) from T where P matches.

## Template

```ts
type FindAll<T extends string, P extends string> = any;
```

## Test Cases

```ts
import type { Equal, Expect } from '@type-challenges/utils';

type cases = [
  Expect<Equal<FindAll<'Collection of TypeScript type challenges', 'Type'>, [14]>>,
  Expect<Equal<FindAll<'Collection of TypeScript type challenges', 'pe'>, [16, 27]>>,
  Expect<Equal<FindAll<'Collection of TypeScript type challenges', ''>, []>>,
  Expect<Equal<FindAll<'', 'Type'>, []>>,
  Expect<Equal<FindAll<'', ''>, []>>,
  Expect<Equal<FindAll<'AAAA', 'A'>, [0, 1, 2, 3]>>,
  Expect<Equal<FindAll<'AAAA', 'AA'>, [0, 1, 2]>>
];
```

**Comment by tunamagur0** [comment]
Playground with solution: [Playground](https://www.typescriptlang.org/play?#code/PQKgUABBBMCMsAYAsEC0EBiBLAdgEwEEAbIyNVCysgIwE8IcBXEiACgAEAXRnAQwFteAc0YAnBAEoIAYn4BTPFkb8ZnOfwAORXmtREsa0byIyAzp1G4hZMtLsQAioznmsAexw2oAcSwA3ORwIXggNHUMg80scIQgABWD8YIg1AA9OCCirCAAVABoILE0idUCMzgALORTaDWqAA2x8YiIAHnz4gD56lIqdCFE5blEcU0SIAlEjekr+gGMPTl5cMeMTXEU5lzYEVA25VIUpADNRNxUciAB3KsH4iEFOOarTADovCE6IADUsOSuIB4IL5OAAJRjUABcEAqnE4GlMkOAwE4pmerwAVm83KIhMA4IgkGAQMAwGTQBAAPrUmm0mkQACabjEEAAwm48NVQXI7nS+dSICSyZxatUAHLKag8nJuSbTVpkS4HNT4MZMfhS0R5MgAJW2ysCeDGPAA1jg3FccABtAC6EAAvBBbWAvo69aYrQByEoxSqeu0G1W5CAAfgg7og0IlGulsqmvFo7QKVteqfdBVN5stNs6AG5haL4kRGKYAPI4OQKqBK9KGtWSnnaqARwNGiCZi3Wu2O6OamVyhPtTouh3h-W1oNW3DHHlUgqp17T2c6m1kMM6r0+oR+gMTts5MhQdcuTeBbcVf2HyNFkvlysdFNplwZnBmzs5sjQuLFssVpNOhd03bV8sxwHN8zAEU6ipJpCBIKtg1bMYshiJt7iQzILCsNCAEkIAw9VNVHBA0JbPd6xjURbVHZ1XXQ8iIE9T01ydVcoGhGsVTbeoABIAG8l1EKkAF9+ME8NhPqFjOLrCBeL4uJRIEnAZyEylJKvMNKVglpWh1Ao4gMn871aHDOmTQDnwgHCPygdiYI2XT9PiIzbz-MyCndYd7PdCCoOqHT4JkoMUKEAz8IY0K6O0xygoMvMyTACl+T5XIXAyVleFMbYUrpQVSSKDQcXKQs+IgABRABHRhjAKcrUjqOYMmEiBTnORiuFFVBnjWM8XGARhOCwIhTE9PzCzmLLtkdK0yHqxrOFaKqaraQK2k9dkSDkJr3CCNxjlyUUAGU5ksDQSugnqtpiFxPQKT0clFT1zKdWAkBzcy5oa7bFuW4xWjW1oNrcLadqBfbDrqE6zou6orq3W77rqZ7k1gAA2ApoAAdg+tD5p+pbqv+wHgdBobwYOx6odOrBzpqS6+muoREcYlHWM6T6oHxprCZWgHYvWu7GKpuQ2dtDm8e+nm-tWgWgaFpiXvF4cbQgpKQCpXL6QwMRKlnI61ARTWtcpfL1bIL4jr6O5aGZITTBBwbdsRGE4QRJEUTRCpMWxXF8XgZBgF4UYrh5C2fj+AEHeLcnRmhWF4URZFUXRLFXhxPECUD6OnY8Uxw4AWRxapWUZhGXYT93k69n309xYlSTAIA)

**Comment by jiangshanmeta** [comment]
```typescript
type NormalFindAll<
  T extends string, 
  S extends string,
  P extends any[] = [], 
  R extends number[] = []
> = 
T extends `${string}${infer L}`?
  T extends `${S}${string}`?
    NormalFindAll<L,S,[...P,0],[...R,P['length']]>
    :NormalFindAll<L,S,[...P,0],R>
  :R

type FindAll<
  T extends string, 
  S extends string,
> = 
  T extends ''?
    []
    :
    S extends ''?
      []:NormalFindAll<T,S>
```
