### ISSUE TITLE
898 - Includes

### ISSUE THREAD

**Issue by Plasticine-Yang** [type-challenges/type-challenges#22111]
```ts
type Includes<T extends readonly any[], U> = T extends [infer First, ...infer Rest]
  ? MyEqual<First, U> extends true
    ? true
    : Includes<Rest, U>
  : false

type MyEqual<X, Y> = (() => X) extends (() => Y)
  ? (() => Y) extends (() => X)
    ? true
    : false
  : false
```

**Comment by adoin** [comment]
![image](https://user-images.githubusercontent.com/20517172/213080025-58634061-d2f9-4596-ae51-476f42907895.png)

**Comment by adoin** [comment]
Expect<Equal<Includes<[{ a: 'A' }], { readonly a: 'A' }>, false>>,
  Expect<Equal<Includes<[{ readonly a: 'A' }], { a: 'A' }>, false>>,
这两行错了

**Comment by Plasticine-Yang** [comment]
@adoin 

> Expect<Equal<Includes<[{ a: 'A' }], { readonly a: 'A' }>, false>>, Expect<Equal<Includes<[{ readonly a: 'A' }], { a: 'A' }>, false>>, 这两行错了

已更正，是 `MyEqual` 的实现有点问题

```TypeScript
type MyEqual<X, Y> = (<T>() => T extends X ? 1 : 2) extends (<T>() => T extends Y ? 1 : 2)
  ? true
  : false
```

**Comment by Tommy0604** [comment]
> @Plasticine-Yang 我也是抄的这个判断方法，但是我没懂为啥他解决了其他判断方法没解决的各种问题。。。
`Equal`实现思路可以看下这个 https://github.com/microsoft/TypeScript/issues/27024#issuecomment-510924206
