### ISSUE TITLE
IfAny

### ISSUE THREAD

**Issue by pashutk** [type-challenges/type-challenges#223]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: IsAny
```

## Question

Sometimes it's useful to detect if you have a value with `any` type. This is especially helpful while working with third-party Typescript modules, which can export `any` values in the module API. It's also good to know about `any` when you're suppressing implicitAny checks.

So, let's write a utility type `IsAny<T>`, which takes input type `T`. If `T` is `any`, return `true`, otherwise, return `false`.

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type IsAny<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<IsAny<any>, true>>,
  
  Expect<Equal<IsAny<undefined>, false>>,
  Expect<Equal<IsAny<unknown>, false>>,
  Expect<Equal<IsAny<never>, false>>,
  Expect<Equal<IsAny<string>, false>>,
]
```

**Comment by antfu** [comment]
Hi, thanks a lot for the new challenge!

However, I feel the name a bit confusing. `IfAny` sounds more like "If there is any of xxxx" instead of "If it is `any`". Also, do you think it is better to be something like `If<IsAny<a>, true, false>`? I would think `If<C, T, F> and `IsAny<T>` are both valid and can be sperate into two challenges. Which might be more flexible as "utils".

What do you think?

**Comment by antfu** [comment]
<details>
<summary>Spoiler</summary>

`IsAny` is actually also exported by `@type-challenges/utils` 😉. But I think it's worth letting people trying to implement it on their own.

</details>

**Comment by pashutk** [comment]
Hi @antfu!

Yep, the name can be misunderstood. If you're planning to add more `IsXxxx`-like exercises, then renaming totally makes sense. In any case, I like `IsAny` as much as `IfAny`.
About spoiler – yes, but this helper is a bit mind bending on it's own, so I think people could try to figure out how it works and have fun.

**Comment by antfu** [comment]
Nice! I also think `If` is a great idea, would you like to create a challenge for that as well? Thanks!

**Comment by antfu** [comment]
@pashutk or if you don't mind, I can do that for you (credit will be yours of course) 😉

**Comment by pashutk** [comment]
@antfu I've updated the proposal so now it's `IsAny`. Should I create `If` in a separate issue?

**Comment by antfu** [comment]
Great! And yes, please. Thanks
