### ISSUE TITLE
How does Equal type works?

### ISSUE THREAD

**Issue by zxch3n** [type-challenges/type-challenges#225]
In the utils, `Equal` is written as follow. 

https://github.com/type-challenges/type-challenges/blob/49b53ccaad1dc296c5c4d20102890fb625d8d345/utils/index.d.ts#L8-L10

I can't really understand how it works.

And what is the difference between it and the following implementation?

```
type Equal<X, Y> = (X extends Y ? (Y extends X ? true : false) : false)
```

**Comment by antfu** [comment]
Maybe you can follow this thread for some information

https://github.com/microsoft/TypeScript/issues/27024#issuecomment-421529650

**Comment by zxch3n** [comment]
Thanks!

**Comment by zhangzhuang15** [comment]
> Maybe you can follow this thread for some information
> 
> [microsoft/TypeScript#27024 (comment)](https://github.com/microsoft/TypeScript/issues/27024#issuecomment-421529650)

Pretty good! By the way,  are you inspired by this thread and give this implementation of `Equal`?
