### ISSUE TITLE
MinusOne

### ISSUE THREAD

**Issue by fayzzzm** [type-challenges/type-challenges#2257]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium 
title: MinusOne
tags: math
```

## Question

Given a number (always positive) as a type. Your type should return the number decreased by one.

For example:

```ts
type Zero = MinusOne<1> // 0
type FiftyFour = MinusOne<55> // 54
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave it to implementation `any`.

```ts
type MinusOne<T extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<MinusOne<1>, 0>>,
  Expect<Equal<MinusOne<55>, 54>>,
  Expect<Equal<MinusOne<3>, 2>>,
  Expect<Equal<MinusOne<100>, 99>>,
  Expect<Equal<MinusOne<1101>, 1100>>,
]
```

**Comment by somebody1234** [comment]
is this possible? while this is trivial for strings, i believe for numbers it would require some very complicated and very cursed typescript acrobatics, making it rated extreme at the very least

**Comment by antfu** [comment]
Yes, it's possible

<details>
<summary>Spoiler</summary>

Construct an array with the given number as its length, pop up one element and get the new length.

</details>

**Comment by somebody1234** [comment]
<details>
<summary>ok, yes but</summary>
i managed to do it, however given that the last case is ~1101, it requires a trampoline which i don't believe is common knowledge

i'd argue that even the array length workaround is obscure enough to merit moving it to extreme rating
</details>

**Comment by fayzzzm** [comment]
> ok, yes but
> i managed to do it, however given that the last case is ~1101, it requires a trampoline which i don't believe is common knowledge
> i'd argue that even the array length workaround is obscure enough to merit moving it to extreme rating

The first thing i could mention about this problem is - it was named MinusOne I (it means easy version). It has a restriction that needs to be mentioned on the description of the problem. The limit of the number is the `n < 50` and `n` is positive.
