### ISSUE TITLE
Translation for pt-br

### ISSUE THREAD

**Issue by k8adev** [type-challenges/type-challenges#23084]
I found this repository after asking in my Twitter about Typescript to JS specialist and for Brazilians, there are a so few sources of knowledge about typescript in pt-br. Can I start (or contribute if already have) with translation for pt-br?

**Comment by kabrunko-dev** [comment]
@k8adev, você teve algum tipo de resposta (fora desta _issue_)? Queria também ajudar a contribuir.

Por que recentemente encontrei este repositório e, nossa, vai ajudar um pessoal legal a treinar o TypeScript.

**Comment by k8adev** [comment]
> @k8adev, você teve algum tipo de resposta (fora desta _issue_)? Queria também ajudar a contribuir.
> 
> Por que recentemente encontrei este repositório e, nossa, vai ajudar um pessoal legal a treinar o TypeScript.

1 ano e ninguém respondeu 👻  Eu criei um fork do projeto aqui para retomar essa ideia, está a fim de contribuir? Seria super bacana e ajudaria demais nossa galera.

**Comment by kabrunko-dev** [comment]
Pode 

> > @k8adev, você teve algum tipo de resposta (fora desta _issue_)? Queria também ajudar a contribuir.
> > Por que recentemente encontrei este repositório e, nossa, vai ajudar um pessoal legal a treinar o TypeScript.
> 
> 1 ano e ninguém respondeu 👻 Eu criei um fork do projeto aqui para retomar essa ideia, está a fim de contribuir? Seria super bacana e ajudaria demais nossa galera.

Pode me incluir, por favor

**Comment by k8adev** [comment]
@kabrunko-dev te mandei convite, vou já começar algumas traduções e conforme vamos mandando para a main, abrimos pr aqui para o repositório e vemos se a galera aceita 🤝

**Comment by k8adev** [comment]
Já comecei com o [README](https://github.com/k8adev/type-challenges/blob/main/README.pt-br.md) em português mas esqueci de abrir uma PR para vermos se é a melhor tradução 🥲

**Comment by kabrunko-dev** [comment]
> Já comecei com o [README](https://github.com/k8adev/type-challenges/blob/main/README.pt-br.md) em português mas esqueci de abrir uma PR para vermos se é a melhor tradução 🥲

Hahahaha tudo bem. Qualquer coisa a gente vai sentindo e consertando conforme indo.

Vou tentar começar esta semana com a tradução de alguns desafios.

**Comment by Fabioh** [comment]
Opa, também tenho interesse em ajudar @k8adev e @kabrunko-dev.

Como faço para contribuir crio um fork do fork da @k8adev ?

**Comment by k8adev** [comment]
@Fabioh seja bem vindo então! Vou te adicionar no repositório e contribui direto lá, só abrir pr para a main

**Comment by k8adev** [comment]
Closed by #31698
