### ISSUE TITLE
14 - First of Array

### ISSUE THREAD

**Issue by se030** [type-challenges/type-challenges#23616]
```ts
type First<T extends any[]> = T extends [] ? never : T[0]
```

### References

https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types

**Comment by se030** [comment]
```ts
type First<T extends any[]> = T extends { length: 0 } ? never : T[0]
type First<T extends any[]> = T[0] extends T[number] ? T[0] : never

type First<T extends any[]> = T extends [infer First, ...infer Rest] ? First : never
```
- [조건부 타입의 infer 키워드](https://velog.io/@from_numpy/TypeScript-infer#%EA%B8%B0%EB%B3%B8-%EA%B5%AC%EC%A1%B0)
  - Element<number> extends Element<infer U>와 같은 타입을 작성하면, U타입은 number타입으로 추론(infer)된다. 이후, 참인 경우에 대응되는 식에서 추론한 U타입을 사용

**Comment by javapyscript** [comment]
// type First<T extends any[]> = T extends { length: 0 } ? never : T[0]
 Brilliant!
