### ISSUE TITLE
Integers Comparator

### ISSUE THREAD

**Issue by g-plane** [type-challenges/type-challenges#274]
> Require TypeScript 4.1

## Info

Basic info of your challenge questions,

```yaml
difficulty: extreme
title: Integers Comparator
tsconfig:
  ts: next
```

## Question

Implement a type-level integers comparator. We've provided an enum for indicating the comparison result, like this:

- If `a` is greater than `b`, type should be `Comparison.Greater`.
- If `a` and `b` are equal, type should be `Comparison.Equal`.
- If `a` is lower than `b`, type should be `Comparison.Lower`.

**Note that `a` and `b` can be positive integers or negative integers or zero, even one is positive while another one is negative.**

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
enum Comparison {
  Greater,
  Equal,
  Lower,
}

type Comparator<A extends number, B extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Comparator<5, 5>, Comparison.Equal>>,
  Expect<Equal<Comparator<5, 6>, Comparison.Lower>>,
  Expect<Equal<Comparator<5, 8>, Comparison.Lower>>,
  Expect<Equal<Comparator<5, 0>, Comparison.Greater>>,
  Expect<Equal<Comparator<-5, 0>, Comparison.Lower>>,
  Expect<Equal<Comparator<0, 0>, Comparison.Equal>>,
  Expect<Equal<Comparator<0, -5>, Comparison.Greater>>,
  Expect<Equal<Comparator<5, -3>, Comparison.Greater>>,
  Expect<Equal<Comparator<5, -7>, Comparison.Greater>>,
  Expect<Equal<Comparator<-5, -7>, Comparison.Greater>>,
  Expect<Equal<Comparator<-5, -3>, Comparison.Lower>>,
  Expect<Equal<Comparator<-25, -30>, Comparison.Greater>>,
  Expect<Equal<Comparator<15, -23>, Comparison.Greater>>,
  Expect<Equal<Comparator<40, 37>, Comparison.Greater>>,
  Expect<Equal<Comparator<-36, 36>, Comparison.Lower>>,
  Expect<Equal<Comparator<27, 27>, Comparison.Equal>>,
  Expect<Equal<Comparator<-38, -38>, Comparison.Equal>>,
]
```

**Comment by magne4000** [comment]
Shouldn't it be extreme difficulty?
Did you have some idea how you would have done this?

I have kinda solution but it still fails (recursivity error) if numbers are both too far from 0. See below

<details>
  <summary>Spoiler</summary>
  
  https://www.typescriptlang.org/play?ts=4.1.0-dev.20200928#code/PQKgsAUABFBMDsAWKBaKBJAdgFwKYHNcAnAZygGEB7AWwAcBDI+7SoyGFTrldqAIwCeUAAoBLfFABi9TBIAUAAXwpaAGxm4AlFADEAC0YATKL147zUAIoBXXCWyjKmU9Ax1VuarhxR6UbAK0uCgeAG64qlCiOATEZADGNAxMLEQAdFAA6rgA5OFQtESUoaKGuMYyUN7W1FAAZqxRmIai8czREth6uFCJdIyiJE5QRHbWqtgANFCqogDWPV2DAFwuHBh1UAAG9FtRZPijzMT+BpjbfFvTAUFQJHqU48Z8PVtU-USDTmkA4kd4RC2aV4aHQmx2exkxi2l18oyqAEdrPRVNdAj17o9VM9Xu9kl9MGkAKJIlFAkEbba7fYzSgAdxOXUqMKu-nRdweT34uKSAyGhIAMvTiOTXLwQCAAHKUPCnZhUyHNC57NrnF4FSgkUQOfLRPCEUhQRqYAjtXUxA1kRoAL2IlGmuHC5ycPUGGq1Op6dL0og8vkwMu6RCNJppJvwZtwaQlaygAD4oAA1US4OkhqA-bUACWsfGWUD02GwtBIy2AwGwJHiejSACsSGlWPhgAhEJAQMBIF2IKAoAB9AeDoeDqAATUewaoZSgWeIPWHC4HUA73eqtTxfOGAG9eH9cMciJNeCTkajeEKGYfIABfVcAD1orGwbNuWH1cSgAF4oABtXgABiPVwAEYgJgWAwKgABmSDEEggBWSCADZIPgSCAA5IIATkg4DAN4YDQIIiCCJggi4IIxCCJQgi0IIzCCJw3hYHw1xYCItiSLYsi2IotiqLYmi2LotiGLYpjXCg1iYCgjiZK4mSeJkviZIEmShJkkSZLEmSJJgRBpKgRA5KMhSjKUoyVKMtSjI0oytKMnSjL0qB4MM+CTPgsz4Is+CrPgmz4Ls+CHPgpz4JcpDDKQkykLMpCLKQqykJspC7KQhykKcpCXPgQz4BM+AzPgCykFQmz4Ds+AHPgJz4Bc9DDPQkz0LM9CLPQqz0Js9C7PQhz0Kc9CXKwwysJMrCzKwiysKsrCbKwuysIcrCnKwly8MMvCTLwsy8IsvCrLwmy8LsvCHLwpy8I2vDcMIu69uAg7gKO4CTuAs7gIu4CruAjaWNw9jAb22ADtgI7YBO2AzoQQGrtgDapNw2Tkb2qCDqgo6oJOqCzqgi6oKuqCNoM3DjLJvbEAOxAjsQE7EDOxALsQK7EA2tzcI8zm9p8zmjoCzmzpCzmroi3CovFna4vFg6kvFk60vFi6svFja8twgqNb2kqNaO+ATsqjWLtqjWNsa3Dmotvb2oto7uots7+otq7htw0a3Z2ya3YO2a3ZOxa3Yu1a3ZcljDJYkyWLMliLJYqyWJsli7JYhyWKcljQ9u5j7uz6Onsg9j47eguPpL1OfpL0OAeYoGa+j0GC-BxvE+hxvU9gdOEYLpHmJR3vo-R7v4+x7vk-x7v0+JgvSeY8nZ+jqnp-junp+Tpnp-TtmC455iud36Ped3+OBd3pDIAAXQAbnvR8iGfG4ejfWIiAAZWwT5ZDIb8tx-ABpJooALAEJQTYT9LS+DIFsAAJFuX+14tjn3zGAuIf9z7XmvhASAD8oCSlwHebAyDDTfkIWQPBeBmhkB-JgGoLxDxQDSAw6IdQTi4PwefKAAB+HBZCoD5msM0XAdRojlAwdg4QoxQgkK-L+FAoF6EMJIVfG+T4XyP0wPEAAPAAFQTN+LRVR8HeEMGQIBIDuH4KkVw1hBCLQoK0ew-MJpwhEAwXg2+992QABFcCaJ0dI-RZCjEmNwMAzY4jHSWJEBIkhP57G8KgE44gGCsHsgAIJ8CGKoaweBZyqCCEQDRqSDHkOMQkmhxBdHbBgak+BxSgnbBQDAphJwAAatSuEtPiTkf8ORRFpIyZQLJeBCl1IoWU6gtDKmELfh-fAJAfzpMydk3AuT8mFLjEoiA2DcERk9IQkZgSxnUImRU6R0Ctw1L2Ic0pWxGlbmacGNpewOnxP4WUIRJpDB9NuMITU2pRDhH2UU65ZBjmTLOdU2pIKGlNMwMw4MfZ2lQDeYI4Rxh8znMuckrZ7INwpFYAAIQOYYo55S6EEtGaUsFpzPy8ApdC-8nCKC8k+PyX4-wTirFcMCklpTGVcLxQSNIF5OW8DxcwVgqSNHeM0akuM0wZUaIJXGOM2LsHitSFKnlJTQVkumPS3luqTlEF0bwHZkYgUJmhfYWZnDeAwDkOavZtiCnKspWQG1HQmUasJYUgZQzcBKvlVARZgzlnrLjPa+Jgq2UiqIJoXg+Y5C-I9AC3A+y3XWvfl6gVLKJVECJak-VkbXAwHzDG74e4DyaDVbivNqRiU6vGbQ-V7rm00t4Nq+pFLc0fCFSeFEvCxX1slYU4t2LeyLgXFALRdhnzkHoCQOw-Yp1DmXJ2CAog6AqK3FAAdqI90Ph8c+a89Qii1ByAoB+KBqwog8LIOwwBsm+hIDkbs2C2hLq-r+Y8R74jYA0fujRPqCmIVcsGithJ90qsgkSP9AGgMgY0WBpCEGWVCrjTB39QR-2AdJKoYDI7QPTHQmhvtsbhQmvldh49eHTyEY+PmjRgFwPTEg8KyjWHXBwZwwh-DDHkhMbA-+Mj+I2VVoBFxmAPHaOIaIxolAwnRObkFJx6j3H4N0ZRAJxgTGWMibY+htl0H1PSc03JxjDaWOKeU6yytHKqOwfM-xpDYGUBQVs0KiTFTTOHt41pgjrnpgoHgJ58TDmpN+dky5+TinguhcM+R+z+5JO+Zk7hizgmG1xdQB5xLYnviYbS85+jSGcvuYM8ypLhJvOOZoxlmLlnWAaOLqgUGYXksHki+WKAgACMkAPB-M6ADyQ2oCeKJESYQfX+u8B6+lvjpX5Ok2gglqrBWasReK-5zLunsu42mLjDrqnLyRfmwFnT+KCmwzgKt9jJmnPbca1l5r7nMK5dI-llTxJ8NcfPt2SAk7V0jkkNYO+QYoBv1wCWFdQO+zroB+AVwCYX4GHhMA0Hdww0OCcKWAsRYSxlgrFWGs9ZGxEGbK2YAMgSCXl4AmZMqZMdDMcJgXHhZiylnLJWasdYGxNhbEgYASzses7p1AAAsqwHo5ADCqHvYQNn+POdE556Tps7YN2QCAA
</details>

**Comment by g-plane** [comment]
@magne4000 

- The recursion failure is a limitation of TypeScript compiler, but `Equal<Comparator<40, 37>, Comparison.Greater>` still works.
- Making a integers list isn't an elegant solution. If the recursion limitation is removed in the future, any integers should be comparable, even though very large.

**Comment by Jack-Works** [comment]
My solution. Only works for positive integer number less than 42 (recursion limitation).

<details>
<pre><code language="typescript">
type TupleOf<T, N extends number> =
    N extends N ? number extends N ? T[] : _TupleOf<T, N, []> : never;
type _TupleOf<T, N extends number, R extends unknown[]> =
  R['length'] extends N ? R : _TupleOf<T, N, [T, ...R]>;

type Comparator<A extends number, B extends number> =
  A extends B ? B extends A ? Comparison.Equal : never :
    TupleOf<0, A> extends TupleOf<0, B> ? Comparison.Greater : Comparison.Lower
</code></pre>
</details>

**Comment by magne4000** [comment]
Updated version with dynamic list of int:
https://www.typescriptlang.org/play?ts=4.1.0-dev.20200928#code/PQKgsAUABFBMDsAWKBaKBJAdgFwKYHNcAnAZygGEB7AWwAcBDI+7SoyGFTrldqAIwCeUAAoBLfFABi9TBIAUAAXwpaAGxm4AlFADEAC0YATKL147zUAIoBXXCWyjKmU9Ax1VuarhxR6UbAK0uCgeAG64qlCiOATEZADGNAxMLEQAdFAA6rgA5OFQtESUoaKGuMYyUN7W1FAAZqxRmIai8czREth6uFCJdIyiJE5QRHbWqtgANFCqogDWPV2DAFwuHBh1UAAG9FtRZPijzMT+BpjbfFvTAUFQJHqU48Z8PVtU-USDTmkA4kd4RC2aV4aHQmx2exkxi2l18oyqAEdrPRVNdAj17o9VM9Xu9kl9MGkAKJIlFAkEbba7fYzSgAdxOXUqMKu-nRdweT34uKSAyGhIAMvTiOTXLwQCAAHKUPCnZhUyHNC57NrnF4FSgkUQOfLRPCEUhQRqYAjtXUxA1kRoAL2IlGmuHC5ycPUGGq1Op6dL0og8vkwMu6RCNJppJvwZtwaQlaygAD4oAA1US4OkhqA-bUACWsfGWUD02GwtBIy2AwGwJHiejSACsSGlWPhgAhEJAQMBIF2IKAoAB9AeDoeDqAATUewaoZSgWeIPWHC4HUA73eqtTxfOGAG9eH9cMciJNeCTkajeEKGYfIABfbs3HoAFWsalwAHk6gAeABKVQAHnhmjITAaheIgAG0AF1pgAQT-ADDCAkDiATABeXgvzAnIPFkLocgguDvAQqBYIAfigH98yfF93w-MC0nor9pgwrDvHwXCIKg4i4wAbm7csoGfIJg1GeJrFIUR8lmahtRpRAAFZ6mNelIFwX9aFYbA2VuLB9TiKAUKgKiPBoyDpnkniVLUjStJ6HTYiIABlbBPlkMgDK3MCAGkmigBYBEoTY7MtXwyC2AASLdPOvLYIPzIK4i8iDr14iBIHvYi+CGVRrDwWdVCEj9YNU+DEOoUDUO2CLoOigjAO2FAIuiOoTgADRqsiWqgfMcgABhyFL0ugzLKGyvBCtqojgLK5D9IwC1iCclz8BIMChqynLcDygroLjCCBvZSVTU9eKiHG4rCNK8rZvCrdqr2c66q2Bqtya1r2qgTr82sZpcDqaJyn225hE1bUJNwE6zv-C6oCmq6DJuu6JtC57XuDPt3u+so-pNYx8wR6KUrS9kNxSVhyG-JGYaQ8DOKKqG6th4hpgAIUpxmiFQ9DMOwti9DwynSIoXlPn5NILxOfNmJ59jKdZsiSYJX5-gloWPmYMnaKl1j2Omei0i-WmWYs1KIHSkn1aIaDIZKqnpsPKBWYeybqc51xDojY75tOnbKfsJaoBI3gYDkd3Iwh5mEydsg-Y6APVeSC3ydMjL1rGiOYOG0bcEKuM4yDrr483QVhSITReHzORgY9MHw8j+miJj2Q4-N1Ik8Nh289cGB8wV0W9wPTRCdN4nhYt63ofZlm2Zd-TeDpm25cLkXvhPFEut4FvWCt6CjaH3tFwXQy7E08h6BIOx+wPodl07CBRDoaytygVfUWftTcHiTTr3qIpahyBR7woGrCiHmdhgA5V9CQHId52RtHPm5KAYFjzv0-h+F+H5N6nTktMOScZpi9xXqSVQucjyuCJCg7AaCiEYNHqkD82CoAADY8FL0VuLDmeDkFBFQegzB9DpgAA4WEEOLpeEhXCP6UN4bQ1gH4eo4OEcLNhJdxFkIoVQ08NC1Z0IYT1RRHxFb9wBKomA5DuFSOoXwlAuj9H4lFuwkxb9zEaJRFohOdD5FQD0fgpRosX6OLMZIlxqg3GMDHp46xtii5K33MYzhajnHSO0bIhhKAADMUTl6EiMcheJpj1FJPcSk6YKB4CZMMcrDhpD8mJMsTI061iSllJ8QYvulSAkFLqckhpqSMktLsd8BxeSnFBMKWEuhjTUBpO8awtpsTcnVJGTwrpRTToAEZUmwD6bM74OSqkSOWZovhiBPFpOaTs7J7ThmBMOa4qxaTGHTAeeU+xKjrmdKOfUj8CBpgIBeYQ08HTamfO6R+dJAiSlpKEf06J-j4kQW7JAfeV8RySDEl0E4TlcAlkviivsN8kXgFcAmByBh4T+TEncEaECnClgLEWEsZYKxVhrPWRsRBmytmADIEgl5eAJmTKmKlo1HCYDpYWYspZyyVmrHWBsTYWxIGAKnUVJB+VQAALKsB6OQAwqhQHioZVK5lsq2VNnbLfSAQA

**Comment by AlexAsh** [comment]
Shouldn't there be test cases with different numbers' lengths?
