### ISSUE TITLE
Split a string

### ISSUE THREAD

**Issue by jfet97** [type-challenges/type-challenges#2822]
## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: Split
tags: string,split,array,tuple
```

## Question

The well known `split()` method splits a string into an array of substrings by looking for a separator, and returns the new array. The goal of this challenge is to split a string, by using a separator, but in the type system!

For example:

```ts
type result = Split<'Hi! How are you?', ' '>  // should be ['Hi!', 'How', 'are', 'you?']
```

## Template
```ts
type Split<S extends string, SEP extends string> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Split<'Hi! How are you?', 'z'>, ['Hi! How are you?']>>,
  Expect<Equal<Split<'Hi! How are you?', ' '>, ['Hi!', 'How', 'are', 'you?']>>,
  Expect<Equal<Split<'Hi! How are you?', ''>, ['H', 'i', '!', ' ', 'H', 'o', 'w', ' ', 'a', 'r', 'e', ' ', 'y', 'o', 'u', '?']>>,
  Expect<Equal<Split<'', ''>, []>>,
  Expect<Equal<Split<'', 'z'>, ['']>>,
  Expect<Equal<Split<string, 'whatever'>, string[]>>,
]
```

**Comment by keithjackson1031** [comment]
// Solution

type Split<
  S extends string,
  SEP extends string
> =
  string extends S
    ? string[]
    : SEP extends ''
      ? S extends `${infer Char}${infer Rest}`
        ? [Char, ...Split<Rest, SEP>]
        : []
      : S e


//Test Cases

import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Split<'Hi! How are you?', ' '>, ['Hi!', 'How', 'are', 'you?']>>,
  Expect<Equal<Split<'Hi! How are you?', 'z'>, ['Hi! How are you?']>>,
  Expect<Equal<Split<'Hi! How are you?', ''>, ['H','i','!',' ','H','o','w',' ','a','r','e',' ','y','o','u','?']>>,
  Expect<Equal<Split<'', ''>, []>>,
  Expect<Equal<Split<'', 'a'>, []>>,
  Expect<Equal<Split<string, 'whatever'>, string[]>>
]
