### ISSUE TITLE
IsRequiredKey

### ISSUE THREAD

**Issue by jiangshanmeta** [type-challenges/type-challenges#2857]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: IsRequiredKey
tags: utils
```

## Question

Implement a generic ```IsRequiredKey<T, K>```  that return whether ```K``` are required keys of ```T``` .

For example

```typescript
IsRequiredKey<{ a: number, b?: string },'a'> // true
IsRequiredKey<{ a: number, b?: string },'b'> // false
IsRequiredKey<{ a: number, b?: string },'b' | 'a'> // false
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type IsRequiredKey<T, K extends keyof T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
    Expect<Equal<IsRequiredKey<{ a: number, b?: string },'a'>, true>>,
    Expect<Equal<IsRequiredKey<{ a: number, b?: string },'b'>, false>>,
    Expect<Equal<IsRequiredKey<{ a: number, b?: string },'b' | 'a'>, false>>,
]
```

**Comment by kyuridenamida** [comment]
Do we think adding `Expect<Equal<IsRequiredKey<{ a: number, b: string },'a'>, true>>` to the test cases makes more sense?

The current test cases can't distinguish the following two solutions:

```
type IsRequiredKey<T, K extends keyof T> = T extends {[k in K]-?: T[K]} ? true: false;
```

```
type IsRequiredKey<T, K extends keyof T> = {[k in K]-?: T[K]} extends T ? true: false;
```

**Comment by jiangshanmeta** [comment]
@kyuridenamida  Would you mind to make a pull request

**Comment by sinoon** [comment]
pr are welcome
