### ISSUE TITLE
13580 - Replace Union

### ISSUE THREAD

**Issue by onionbrowsers** [type-challenges/type-challenges#28792]
```ts
type UnionReplace<T, U extends [any, any][], Arr extends any[] = []> = T extends U[number][0]
  ? [...Arr, U[number][1]][number]
  : [...Arr, T][number]
```

**Comment by moonpoet** [comment]
`
type R1 = UnionReplace<
  Function | object,
  [[Date, string], [Function, undefined]]
>`
Is this use case wrong?

**Comment by moonpoet** [comment]
> ```ts
> type UnionReplace<T, U extends [any, any][]> = T extends U[number][0]
>   ? U[number][1]
>   : T
> ```

`type R1 = UnionReplace<
  Function | object,
  [[Date, string], [Function, undefined]]
>`Is this use case wrong?

**Comment by moonpoet** [comment]
> ```ts
> type UnionReplace<T, U extends [any, any][]> = T extends U[number][0]
>   ? U[number][1]
>   : T
> ```

```
type R1 = UnionReplace<
  Function | object,
  [[Date, string], [Function, undefined]]
>
```
Is this use case wrong?

**Comment by onionbrowsers** [comment]
> > ```ts
> > type UnionReplace<T, U extends [any, any][]> = T extends U[number][0]
> >   ? U[number][1]
> >   : T
> > ```
> 
> ```
> type R1 = UnionReplace<
>   Function | object,
>   [[Date, string], [Function, undefined]]
> >
> ```
> 
> Is this use case wrong?

yes, my answer has some problem, you can use 
https://github.com/type-challenges/type-challenges/issues/20711
this answer，only need replace `never`  to `T`
i will try how to resolve this problem

**Comment by user65536** [comment]
This solution failed on this case
```ts
Expect<Equal<UnionReplace<number | string, [[string, null], [Date, Function]]>, number | null>>
```

A little update:
```ts
type UnionReplace<T, U extends [any, any][], Source = U[number]> = T extends U[number][0]
  // using union distribution to find target
  ? Source extends [T, infer Target]
    ? Target
    : never
  : T;
```
