### ISSUE TITLE
Nullable

### ISSUE THREAD

**Issue by jiangshanmeta** [type-challenges/type-challenges#2893]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: easy
title: Nullable
tags: utils
```

## Question

Implement the generic ```Nullable<T>``` which makes ```T```   nullable (contains null and undefined )

For example

```typescript
type nullableString = Nullable<string> // string | null | undefined
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Nullable<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Nullable<string>, string | null | undefined >>
]
```

**Comment by antfu** [comment]
Won't this be too easy? 🤔
