### ISSUE TITLE
Unique Items

### ISSUE THREAD

**Issue by bgenia** [type-challenges/type-challenges#30178]
## Info

```yaml
difficulty: hard
title: Unique Items
tags: tuple, application, cif
```

## Question

Some concepts in TypeScript can not be described by types, but can be expressed through type constraints. For example, you can't define a type for positive numbers, but you can check whether a number literal type is positive. One of the patterns for applying such constraints is constrained identity function (CIF). A CIF takes one parameter, infers its type, performs additional checks and returns the parameter unmodified.

```ts
// Ensures `n` is a positive number
function positive<const N extends number>(n: `${N}` extends `-${string}` ? never : N) {
  return n
}

const a = positive(1) // Ok
const b = positive(-1) // Error, -1 is not assignable to never
```

Write a CIF `uniqueItems` that takes a tuple of literals and ensures that all of them are unique.
You are free to use either mutable or readonly tuples.

Bonus task: Helpful error messages instead of `not assignable to never`.
Bonus task: Only repeating tuple elements should be treated as errors, not the entire argument. 

## Template

```ts
function uniqueItems(items: any[]) {
  return items
}
```

## Test Cases

```ts
import type { Equal } from '@type-challenges/utils'

declare const readonlyEqual: <A>() => <T>(value: T) => Equal<Readonly<A>, Readonly<T>>
declare const expect: (value: true) => void

// Should work
expect(readonlyEqual<[1, 2, 3]>()(uniqueItems([1, 2, 3])))
expect(readonlyEqual<['a', 'b', 'c']>()(uniqueItems(['a', 'b', 'c'])))
expect(readonlyEqual<[1, 'a', true]>()(uniqueItems([1, 'a', true])))
expect(readonlyEqual<[undefined, null, 3, false]>()(uniqueItems([undefined, null, 3, false])))

// Should error
// @ts-expect-error
uniqueItems([1, 2, 2, 3, 4, 4, 5, 6])
// @ts-expect-error
uniqueItems([true, true, false, false, 'b', 'b'])
// @ts-expect-error
uniqueItems([1, 1])
// @ts-expect-error
uniqueItems([undefined, undefined])
// @ts-expect-error
uniqueItems([null, undefined, null])
// @ts-expect-error
uniqueItems(['test', undefined, 'test'])

// Bonus: Should give detailed errors
uniqueItems([
  1,
  2,
  // @ts-expect-error
  2,
  3,
  4,
  // @ts-expect-error
  4,
  6,
  7
])

uniqueItems([
  true,
  // @ts-expect-error
  true,
  false,
  // @ts-expect-error
  false,
  'b',
  // @ts-expect-error
  'b'
])
```

**Comment by bgenia** [comment]
[Solution example](https://www.typescriptlang.org/play?#code/PQKgsAUABFDMAMBGA7ADigWigVQHYEsBHAVwFMoBJAF1IFsBnSGDF1jJqAIwE8oBRAG4BzUgV4AKAAKcRBAIYBKKAGIAFnIBOAExVViABwA25ZXP1H8AYzlV8Ae1wrL+AGaQOyz1ACKZerYd3aCgAZTtacksHS1J9KnoofEcAFW59UhDLDXw4qGtHXDsqLnItUnos-E5SHR4oKjTygBouYmL8kqhSAA99DXL6GvrVDTtiIVV6xryHfw05JPiAOg4AMTsNLu65WiNSFu4xvLlcAHJispck8jkp9KgXDah9O3p8WwFyXGJaao16FqcNpQQ7EY6OSyqUiWADWUAA7lCqFDNrdvr9SJtDO9MXJDHdyPgEi83h9SCtggB5XDkOwuYbkfQ2GgaXAJR6o8yGbhJIRQejESEzNlUeaLBJE4VzBY0nT4Mq4WwNB7EXCWAKOcQAYQoqwUFJgAEEoDrVvU5DDylAHIzNDtSCyWkkXJiJfECS10hoOQwoHItFp3vZcHi8lDYQkTjp+npWQlkbb5hEWVBVbQ7IGrjUKRwAAb5+IcYDAfhs4j9BK53C5xKR56vIOfKDov4cFyq9XB+uk-CfAA8URFUAAclsaLgtAkW5iAHziXAALiguYAJABvYcAXxrPXHk+XGHXc1526gAH5m6RPpsl8OlGuODAY+WChxN0EYIP-H6oABebuNqQ4iIEoxZQJSMIcF+xScH+AFkuIGAgVAYF8BoowaC0SG1s2RR+vQbxCCGnDGPUdiXteeb5h+UAAOrZDQP6msuqpEGQ1B0PQNbIjY5qWnWeh7Na9LYiyeKRhOXRlhWwy8Xi+J0gytB+v0qYECQ5IcAAmkcmjkC4-TkFQ5HEIMXTvCiUC0G0cgkbSmz9P6DjcvUBjGPQObBAAQg4pnmvQMJLgAEqQhj6O2+KYhhVkDHIIgSiKpD+sJy6FMUcgEfgRG2aRxkUZiuYGlAPnfPGGWBeBuAuf06Q2LyrlCaFdCiO69CqGMhi1EZjk0DoGVdOhGwArhxQJlJtiqZoQg-C1nkwDOUAAGr4KQ8LWo4ADi7xBcQnBLqoVBUPo9ALsW8SQksABWHkbEIwAICgqCQCAwBBKAUAAPpfd9P3fVAOnliaGbkCFqm-eDX1QC9QSLJiLhyDE-CDRofbJAAsrFIhwTS14LWun0fVFGziBEBFxaQS7o5jpAKEuOOYlA74QJADT3HwvTQlQeBsaQHEMKjfMJLuoj7o5WjObwqowoU8K4AA2gAui0yQAErlMQhjFMLE4JGLEtqdLdiy4rcGKwtv4cMkgtjiLutJeLVW8HLzoM8kqz4P8VAtEsPsu5sqvlFQCuPueUBux737a-uAcCprcvThowfBDAMAXuz6TqtzGmC6jav+C0euO1Acs+0sMca17SMYX2csAER8MYESKrXyvu57LS5rxcvruXce18YuBCMitcK5uCs4Wlak87mCszrPIcwEu6ec1n7E0PzMeV4XLklz7veV+Hnvz8nUCU3nFdBO2aoalP2fr-QA6zMUVv3zbOtQNvku4Ibxuz+IHA4gYEvZGb99zL0zupNenEBb3xnPHH4fwk4p1DuArmkDeb3xgZxGcIdKaC0gPeDgz5WSJHvpAJmkB3oQ3BmHQOJoMpWmob9KGr0ID4F2BsUa0x8Z8BIKGTcDxRjKVOJIVmpAMCQnkqIeKwA2j4EMPQU4QQyiWEMHpKUxRP68OIHiJcfZDRziUL+BaqM5wCDxGQSmRiFraLxH2NWTlHb6JnC0BxDtuSmJwRAFRajVLQS2BnKgS5xDmMMJY+oGgyDWKgAIOw8o3olhCO1DWOh4QbEghAHogTxBaL4YYGuiAWgACYWiwD-gocQrE76cXEHLQpUASlwAVgoFpkAsmcxyfbCWtj8ly1OHIU4LRTicEGVAU4lhTjlMqegwWtT+mjOGQsiZzTWmZI5uqTpjjuQ9IKUMgZLRRRkCmVUqBDBan1PmQcyJpAVkKDaesqgmz3HcB2XLVUlxrhaBaN8QwhhSktHhgom5hjpk81mW8icpAriym+RrP5cAAXiRuS0u5zMIBgSSR1HQRMNCUJLKI+gGB2nqiJcjSAJyME1LqcUmlCKoAABYWiMqgAAVhaAANmaXiqABKiUPNJRhclMz761MOfsCJZBEVAqlYMIZIy5WTNRWBXlxKqACo2EKsFIrqVQEQFy9F+L4h8sCeq3FEAKXgveVCz5LQrXQpqPq5VRrVWms1dUs58Dfm2shfar5zY4WOsNYSl1OK3WnPoHMmg-hRl2ptWMqNVBFUJOKr5E6oRkmdSgEIXspQHQLGMNi5GjBzXCqpRwQpHASlFiDcazmrrghVuCLAJoHBGXVp5c6-lobghtuCOyltwRkCQH1WGylHqOBioHTAJ1wau1kuCJOtsSKp0oRrSG+dMBAWyo4IsldM7a0ku7TARZw7UWUJAATJhkNVjlgTJsEINBjqXqvSw89HAFpJPUaCTY9A7BhI1Gmg6R0TpnQqKoK6N0NB3QemgYAJx6DwkxO+paK01q-v-cGQDh1jqnWAOdcD10li3XukgWD6G5GzGQ2jDY5AtTqF+dI8o+1sMgbw2BiDRGoPPVYUAA)

**Comment by jazelly** [comment]
LGTM. The only thing I can comment is maybe it's more consistent using `Expect` instead of the customized `expect`
