### ISSUE TITLE
2946 - ObjectEntries

### ISSUE THREAD

**Issue by qianzhong516** [type-challenges/type-challenges#30608]
```ts
type ObjectEntries<T> = Required<{[P in keyof T]: T[P]}> extends infer Obj ? keyof Obj extends infer K ? K extends keyof Obj ? [K, Obj[K] extends never ? undefined : Obj[K]] : never : never : never;
```
The idea is to extend on keys of T  and trigger the typescript's distributive behaviour to make a union type as the result.

`[K, Obj[K] extends never ? undefined : Obj[K]]` is a kinda hard-coded solution for by-passing the case 

```ts
ObjectEntries<{ key?: undefined }>
``` 

Because `Required<{[P in keyof T]: T[P]}>` would transform `{ key?: undefined }` to `{ key: never }`!

### Better solution
It is way more concise to write
```ts
type ObjectEntries<T, U = Required<T>> = {
  [K in keyof U]: [K, U[K] extends never ? undefined : U[K]]
}[keyof U]
```

**Comment by 2102819372** [comment]
Genius
