### ISSUE TITLE
Fixed String Literal Type

### ISSUE THREAD

**Issue by sugoroku-y** [type-challenges/type-challenges#30970]
> テンプレートに従って内容を記入してください。PRは自動生成され、常にあなたの変更が反映されます。
>
> 詳細な解答/ガイドは必要ありませんが、課題が解決可能であることを確認してください。

## 基本情報

```yaml
# 難易度
difficulty: medium

# タイトル
title: 確定した文字列リテラル

# タグ
# tags: string, string-literal # separate by comma
```

## 質問

確定した文字列リテラル型かどうか、を判別したい場合があります。例えばクラスの識別子として指定された型が確定した文字列リテラル型であるか確認したいときです。

```ts
type Action<ID extends string> = { readonly id: ID };
```

確定している必要があるので以下の型はfalseと判定する必要があります。

- never型
- 文字列リテラル型のUnion
- string、number、bigint、booleanが埋め込まれたテンプレートリテラル型

与えられた型Sが確定した文字列リテラル型かどうかを判別して下さい

## テンプレート

課題の挑戦者がコーディングを始める際のテンプレートです。基本的には質問とテストに合わせて型の名前を変更して、実装は `any` とするだけです。

```ts
type IsFixedStringLiteralType<S extends string> = any;
```

## テストケース

あなたの課題のテストケースです。`@type-challenges/utils`が提供するいくつかのアサーションを使うことが出来ます。

```ts
import type { Equal, Expect } from '@type-challenges/utils';

type testcase =
  | Expect<Equal<IsFixedStringLiteralType<'ABC'>, true>>
  | Expect<Equal<IsFixedStringLiteralType<string>, false>>
  | Expect<Equal<IsFixedStringLiteralType<'ABC' | 'DEF'>, false>>
  | Expect<Equal<IsFixedStringLiteralType<never>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${string}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${string & {}}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${number}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${bigint}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${boolean}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${true}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${false}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${null}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${undefined}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${string}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${string & {}}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${number}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${bigint}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${boolean}`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${true}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${false}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${null}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${undefined}`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${string}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${string & {}}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${number}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${bigint}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${boolean}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`${true}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${false}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${null}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`${undefined}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${string}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${string & {}}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${number}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${bigint}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${boolean}DEF`>, false>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${true}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${false}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${null}DEF`>, true>>
  | Expect<Equal<IsFixedStringLiteralType<`ABC${undefined}DEF`>, true>>
  | true;

```

**Comment by jiangshanmeta** [comment]
Hi @sugoroku-y , help to provide the solution. I don't know how to solve this challenge

**Comment by sugoroku-y** [comment]
OK. This is my solution.

```ts
import type { Equal,  NotEqual } from '@type-challenges/utils';
type IsNever<T> = [T] extends [never] ? true : false;
type IsUnion<T> = NotEqual<[T] & T, (T extends T ? [T] : never) & T>;

type IsFixedStringLiteralType<S extends string> = true extends
  | IsNever<S>
  | IsUnion<S>
  | Equal<S, string>
  ? false
  : S extends `${infer First}${infer Rest}`
  ? true extends
      | Equal<First, string>
      | Equal<First, `${string & {}}`>
      | Equal<First, `${number}`>
      | Equal<First, `${number & {}}`>
      | Equal<First, `${bigint}`>
      | Equal<First, `${bigint & {}}`>
      | Equal<First, `${any}`>
    ? false
    : IsFixedStringLiteralType<Rest>
  : true;
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgsAUABFDMAMBOA7PKBaKguj0Fnah1BkH0GQcNNB1bUHQlQK4ZAxhkEuGQa4ZIZ1mX1GoAjATykFuwwBW1A0jqAZ5UC2ilAAUAAQDOAVwDmAewBOSgNZz0XAJRQAxIFo5QFi+kdvotRAVzGB5VTPRs+YuWr1A0eqBpBkCWDIDEGD4EAGQCSGQBIlQFIlQkARBkAWDUAIFUAZBkAhBkAohkA-BkBNBkAgBkBo+UAJBkAHBkB6hhpAToZAOwZADWjQ-kALBjxAMwZAcGMcQFUGQBiGAjc43EJSSlo6N0BzBgTAaIYPLEBYqMjqwFkGQcz7GAADFYAXGXZVrgAHAFMoAEEAY1WASyUAOwAeAEkAEShdgA9V3YuAExkoGVWVU4uFAA+KAAXigAG8oCpdgBDd6XAA2PFO7wAXFB7lAAL4AbnYKyWi0c9QiI0Ao-qAQMjEiNSoNAKdygGg5UpuQD2DAAzGEImS7arBHBpclU5LpDJEzAXXYAN12Kjc7EwvVcA1KAFULucLvLvr9-gp-Bc5ABbDgy-wcU4Kf6rM1KJQI2EXOKAafVAIEMgB74lLtKiAZ4ZAOsMgBuGQA-DIAJhiVcog7EAcHI5QCRDO03ABlLpORX9Ty+DwhcJ1BnNCJE4EAcVOqwAEnIOINJgLAFj-AAtVqttjJUcBgOsjnWAHQAKxkXdUCmACBQ8GAPZhkBAwEgp0N21UqygWz2EKgAFEAI5yTkAGg3Tz2J33ADklKstzuEdioGy1IaoAByKQr3boTuc+0A3YyYByM5co+eIRhAoBQAA+pBUHQVBUCAMoMcGANYMgDNDIGgCTDIEgAYUYApooQTB+HgVA072K+GIyCeUoylcAAqwJggA2tRAC6jwvG8nxQPRErSioLEAPzLiocj7OiHJcrswGkTcMhqhqNF0VAZ4XtunJXIxLEAGRQNR+4SNRrGvB8Xz6QJ6lQOi3EynoWm0cBkBSTIABipxPLs7wJjqAIADIljKnLUTsuxXAmBnsV8Px-ACCm-MJoVGZI0kUTxwXAgAPmRsmXClUDpZeqkJvuEW6oCegCWJ3LmewIXPIZHFLAAJOC-xsjKUDOSoPxYo1zWtQASj+qxYksUB8ewMAxfsNVhZIY0wDlG4qQiVztT8hWeUCs0wLli3LacHWrPuDXgkVAJQFp4JYkNgKbfNeVLStB1QEdBrGjKV03dtV67fth2NS9JoqGdEKXUs10OHNt07Q9v3gualoXINoMfQtX3Q09jVw1aQMXe94NzZ9qlo0dMIXFwuMQ6Vt6chV6LSc5rnuetPmvCo-mBVc-U-GDMDohNdmgSAeEEdBUBUMUwaAI0MgbFELwuQURM4gaRrw-EcMIVSC7C5YeuwnFcd23E5LluR5kUKMzfkIgFexXI+BwAEIAMKPoC+4TYC3O3TresG3TxuM2bFus1b7MnUC+7lbsHtaweR6rPrO1+wzpu6kHbM23bTuPvNj53OujkuxH1NR572txwnX1JybTO+cH1tBZZKiu1T4nRw4Ze6-HvtG8nNcs+nQVHWHV1F63pex53FeqVXAep7XA9XEP63YyDzeR23W0Tz7ic99XgfzyHNvPUaAMjy33Ib175fd-Te9z-3h+DxjFpWmf6-j+u3tdzvt+z95B-10XhjW09oSZv2LpfDu29K67z-ubAB7MjoTTPu7D+X8p5LRninf+D9AFHUjigoSJcY6f2vj-f22D4G4MQX9OQCIESEOEpAre38YG-0oWnR+QDwRyA+LsNk-w3KMOIe3FhGDDbsL7pbPBDtHaNWHqDUeF80FkLYRQqRddEGyPkcvc6q8lEiM3qQyeN91H72oUfbR4J-pvUUefQxV8THkN7uY6RWinbP3hojNeECVFOLUS4++bjLEeNhiAh04Cx4kPQaYwJODgmDyscguxqDomqOnrAjhCCQlyPBAQlJRDmHGOgRkyRrjNE5NofQ4RRSYnOLvvEipiTQm8PePwwR7wal+JKZgzJGiF5LzNliPOjk7HvzSf40pZiglNO4WHFewz85jN8RMnpEjpmNIGbQ16KhFmjJ8VE0RxTWFTLiVQhJ3DMYIz2csw5Ri6kBIaec2ZR0ODhLASM25yjVknN6WUmZWzwTIM+c3VJRyHmnKeZwvBjUCEgrdoU7pvz1lnOhTQ6xdCGHwsEkwpF4isH9K4UdVp7SJSdOxWC+56S-kbOeQMqxw9sXjPBdSlFULsnNNyfMvRNyDnfJZZMmlqKOWLysTY3ZTKVkCrWQS8p9LQlXMGpKu5jiZV9LlUSqxby7QROVfyqlgq2VwLRZUoFRDeUItxT8-F6qAWatCXCpZoLEXWtieyixnKqlYqdZahxUDkWyrtTIlpfCBFkotTiv1kb+ZgTliLQAhNalGKFQQAwwy+llnLBWkBQDsGBIAY8jAAq3oEQAjoqAEhzWsDYmwtjbB2bsfYBwqCHCOVAwASYyAAO4ynHJOBw+ai2AGjIkY9ZGzNlbO2GQnZez9kHMOJALaZB2n-BqDYvaoCAF0GUogA1uVKIAJqjAAyGcOqtY7a1TobUOCcU5FZAA)
