### ISSUE TITLE
2946 - ObjectEntries

### ISSUE THREAD

**Issue by jbalancer** [type-challenges/type-challenges#31568]
```ts
type ObjectEntries<T, R extends T = Required<T>> = {
  [P in keyof T]-?: [ P, R[P] extends undefined ? undefined : R[P] ]
}[keyof T]
```

**Comment by TimDreamer** [comment]
@jbalancer 
I wanna ask about this part `R[P] extends undefined ? true : false`. (I change the ternary condition to make the problem clear.)
If `R[P]` equals to `(string | undefined | number)`, why the result wouldn't be `false | true | false`, which will be `boolean`?
Sometimes we use `K extends K` to iterate through union type, so now I am confused. Could you give me some clues?

**Comment by zcfan** [comment]
> @jbalancer I wanna ask about this part `R[P] extends undefined ? true : false`. (I change the ternary condition to make the problem clear.) If `R[P]` equals to `(string | undefined | number)`, why the result wouldn't be `false | true | false`, which will be `boolean`? Sometimes we use `K extends K` to iterate through union type, so now I am confused. Could you give me some clues?

It's a bug.

According to [TypeScript doc](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types), `When conditional types act on a generic type, they become distributive when given a union type.`

[But it fail to distribute in properties of mapped types.](https://github.com/microsoft/TypeScript/issues/33669)

Demo code:

```typescript
type b = string | undefined
type B<T> = T extends undefined ? true : false
type bb = B<b>
// type bb = boolean <------- Expected

type a = {
  aa: string | undefined
}
type A<T> = {
  [P in keyof T]: T[P] extends undefined ? true : false
}
type aa = A<a>
// type aa = {
//    aa: false;  <-------- Unexpected
// }
```

A workaround is introducing a helper generic type:

```typescript

type a = {
  aa: string | undefined
}
type A<T> = {
  [P in keyof T]: T[P] extends undefined ? true : false
}
type aa = A<a>
/*
type aa = {
   aa: false;  <-------- Unexpected
}
*/

type Helper<T> = T extends undefined ? true : false
type C<T> = {
  [P in keyof T]: Helper<T[P]>
}
type c = C<a>
/*
type c = {
    aa: boolean; <-------- Fixed
}
*/
```

**Comment by zcfan** [comment]
> @jbalancer I wanna ask about this part `R[P] extends undefined ? true : false`. (I change the ternary condition to make the problem clear.) If `R[P]` equals to `(string | undefined | number)`, why the result wouldn't be `false | true | false`, which will be `boolean`? Sometimes we use `K extends K` to iterate through union type, so now I am confused. Could you give me some clues?

According to the discussion in [this issue](https://github.com/microsoft/TypeScript/issues/22945#issuecomment-376955411), it seems the conditional is distributed only when the checked type is a naked (generic) type parameter:

```typescript
type a = {
  foo: string | undefined
}

type A<T> = T extends undefined ? true : false
type B<T extends a> = T['foo'] extends undefined ? true : false

type aa = A<a['foo']>
// type aa = boolean
type bb = B<a>
// type bb = false
```
