### ISSUE TITLE
Distributive Conditional Types & Mapped Types does not work together

### ISSUE THREAD

**Issue by jiamingparker** [type-challenges/type-challenges#33470]
For challenge [20](https://www.typescriptlang.org/play/?ssl=33&ssc=117&pln=27&pc=1#code/PQKgUABBBMAMEFoIAUBOB7AtgSwM4FMA6AQwBtTJEFqbKAjATwgEEA7AFwAt1WmAxAK4QAFAAFiHAGYCAlBADEmfABNsAzAuKpUxJvIAOGHATCV55iAEUB+XO2w9TUACoN9+CFw-TWAY3s8EAAGaFh4+MzkQZ6cxOwQxL6++PrsuAmsCdq6EOiSKEbhADLYANYe6HQAVvj+uAA0MR6o+OwCqKzYrADmEABuZDYQuNwCpMoQdB4hhQQAPM4AfNEA7pz4LcHO0XhNEC246KR9Kvu2Y-FaOgyETsFBQWmUvjx2EIZhBACMEAC8BZ8iAcjidhABmGQAbmer3iH2M+GgfwgABZoNCoC9WG94eEwcjWPgVgCEXM7Kgut1FsJhMDjvhGi0av45L9FhAAN6UKAEdjObBKdACdi02wghkQL6wWCNADkknQ6FlUMoAF8VZRgMAIPgAB7ufyndjoSbTUKkgDarHUU1QjTRjXJlIAussYdi4cjzeFIqRhBbcd9GoHEcHZvgwc6EuksXYZJQHkE7uyAGrYIm5TIAcWw7AAEgI6AAuCCcdjsfS4ItatK+TiEKq4QjoVDdYBwMAgYCmUAQAD6A8HQ8HEAAmkLUBAAMLoZQePMbDzD5cDiBd0xgLUQZycXbKdC2CCsdDxFYt0pgOe+UhabwCPwBTLegi+hY63XsfCsZTpCQMC2usIAykDYVZnMQ+6sKQTAWoQcHOM6Mgls++BzByEAWgA0hAXQQOUDB5Nuzols4WFRnqn7fukKFzF0kgbBAABK7IAPxMRAJFkRAqqLNCPbajuuxnqgpS4Ju2rsG4HgALIMMwKzELmKgLOy-zOO+lE-iS4S0aw9GTsxEBsYxHHbpetQ3psPj+A4T7hq+6kUV+Wl-gB1LAaBJYtBBPDQRhcGEAhSHafM6FYThmT4YRCElrJ8mKZ+ygLGR7I8Xxm4gP2K7DtutjxFOxAEOk2U5euAr6C28SSe4nIQAAogAjgIZCNHV+q1PEqoQJIRgQLKojVfgCB1mQpBft0tjAMK2CkLgsqmLGcL2eQzh5T8-wob6-pfI00CNJG0YQIt8aLe8y2kKtdhIht53bbtjQoYQdKghCUaFUdsInbCZ2Ar6l3sPiN2-eQd0wA94ZPWK9LgjIiFgKdIZ-XlKJeudczMNkDBzNamC2hAAA+IWoTjtqLGToN7RAkbxmAg1HYVh7-BalBtQa7BzI1zWkHMg2EYjK1reDgJzBaO1g1Trpk-ULPtf4HNNWQPNSXz53-ZTNGi-dR42hskuLNLUCsx18tc0r7gq8DF15WCQuWiTGyNPbdra7jutk-rMtsybiu8-k-NW3YKK2zpTtuVLYDOj2mUlUOECCKgXiTgAyp+lZZTHfZrt2oCUOySexJsBHtMMRzTa8JZlhWVY1rgdYNk2LZtnAwASLgKwbLnEBphmhwgY+YGV5W1bALW9aNs2rbtrAwC92X2Kd9JLYeFOsTkONtgV+WQ813X4+N523ZAA), the most rated solution does not work for test case 4 for me:
```
declare function PromiseAll<T extends any[]>(values: readonly [...T]): Promise<{ [K in keyof T]: T[K] extends Promise<infer R> ? R : T[K] }>;

```

I have to move the `extends` part to another generic type
```
type MyAwaited<T> = T extends Promise<infer R> ? R : T
declare function PromiseAll<T extends any[]>(values: readonly [...T]): Promise<{ [K in keyof T]: MyAwaited<T[K]> }>;
```

This is really confusing. My explanation is distributive conditional types does not work in mapped types. When T[K] is a union type `number | Promise<number>`, the distributive behavior does not happen. But if we use another generic type, the context is clear and the distributive behavior happen again. 

Anybody can explain on this?

**Comment by ZLY201** [comment]
For the first case:
```ts
declare function PromiseAll<T extends any[]>(values: readonly [...T]): Promise<{ [K in keyof T]: T[K] extends Promise<infer R> ? R : T[K] }>;
```

It equals to:

```ts
// replace T[K] to number | Promise<number>
type Value = number | Promise<number> extends Promise<infer R> ? R : number | Promise<number>;
```

It obviously will return `number | Promise<number>`.

But in the second case, you abstract the judge Statement, so it will be:

```ts
type MyAwaited<T> = T extends Promise<infer R> ? R : T;
type Value = MyAwaited<number | Promise<number>> = MyAwaited<number> |  MyAwaited<Promise<number>> = number;
```

So it works fine.
