### ISSUE TITLE
Why are these two results inconsistent

### ISSUE THREAD

**Issue by come-on-lxs** [type-challenges/type-challenges#33655]
![WX20240630-202746@2x](https://github.com/type-challenges/type-challenges/assets/24729896/4b846526-03e5-44ef-a471-6db21e262d47)
![WX20240630-202816@2x](https://github.com/type-challenges/type-challenges/assets/24729896/d96b3477-1302-45d2-a7e1-eb084f0e997f)
![WX20240630-202830@2x](https://github.com/type-challenges/type-challenges/assets/24729896/4947bd23-091a-4c89-b124-407ef2335c38)

**Comment by teamchong** [comment]
In TypeScript, `boolean` is defined as the union type `true | false`, meaning it can be either `true` or `false`. Therefore, `true | false` cannot extend `true` because it includes `false` as well. This inconsistency is demonstrated by the type `B = boolean extends false ? true : false` returning `false`, confirming that `boolean` does not extend `false`.

**Comment by come-on-lxs** [comment]
> In TypeScript, `boolean` is defined as the union type `true | false`, meaning it can be either `true` or `false`. Therefore, `true | false` cannot extend `true` because it includes `false` as well. This inconsistency is demonstrated by the type `B = boolean extends false ? true : false` returning `false`, confirming that `boolean` does not extend `false`.
> 
> ```ts
> type CanExtends<A, B> = A extends B ? '✅' : '❌'
> 
> /* _____________ Test Cases _____________ */
> import type { Equal, Expect } from '@type-challenges/utils'
> 
> type cases = [
>   Expect<Equal<CanExtends<true, boolean>, '✅'>>,
>   Expect<Equal<CanExtends<false, boolean>, '✅'>>,
>   Expect<Equal<CanExtends<true | false, boolean>, '✅'>>,
>   Expect<Equal<CanExtends<boolean, true>, '✅' | '❌'>>,
>   Expect<Equal<CanExtends<boolean, false>, '✅' | '❌'>>,
>   Expect<Equal<CanExtends<boolean, true | false>, '✅'>>,
> ]
> ```
> 
> [Playground](https://www.typescriptlang.org/play/?#code/PQKgUABBAsCsCcEC0EBiAbAhgF2wUwDtJklSziAjATwgC8ALAewFcqBLAWzYIHMIAKAAIBjehQBOjAJQQAxBzwATNsw5zM48ZirFis-RACKzPAGdsbRkSjEAkgQjZ6bUxFGZ06QjzwAaCFQsEADuLOiKEAR4So6MIeJs+BCYjlQADniO9DiOmADWZskOGlo0mAQReFy4MU6ZAGZYNcWa2qkZAHS6UKiM4hB4AB6YHGleAFzdEAAGs9imxNjpDU34DgC8aKuEADwA2gCM-gBM-nsAzP7QALpne3uw10-XAHwQwMAQhyf+lzD+j2Is2mUzeADU2HhghArBAAOKJAASzAo4wg9FwaVM4w+81EHQAVqYOn0eMA4PAwCBgGBaaAIAB9JnMlnMiAATRY-QAwoxFJlEXhxJlWaKmRBqbSlhkINzygBRQZrRSmHYAQX8ACE3ps1QMlYQVRBNRAAPwQADkgFByC0QNEWwAy5Ba6SBGWLWRAACpmbCyzCmQruj2SzhpPq+6WZADeEHlAEdmB5-IqMsJfQBfCD1SRqC2CSNIdyebxmYDMCzoUzOsCRtz+wqbPbEFN4NM7eOJ9A7OUERXK1XYcQmfwURiMLzlF7+a0Wl5T5uDVPYdsJjzdhUGiqq+oeAMjscTghTy02ue+BdLled9e9zcqnaDkwQAA+Wd3fggo-HeEn09P86gFs2w7Ncez7Q1VS-Q9-EfPBjxnF9LSdM8L1bZcQK7MC70gg8fwIfwd0rOC-1tV9HVnADY0XNCr1Ajd+x2KC8JgodMlfQiA3g-9z2uWkXTdINxVQZhxDqfoAGV8CxATBIlGlQGIN5xOyYUAi5CBTHHctLAIbF0UxbFcVMfEiRJcQyQpYBylMYIhUUiAIShDStIsKw9IxbAsRxYA8XoQliVJckEGATT0G0tz7IAWT6TJuWyYteDMNEPK8oyTIC8yqRpMAgA)

thanks
