### ISSUE TITLE
Compare Array Length

### ISSUE THREAD

**Issue by ScriptBloom** [type-challenges/type-challenges#34007]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Compare Array Length
tags: recursion, array
```

## Question

Implement `CompareArrayLength` to compare two array length(T & U). 

If length of T array is greater than U, return 1;
If length of U array is greater than T, return -1;
If length of T array is equal to U, return 0.

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type CompareArrayLength<T extends any[], U extends any[]> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<CompareArrayLength<[1, 2, 3, 4], [5, 6]>, 1>>,
  Expect<Equal<CompareArrayLength<[1, 2], [3, 4, 5, 6]>, -1>>,
  Expect<Equal<CompareArrayLength<[], []>, 0>>,
  Expect<Equal<CompareArrayLength<[1, 2, 3], [4, 5, 6]>, 0>>,
]
```

**Comment by jiangshanmeta** [comment]
```typescript
type CompareArrayLength<T extends any[], U extends any[]> = 
  T['length'] extends U['length']?
    0:
    T['length'] extends 0?
      -1:
      U['length'] extends 0?
        1:
        [
          T,U
        ] extends [
          [any,...infer TR extends any[]],
          [any,...infer UR extends any[]]
        ]?
          CompareArrayLength<TR,UR>:never
```
