### ISSUE TITLE
Some PR merge failed

### ISSUE THREAD

**Issue by pandanoir** [type-challenges/type-challenges#343]
- https://github.com/type-challenges/type-challenges/commit/874bbebb6f8439e0d6d7ee925733ef6b8b95f300
- https://github.com/type-challenges/type-challenges/commit/8dfedf1b72940ea17b8a56a9caeb648470979e0b
- https://github.com/type-challenges/type-challenges/commit/3bbd1ac22a243ee2f18f11828b14cc9ef49a2384

These PR aren't merged into master branch on this repo.

**Comment by antfu** [comment]
Oh, there is a conflict with GitHub actions. I have brought them back and thanks a lot for catching them!
