### ISSUE TITLE
New Challenge: Construct Tuple by Length

### ISSUE THREAD

**Issue by keepmhwn** [type-challenges/type-challenges#34979]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Similar to medium-7544-construct-tuple, but this new challenge helps you create a tuple of length N with a desired type.

You can define tuples of the same type of length N at once.

```yaml
difficulty: medium
title: Construct Tuple By Length
tags: tuple, conditional type
related: 7544
```

## Question

Given a generic type `T` and a generic number type `Length extends number`, returns a tuple of type `T` with a length of `Length`.

```ts
type result = ConstructTupleByLength<number, 2>; // [number, number]
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type ConstructTupleByLength<T, Length extends number> = any;
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<ConstructTupleByLength<unknown, 0>, []>>,
  Expect<Equal<ConstructTupleByLength<number | string, 2>, [number | string, number | string]>>,
]
```

**Comment by jiangshanmeta** [comment]
Hi @keepmhwn   thanks for your proposal. 
In my opinion, it's too similar to  medium-7544-construct-tuple. The only difference is we can have specific type rather than only unknown type. 
I don't think  it's necessary to have a separate challange. 

Maybe you can contribute to medium-7544-construct-tuple and take this challange as a "Level Up".
