### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by thomcleary** [type-challenges/type-challenges#35045]
## Info

```yaml
difficulty: medium
title: Longest Common Prefix
# tags: array, string, template-literal
```

### Longest Common Prefix

Write a type, `LongestCommonPrefix` that returns the longest common prefix string amongst a tuple of strings.

If there is no common prefix, return an empty string `""`.

```ts
type Common = LongestCommonPrefix<["flower", "flow", "flight"]>
//   ?^ "fl"

type Uncommon = LongestCommonPrefix<["dog", "racecar", "race"]>
//   ?^ ""
```
Inspired by [LeetCode 14. Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/description/)

## Template

```ts
type LongestCommonPrefix<T extends string[], P extends string = ""> = any
```

## Test Cases

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<LongestCommonPrefix<["flower", "flow", "flight"]>, "fl">>,
  Expect<Equal<LongestCommonPrefix<["dog", "racecar", "race"]>, "">>,
  Expect<Equal<LongestCommonPrefix<["", "", ""]>, "">>,
  Expect<Equal<LongestCommonPrefix<["a", "", ""]>, "">>,
  Expect<Equal<LongestCommonPrefix<["", "a", ""]>, "">>,
  Expect<Equal<LongestCommonPrefix<["", "", "a"]>, "">>,
  Expect<Equal<LongestCommonPrefix<["a", "a", ""]>, "">>,
  Expect<Equal<LongestCommonPrefix<["a", "", "a"]>, "">>,
  Expect<Equal<LongestCommonPrefix<["", "a", "a"]>, "">>,
  Expect<Equal<LongestCommonPrefix<["a", "a", "a"]>, "a">>,
  Expect<Equal<LongestCommonPrefix<["abc", "abcd", "abcde"]>, "abc">>,
  Expect<Equal<LongestCommonPrefix<[" ", " ", " "]>, " ">>,
  Expect<Equal<LongestCommonPrefix<["type-challenges", "type-hero", "typescript"]>, "type">>
]
```

**Comment by thomcleary** [comment]
[My solution](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nAogRwK4CGANgDTYAeqAxvAL5wBmUEIcA5AAJKoC0VAFsSIoAdgHMUAZwD0eGMCKS2AKGXc0AGQjipMAMIsQ2gApQUDYOQA8AFTgpyMUQBNJcSTCjBxAbQC6ZMb2ji5uHl7icAC8cABEsQB80XB2Dk4irnA+3gwoUHAAYsBQHsHpmeHeYmQAdHVwOXlwAEq6ZaHunlX+fnDKcHAA-IXFpWkd8X0DA8PG-dMAXHAAEigEzlatHj4ieCAARnl+SeMZbqvrVkUlMAnz00NwWjoeBiBGIqbmllY+NgQKK6jW61Or-BSSTa6BIBOAAAwAJOhjLQkRcNtcPAlaHC7g8Bks5gS4HM1Mg0OirABldpnToRMRJGI006ZRHoRr5dGo9CVcQ4x7ouBLeIAbjJqBSAKI1NpFS64iZcBZITp7M5KzWzh5GvBRAFwz1wrisXFErQeshKvKYQVYn8ZAAsgQwKhnHLbQz-Ml-ErrR1siJcvlMfBWZ6qqCahqtmHVfKvX5evNDdLIbGyD46jVna6UM4yHqgTcYXjjbm3ap1HAqARJFIffMsJQUDQrLhCDLnhJXoYTGYLNYfLEGEQIAB3PKxMgjsfj6dxUfAMT8GCxY4z0eJBIkJsttsd4hWbu6N4fL6D36xZwQMQL2JQAhUVsEKD3x-P9c7k0JHd76gwO2+BHievbvP23xDvEM73l+MG-ruAzNgBQGdse2g9vofafAOPzDgQsEwRuP5-kh+6AYeXYYae2EXnh0FxARRHfvECH-q2FHAVRLxYeBOGQVehGMXBJGIRQKGUehPFnhBl74feTEmsRrGkeJHGoSB1FgeeuFQYpDGxARynbmJyHqZJoG8TpAnDgpdnGWxZESVxUmYTJ-FyYZdkzkZLEEY5akHi5lnuXRen7FQCkRc4UVUM4KAiYZEUmexQVoSFtG6VecQzjlcRxMpcQBWZaWadJmU2bE6h8IIRDCC897VfweQQI15KSFQXhgGuynqNuyh+EAA)

**Comment by alexandroppolus** [comment]
Hi! I propose a more universal generic for union of string literals:
`LongestCommonPrefix<"flower" | "flow" | "flight"> = "fl"`

Using this for tuple: `LongestCommonPrefix<MyTuple[number]>`
