### ISSUE TITLE
Running locally?

### ISSUE THREAD

**Issue by jackmac92** [type-challenges/type-challenges#383]
Is it possible to test solutions locally? Or do you need to use the `Take the Challenge` link?

**Comment by antfu** [comment]
We do not have a local workflow at this moment yet, you might need to do some tweak and setup in order to run and test on local env. If anyone came up with any ideas to have a "local playground", please let me know and we might be able to ship it. Thanks.

**Comment by carleryd** [comment]
If you've got an editor with TS, you can just go to an exercise, such as number 14:

	 14-easy-first
			  README.ja.md
			  README.md
			  README.zh-CN.md
			  info.yml
			  info.zh-CN.yml
			  template.ts
			  test-cases.ts

and put "template.ts" and "test-cases.ts" side by side in your editor and hover the "cases" in "test-cases.ts" to see whether or not the tests pass. You should expect an array of `false` before you begin, and once it's an array of only `true` then you know you've passed!

**Comment by BlairCurrey** [comment]
I found this issue when looking for a way to access the quizzes locally in my IDE as well. I have been copy-pasting which is obviously tedious over the long haul. I just use my IDE to complete them - correctness verified by the IDE's type checking, or you can just compile it. 

With this in mind, I decided to add a build script that builds the quizzes and saves them locally (same content that is populated in typescriptlanguage.org IDE). I opened a PR for it here in case this is a direction people are interested in: https://github.com/type-challenges/type-challenges/pull/21274
