### ISSUE TITLE
RequireOnlyOne

### ISSUE THREAD

**Issue by ali-master** [type-challenges/type-challenges#4256]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: Require Only One
#tags: utils
```

## Question

Implement the advanced util type RequireOnlyOne<T>, which requires only one key in the object.

For example:
```ts
interface Relation {
  a?: string;
  b?: string;
  c?: number,
}
RequireOnlyOne<Relation, "a"> // expected {a: string, b?: string, c?: string}
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type RequireOnlyOne<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<RequireOnlyOne<{a?: string, b?: string}, "a">, {a: string, b?: string}>>,
  Expect<Equal<RequireOnlyOne<{a?: string, b?: string, c: string}, "c">, {a?: string, b?: string, c: string}>>,
]
```

**Comment by jiangshanmeta** [comment]
This question looks like [RequiredByKeys](https://github.com/type-challenges/type-challenges/blob/master/questions/2759-medium-requiredbykeys/README.md).
