### ISSUE TITLE
PartialOnlyOne

### ISSUE THREAD

**Issue by ali-master** [type-challenges/type-challenges#4258]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: Partial Only One
#tags: utils
```

## Question

Implement the advanced util type PartialOnlyOne<T>, which makes one property in T optional.

For example:
```ts
interface Relation {
  a: string;
  b: string;
  c: number,
}
PartialOnlyOne<Relation, "a"> // expected {a?: string, b: string, c: string}
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type PartialOnlyOne<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<PartialOnlyOne<{a: string, b: string}, "a">, {a?: string, b: string}>>,
  Expect<Equal<PartialOnlyOne<{a: string, b: string, c?: string}, "a">, {a?: string, b: string, c?: string}>>,
  Expect<Equal<PartialOnlyOne<{a: string, b: string, c: string}, "c">, {a: string, b: string, c?: string}>>,
]
```

**Comment by antfu** [comment]
Maybe we could name is as `PartialPick` and support unions like `PartialPick<Obj, 'a' | 'b'>`. Also I would think this might better fit as `easy` of `medium` - https://github.com/type-challenges/type-challenges/blob/master/questions/4-easy-pick/README.md

**Comment by jiangshanmeta** [comment]
This question remind me of [PartialByKeys](https://github.com/type-challenges/type-challenges/blob/master/questions/2757-medium-partialbykeys/README.md).

**Comment by antfu** [comment]
Oh yeah, then it's duplicated I think. Thanks for your contribution.
