### ISSUE TITLE
Greater Than

### ISSUE THREAD

**Issue by ch3cknull** [type-challenges/type-challenges#4425]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Greater Than
tags: array
```

## Question

In This Challenge, You should implement a type `GreaterThan<T, U>` like `T > U`

Negative numbers do not need to be considered.

For example

```ts
GreaterThan<2, 1> //should be true
GreaterThan<1, 1> //should be false
```

Good Luck!

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type GreaterThan<T extends number, U extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<GreaterThan<1, 0>, true>>,
  Expect<Equal<GreaterThan<5, 4>, true>>,
  Expect<Equal<GreaterThan<0, 0>, false>>,
  Expect<Equal<GreaterThan<20, 20>, false>>
]
```

**Comment by jiangshanmeta** [comment]
This question looks like a easier version of [Integers Comparator](https://github.com/type-challenges/type-challenges/blob/master/questions/274-extreme-integers-comparator/README.md) as it does't need to consider negative number

**Comment by RThong** [comment]
应该添加一些不同长度数字对比的测试用例

**Comment by ch3cknull** [comment]
> 应该添加一些不同长度数字对比的测试用例

pull request welcome, you can add some test case
