### ISSUE TITLE
110 - Capitalize

### ISSUE THREAD

**Issue by yifanwww** [type-challenges/type-challenges#4552]
I really want to write this XD
```ts
type Capitalize<S extends string> = intrinsic;
```

But yeah I should implement it by myself, without using `intrinsic`

So what about this? XD
```ts
type Capitalize<S extends string> = S extends `${infer T}${infer U}` ? `${Uppercase<T>}${U}` : S;
```

Well... actually built-in `Uppercase` also uses `intrinsic`, this answer is literally using `intrinsic` indirectly.

So may this?

```ts
interface UppercaseMap {
  a: 'A';
  b: 'B';
  c: 'C';
  d: 'D';
  e: 'E';
  f: 'F';
  g: 'G';
  h: 'H';
  i: 'I';
  j: 'J';
  k: 'K';
  l: 'L';
  m: 'M';
  n: 'N';
  o: 'O';
  p: 'P';
  q: 'Q';
  r: 'R';
  s: 'S';
  t: 'T';
  u: 'U';
  v: 'V';
  w: 'W';
  x: 'X';
  y: 'Y';
  z: 'Z';
}

type Capitalize<S extends string> = S extends `${infer T}${infer U}`
  ? T extends keyof UppercaseMap
    ? `${UppercaseMap[T]}${U}`
    : S
  : S;
```

**Comment by Jayce-liang** [comment]
wtf

**Comment by Jayce-liang** [comment]
> I really want to write this XD我真的很想写这个XD
> 
> ```ts
> type Capitalize<S extends string> = intrinsic;
> ```
> 
> But yeah I should implement it by myself, without using 但是，是的，我应该自己实现它，而不使用`intrinsic`
> 
> So what about this? XD那么这个呢？ XD
> 
> ```ts
> type Capitalize<S extends string> = S extends `${infer T}${infer U}` ? `${Uppercase<T>}${U}` : S;
> ```
> 
> Well... actually built-in `Uppercase` also uses `intrinsic`, this answer is literally using `intrinsic` indirectly.嗯...实际上内置的`Uppercase`也使用`intrinsic` ，这个答案实际上是间接使用`intrinsic` 。
> 
> So may this? 那么这可以吗？
> 
> ```ts
> interface UppercaseMap {
>   a: 'A';
>   b: 'B';
>   c: 'C';
>   d: 'D';
>   e: 'E';
>   f: 'F';
>   g: 'G';
>   h: 'H';
>   i: 'I';
>   j: 'J';
>   k: 'K';
>   l: 'L';
>   m: 'M';
>   n: 'N';
>   o: 'O';
>   p: 'P';
>   q: 'Q';
>   r: 'R';
>   s: 'S';
>   t: 'T';
>   u: 'U';
>   v: 'V';
>   w: 'W';
>   x: 'X';
>   y: 'Y';
>   z: 'Z';
> }
> 
> type Capitalize<S extends string> = S extends `${infer T}${infer U}`
>   ? T extends keyof UppercaseMap
>     ? `${UppercaseMap[T]}${U}`
>     : S
>   : S;
> ```

so good
