### ISSUE TITLE
TrimRight

### ISSUE THREAD

**Issue by Talljack** [type-challenges/type-challenges#4803]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Trim Right
#tags: template-literal
```

## Question

Implement `TrimRight<T>` which takes an exact string type and returns a new string with the whitespace ending removed.

For example:

```ts
type Trimed = TrimRight<'   Hello World    '> // expected to be '   Hello World'
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type TrimRight<S extends string> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<TrimRight<'str'>, 'str'>>,
  Expect<Equal<TrimRight<'str '>, 'str'>>,
  Expect<Equal<TrimRight<'str     '>, 'str'>>,
  Expect<Equal<TrimRight<'     str     '>, '     str'>>,
  Expect<Equal<TrimRight<'   foo bar  \n\t '>, '   foo bar'>>,
]
```

**Comment by jiangshanmeta** [comment]
remove ```#``` before tags if you want to add a tag
