### ISSUE TITLE
898 - Includes

### ISSUE THREAD

**Issue by curly210102** [type-challenges/type-challenges#4961]
```ts
// your answers
type IsEqual<T, U> =
	(<G>() => (G extends T ? 1 : 2)) extends
	(<G>() => (G extends U ? 1 : 2))
		? true
		: false;

type Includes<T extends any[], U> = T extends [infer L, ...infer R] ? IsEqual<L, U> extends true ? true : Includes<R, U> : false;
```

Related knowledge points
> When the type on the left of the extends **is assignable to** the one on the right, then you’ll get the type in the first branch (the “true” branch); otherwise you’ll get the type in the latter branch (the “false” branch).

https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

The most difficult part is to judge whether type `isEqual`.

**Comment by PigMerit** [comment]
wqe
