### ISSUE TITLE
Without

### ISSUE THREAD

**Issue by Pineapple0919** [type-challenges/type-challenges#5117]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Without
tags: union, array
```

## Question

Implement the type version of Lodash.without, Without<T, U> takes an Array T, number or array U and returns an Array without the elements of U.

```ts
type Res = Without<[1, 2], 1>; // excepted to be [2]
type Res1 = Without<[1, 2, 4, 1, 5], [1, 2]>; // excepted to be [4, 5]
type Res2 = Without<[2, 3, 2, 3, 2, 3, 2, 3], [2, 3]>; // excepted to be []
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Without<T, U> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Without<[1, 2], 1>, [2]>>,
  Expect<Equal<Without<[1, 2, 4, 1, 5], [1, 2]>, [4, 5]>>,
  Expect<Equal<Without<[2, 3, 2, 3, 2, 3, 2, 3], [2, 3]>, []>>
]
```

**Comment by jiangshanmeta** [comment]
Good question.
Personally, I suggest changing the name to ```Without```, to follow without method in ```lodash```, which also remove some value in an array.

**Comment by Pineapple0919** [comment]
> 

Good suggestion! I will take it.

**Comment by Pineapple0919** [comment]
> Good question. Personally, I suggest changing the name to `Without`, to follow without method in `lodash`, which also remove some value in an array.

Good suggestion! I will take it.
