### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by joonseolee** [type-challenges/type-challenges#5238]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: easy
title: Prefix
#tags: string
```

## Question

`Prefix<T>` is to check whether the sentence has  a prefix string.

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Prefix<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Prefix<'api', ''>, false>>,
  Expect<Equal<Prefix<'api', 'foo'>, false>>,
  Expect<Equal<Prefix<'api', 'foo/api'>, false>>,
  Expect<Equal<Prefix<'api', 'api/foo'>, true>>,
  Expect<Equal<Prefix<'api', 'apifoo'>, true>>,
]

```

**Comment by antfu** [comment]
Thanks, but we already have this https://github.com/type-challenges/type-challenges/tree/1d6099780a2a03bb0e0512cd982b6f45dec4d1c4/questions/2688-medium-startswith
