### ISSUE TITLE
Generic way to map strings to numbers

### ISSUE THREAD

**Issue by jpribyl** [type-challenges/type-challenges#5298]
What I am looking for is some generic type `NumberFromString` such that:
```ts
type numberFromString = NumberFromString<'200'> // 200

// and
type testCase = ExpectExtends<number, NumberFromString<'200'>> // true
```

For more context, I wish to do this because I am looking to use a combination of `django-js-reverse` and `openapi-typescript` to autogenerate frontend typings for api responses.

One alternative would be use `patch-package` in order to force `openapi-typescript` to return string keys.. but this seems like an interesting exercise

[playground](https://www.typescriptlang.org/play?#code/PTAEEEFcBcHsHMCmA7RAnAhtRATUAjAT1FgAcUNSBLAWmkPIGcBjNK06AKCuWzQDMMzRKFJYAFo1ABvTqFAByYJSrAUOUrB7Rg0qjgC+wBQC4ZoJNDNl0WKrGSMA2gpUB9SwoC6oAwG5OA05uXnRBYVBmWABbTVReKVl5FnFEaIxGMyT5UABZQgARACFc2BxEABss0H0zZEho-HQ-EmhUtDceflgzRmg2ZHhfAJzQAGVoLEhGACVERjjGRGq+qczQPoGh-zlhwODtMKERG0xoe0cZXfdLLN35MUxoxD516VEJatqN-p5tvdGaHmi3md1G8gATAAGKFg8HyKKhXjVVykUgVKjMOwOYAAK0YDlMkRicRQ0GcChSaQy3hc+WKpXKFW8APBO3uOQALDC4fDEdhkVd4aNUejMdjkHiCcgiVFYg4yRSqelGLSFBM1nMFg4lt4RsKdvDDTljTsgpwQKAAJKgDDRUAVWCwADWf1A3TQttAAHcMMQ4KAcLBQG0qFJvVQ2rAYKBULg3RgfltQDQAHyxhpNT3pNFu+jkTj5kQa6DTADCZXmoAAvELFNCoUSG-qFNzG2Y2wF2UXQAVEIhSABVZAXAA8ABUADSgAAK6drM9AiAAHgKcFJnYhCLB+KBx7sAPx7pwzry7MyLldrqQAAwAJHpkPx0LOAIwGAB0D66L5nEIMN6Hm+S6ruoG5bjue4ckefYDsOY7jier5eNOf6phyF6viB16gJu267iW5aVlIloEjUjjYBgeCQaGjAfvRH4bDELziG6GKbqAABymboAAYmgMQTFso4zq+6ZXmBuEQbu+6jDB-ZDiODijrBikIdOhGMBW5TOKJXipqhELppaGDIHgbQoKA7QiKp8HKYh3GNHxAnREJfwiWJKGzkZGGxogABu6DnrO2GSXhkGadp8xAbZSnIBOGmTKWWnESe+nBaggVoAEhYMCIdnIOOsC8ZAyDMBO857qFZlSKZxBHgAFMuZjjgAlDW6ZQqAdQBc0uXkKABVFVaoRoEszDQBVNaDXFRUlWVU0STVoBNWYP6ela7XVp1oBHjaPVZQEPaqTOmLOglIVLeuSZ-JVQ2wCNryIBNKkKQVF1zqmOU9kC2qOCItYnWdo6gJa7zfJsfzTrAFkdF0PQ3YMvi7GIbQUso1BqGZmjaLo+hGN4k67Aolgfr9IJ0Q2H78mSH6UGKWLnDi+KEpwqZAA)

----

Edit: just found this [string to number challenge](https://github.com/type-challenges/type-challenges/tree/master/questions/300-hard-string-to-number)

**Comment by jpribyl** [comment]
cc @razh bc I know you've thought about this use case before

**Comment by razh** [comment]
Hey Johnny, hope things are going well in your new role! 💪 

The `StatusCodes` type might be the most straightforward way to do this? All of the solutions involve some level of recursion that blows up rather quickly!

https://github.com/type-challenges/type-challenges/issues?q=is%3Aissue+label%3A300+

We also have an `OkJSONResponse` type that extracts the specific response type:

```tsx
export type OkJSONResponse<T extends keyof paths> =
  paths[T]['get']['responses'] extends {
    200: { content: { 'application/json': unknown } };
  }
    ? paths[T]['get']['responses'][200]['content']['application/json']
    : never;

type response = OkJSONResponse<'/api/endpoint/{id}/'>
```

**Comment by jpribyl** [comment]
Hey! Yeah things are going well so far, super fast paced and people are excited so can't go wrong there :ringed_planet: 

Yeah, I guess using `StatusCodes` also has the benefit of guarding against "illegal" status numbers

I think patching the package would be relatively straightforward as well since it [used to have string keys](https://github.com/drwpow/openapi-typescript/pull/381/files)

Kind of an interesting thing since JS will let you use a string to access a numeric key:
![image](https://user-images.githubusercontent.com/27659352/146831363-27974ee0-7a48-4694-b9a9-954a3b737d7a.png)

I'll have to do some mulling over the cleanest implementation here! I do like the simplicity of that `OkJSONResponse` type :smile:

**Comment by razh** [comment]
I almost forgot to mention, credit for the `OkJSONResponse` type, along with our improved API typings, goes to @maciejmyslinski 🙌

**Comment by jpribyl** [comment]
Nice! I was guessing as much :laughing: I actually meant to mention- I wound up able to pull the params typing as well with something like
```tsx
type Query<TUrl extends string> = DeepPick<
  DeepPick<ApiPaths, TUrl>,
  'get.parameters.query'
>;

export default function useGetQuery<TUrl extends string = string>(
  url: TUrl,
  query?: Query<TUrl>,
) {
  // ...
}
```

Or in the format above:

```tsx
export type Query<T extends keyof paths> =
  paths[T]['get']['parameters']['query']

export default function useGetQuery<TUrl extends keyof paths>(
  url: TUrl,
  query?: Query<TUrl>,
) {
  // ...
}
```

Only problem... now I'm shinng a light on all of the mistyped / overlooked api responses :facepalm:

**Comment by maciejmyslinski** [comment]
Hey folks, this thread made my ~~day~~ week. Thank you 😭 

TBH I don't watch many programming related youtube videos these days. I'm not up to date with what channel is worth subscribing to, so thank you for the recommendation, @jpribyl 🙇
