### ISSUE TITLE
5310 - Join

### ISSUE THREAD

**Issue by ch3cknull** [type-challenges/type-challenges#5334]
```ts
type Concat<L, M extends string, R> = `${L & string}${M}${R & string}`

type Join<T extends any[], U extends number|string> = T extends [infer L, ...infer R]
? T['length'] extends 1
  ? `${T[0]}`
  : Concat<L, `${U}`, Join<R, U>>
: ''
```

**Comment by YangLG-7** [comment]
hi~  Could you help me solve this question

If I make`T` to be `string []` like ` type Join<T extends string[], U extends number|string>`

```
type Join<
  T extends string[],---> I define T as string []
  U extends number | string,
  S extends string = ""
> = T extends [infer F, ...infer R]
  ? R["length"] extends 0
    ? `${S}${string & F}`
    : Join<R, U, `${S}${string & F}${U}`>  --->  Type 'unknown[]' is not assignable to type 'string[]
  : S;
```

Why do TS  think R is `unknown []`

**Comment by ch3cknull** [comment]
> hi~ Could you help me solve this question
> 
> If I make`T` to be `string []` like ` type Join<T extends string[], U extends number|string>`
> 
> ```
> type Join<
>   T extends string[],---> I define T as string []
>   U extends number | string,
>   S extends string = ""
> > = T extends [infer F, ...infer R]
>   ? R["length"] extends 0
>     ? `${S}${string & F}`
>     : Join<R, U, `${S}${string & F}${U}`>  --->  Type 'unknown[]' is not assignable to type 'string[]
>   : S;
> ```
> 
> Why do TS think R is `unknown []`

Seems I have same problem before. **Might you should told typescript like this:**
```ts
type Join<
  T extends string[],
  U extends number | string,
  S extends string = ""
> = T extends [infer F, ...infer R]
  ? R["length"] extends 0
    ? `${S}${string & F}`
    // tell TypeScript it a string[]
    : R extends string[]
      ? Join<R, U, `${S}${string & F}${U}`>
      : never
  : S;
```
Or you can **escape it by use `any[]`**, like this:

```ts

type Join<
  T extends any[],
  U extends number | string,
  S extends string = ""
> = T extends [infer F, ...infer R]
  ? R["length"] extends 0
    ? `${S}${string & F}`
    : Join<R, U, `${S}${string & F}${U}`>
  : S;
```

Hope that my answer can help you. Have a good time!

**Comment by YangLG-7** [comment]
I appreciate your reply, which is very helpful to me

I'm curious why ts can't infer that `R` is  a `string []` if this conditional statement `R extends string[]`    is not added in front。Is it because there are some edge case  that we haven't taken into account
