### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by Pineapple0919** [type-challenges/type-challenges#5340]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: Split
tags: array
```

## Question

Implement the type version of String.split, Split<T, U> takes an String T, string U and returns the Array T array that is separated by U.

```ts
type Res = Split<"p-i-n-e", "-">; // expected to be ['p', 'i', 'n', 'e']
type Res1 = Split<"happy coding", "-">; // expected to be ['happy coding']
type Res2 = Split<"apple">; // expected to be ['a', 'p', 'p', 'l', 'e']
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Split<T, U> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Split<"p-i-n-e", "-">, ["p", "i", "n", "e"]>>,
  Expect<Equal<Split<"happy coding", "-">, ["happy coding"]>>,
  Expect<Equal<Split<"apple">, ["a", "p", "p", "l", "e"]>>
]
```

**Comment by ch3cknull** [comment]
Looks Same as 2822 Split
https://github.com/type-challenges/type-challenges/blob/master/questions/2822-hard-split/README.md
