### ISSUE TITLE
KebabCase

### ISSUE THREAD

**Issue by johnsoncodehk** [type-challenges/type-challenges#612]
## Info

Related: https://github.com/vuejs/rfcs/discussions/248

```yaml
difficulty: medium
title: KebabCase
tags: template-literal
```

## Question

`FooBarBaz` -> `for-bar-baz`

## Template

```ts
type KebabCase<S> = any;
```

## Test Cases

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<KebabCase<'FooBarBaz'>, 'foo-bar-baz'>>,
  Expect<Equal<KebabCase<'fooBarBaz'>, 'foo-bar-baz'>>,
  Expect<Equal<KebabCase<'foo-bar'>, 'foo-bar'>>,
  Expect<Equal<KebabCase<'foo_bar'>, 'foo_bar'>>,
  Expect<Equal<KebabCase<'Foo-Bar'>, 'foo--bar'>>,
  Expect<Equal<KebabCase<'ABC'>, 'a-b-c'>>,
  Expect<Equal<KebabCase<'-'>, '-'>>,
  Expect<Equal<KebabCase<''>, ''>>,
  Expect<Equal<KebabCase<'😎'>, '😎'>>,
]
```

**Comment by antfu** [comment]
Can you add several more test cases or descriptions of the expecting inputs to make the challenge more clear? Something like what we expected to see the output of: 

```ts
KebabCase<'fooBarBax'> 
KebabCase<'foo-bar'>
KebabCase<'Foo-Bar'>
KebabCase<'ABC'>
KebabCase<'-'>
KebabCase<''>
KebabCase<'😎'>
```

**Comment by johnsoncodehk** [comment]
done. simply put,
KebabCase: make first char lower case, and replace all capital cases to `-` + lower case.
CamelCase: replace all `-` + lower case to capital case.

**Comment by johnsoncodehk** [comment]
maybe change title to `SimilarCamelCase` and `SimilarKebabCase ` will be better? because this is not equal to normal transform functions.

**Comment by antfu** [comment]
Thanks! I think `KebabCase` and `CamelCase` are good enough and sure I don't think we need to handle all the edge cases.

**Comment by johnsoncodehk** [comment]
@antfu please add this test case: `Expect<Equal<CamelCase<'foo----------bar'>, 'foo---------Bar'>>`, see: https://github.com/type-challenges/type-challenges/issues/615

**Comment by antfu** [comment]
Just open a pr for it 😉
