### ISSUE TITLE
9 - Deep Readonly

### ISSUE THREAD

**Issue by julienandreu** [type-challenges/type-challenges#6686]
```ts
type DeepReadonly<T extends {}> = {
  readonly [K in keyof T]: T[K] extends {[key: string]: unknown}
    ? DeepReadonly<T[K]>
    : T[K];
};
```

**Comment by arpitBhalla** [comment]
@julienandreu 
Can we use `any` instead of `unkown`?

**Comment by julienandreu** [comment]
Yes but by using unknown, you're reflecting that you're not aware on the values type.

If you're using any, that could be converted in any type, so in strict mode for example, you'll face error or warning.
