### ISSUE TITLE
533 - Concat

### ISSUE THREAD

**Issue by HChengH** [type-challenges/type-challenges#7184]
```ts
// 你的答案
type Concat<T extends any[], U extends any[]> =[...T, ...U];
```

**Comment by sv-98-maxin** [comment]
这个例子会报错
  Expect<Equal<Concat<typeof tuple, typeof tuple>, [1, 1]>>,
这个答案可以避免
```ts
type Concat<T extends readonly any[], U extends readonly any []> = [...T, ...U]
```

**Comment by DefterYu** [comment]
```
//  处理异常情况
type Empt = null | undefined;

type Concat<
    T extends (readonly any[] | Empt),
    U extends (readonly any[] | Empt)
> = T extends readonly any[]
    ? U extends readonly any[]
        ? [...T, ...U]
        : never
    : never;
```

1. `T extends readonly any[]`可以接受`readonly any[]`和`any[]`两种类型
2. `Empt`用于处理特殊情况

**Comment by shaobeichen** [comment]
type Concat<T extends readonly any[], U extends readonly any[]> = [...T, ...U]

**Comment by 15200596294git** [comment]
类型约束加个readonly好像行了
`
type Concat<T extends readonly any[], U extends readonly any[]> = [...T,...U]
`

**Comment by star176** [comment]
不太理解为什么readonly Array<any>会报错，readonly any[]不会，这两个有什么本质区别吗

**Comment by TheShining** [comment]
> 不太理解为什么readonly Array 会报错，readonly any[] 不会，这两个有什么本质区别吗

ReadonlyArray 用这个readonly 修饰符不能直接应用于泛型类型

**Comment by wzjiscode** [comment]
> 不太理解为什么readonly Array 会报错，readonly any[] 不会，这两个有什么本质区别吗

“readonly”类型修饰符仅允许用于数组和元组的字面量类型。
