### ISSUE TITLE
189 - Awaited

### ISSUE THREAD

**Issue by Wuzh994** [type-challenges/type-challenges#7219]
```ts
// 你的答案
type MyAwaited<T extends Promise<any>> = T extends Promise<infer U>
  ? U extends Promise<any>
    ? MyAwaited<U>
    : U
  : never;
```

**Comment by PAVANT009** [comment]
You are expecting a promise here ->  Expect<Equal<MyAwaited<T>, number>>,
but in last test 

``  Expect<Equal<MyAwaited<T>, number>>,
type T = { then: (onfulfilled: (arg: number) => any) => any }
``

its not a promise you have to use this 

``T extends { then: (onfulfilled: (arg: infer V) => any) => any }``
am i missing something?
