### ISSUE TITLE
Object KeyPaths

### ISSUE THREAD

**Issue by ChenKS12138** [type-challenges/type-challenges#7258]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: Object Key Paths
tags: object-keys
```

## Question

Get all possible paths that could be called by [_.get](https://lodash.com/docs/4.17.15#get) (a lodash function) to get the value of an object

```typescript
type T1 = ObjectKeyPaths<{ name: string; age: number }>; // expected to be 'name' | 'age'
type T2 = ObjectKeyPaths<{
  refCount: number;
  person: { name: string; age: number };
}>; // expected to be 'refCount' | 'person' | 'person.name' | 'person.age'
type T3 = ObjectKeyPaths<{ books: [{ name: string; price: number }] }>; // expected to be the superset of 'books' | 'books.0' | 'books[0]' | 'books.[0]' | 'books.0.name' | 'books.0.price' | 'books.length' | 'books.find'
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type ObjectKeyPaths<T extends object> = any;
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectExtends } from "@type-challenges/utils";

const ref = {
  count: 1,
  person: {
    name: "cattchen",
    age: 22,
    books: ["book1", "book2"],
    pets: [
      {
        type: "cat",
      },
    ],
  },
};

type cases = [
  Expect<Equal<ObjectKeyPaths<{ name: string; age: number }>, "name" | "age">>,
  Expect<
    Equal<
      ObjectKeyPaths<{
        refCount: number;
        person: { name: string; age: number };
      }>,
      "refCount" | "person" | "person.name" | "person.age"
    >
  >,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "count">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.name">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.age">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.books">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.pets">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.books.0">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.books.1">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.books[0]">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.books.[0]">>,
  Expect<ExpectExtends<ObjectKeyPaths<typeof ref>, "person.pets.0.type">>,
  Expect<Equal<ExpectExtends<ObjectKeyPaths<typeof ref>, "notExist">, false>>
];

```

**Comment by ChenKS12138** [comment]
My answer.

```typescript
type ObjectKeyPaths<
  T extends object,
  NotFirst extends boolean = false,
  K extends keyof T = keyof T
> = K extends string
  ?
      | (NotFirst extends true ? `.${K}` : `${K}`)
      | (T[K] extends object
          ? `${NotFirst extends true ? `.${K}` : `${K}`}${ObjectKeyPaths<
              T[K],
              true
            >}`
          : never)
  : K extends number
  ?
      | (NotFirst extends true ? `.${K}` | `[${K}]` | `.[${K}]` : `${K}`)
      | (T[K] extends object
          ? `${NotFirst extends true
              ? `.${K}` | `[${K}]` | `.[${K}]`
              : `${K}`}${ObjectKeyPaths<T[K], true>}`
          : never)
  : never;
```

**Comment by mauroerta** [comment]
I wrote an article about it yesterday, the hardest thing is to make the type Tail Recursive, here there is a detailed explanation:
https://javascript.plainenglish.io/advanced-typescript-type-level-nested-object-paths-7f3d8901f29a

A simple solution could be the following:
```typescript
export type NestedPaths<
  T extends GenericObject,
> = {
  [K in keyof T]: T[K] extends GenericObject
    ? K | `${K}.${NestedPaths<T[K]>}`
    : K
}[keyof T];
```
But is not tail-recursive, my proposal is the following one:
```typescript
type Primitive = string | number | symbol;

type GenericObject = Record<Primitive, unknown>;

type Join<
  L extends Primitive | undefined,
  R extends Primitive | undefined,
> = L extends string | number
  ? R extends string | number
    ? `${L}.${R}`
    : L
  : R extends string | number
  ? R
  : undefined;
type Union<
  L extends unknown | undefined,
  R extends unknown | undefined,
> = L extends undefined
  ? R extends undefined
    ? undefined
    : R
  : R extends undefined
  ? L
  : L | R;
/**
 * NestedPaths
 * Get all the possible paths of an object
 * @example
 * type Keys = NestedPaths<{ a: { b: { c: string } }>
 * // 'a' | 'a.b' | 'a.b.c'
 */
export type NestedPaths<
  T extends GenericObject,
  Prev extends Primitive | undefined = undefined,
  Path extends Primitive | undefined = undefined,
> = {
  [K in keyof T]: T[K] extends GenericObject
    ? NestedPaths<T[K], Union<Prev, Path>, Join<Path, K>>
    : Union<Union<Prev, Path>, Join<Path, K>>;
}[keyof T];
```

**Comment by ChenKS12138** [comment]
@antfu It seems that `7258-medium-objectkeypaths` and `7258-hard-object-key-paths` are both exist, there could be some bugs in the current workflow. `7258-medium-objectkeypaths` needs to be removed.

https://github.com/type-challenges/type-challenges/blob/549eed542dcd430a66b3b63f32352f68dfb3f95e/questions/7258-medium-objectkeypaths/README.md
https://github.com/type-challenges/type-challenges/blob/549eed542dcd430a66b3b63f32352f68dfb3f95e/questions/7258-hard-object-key-paths/README.md

**Comment by fabien0102** [comment]
Just for sharing, I found how to solve this problem during the last TSConf on Anders Hejlsberg keynote: https://youtu.be/V5OnAN63vls?t=1471

https://www.typescriptlang.org/play?#code/C4TwDgpgBACghsAFgaQiAzgHgCoD4oC8AUFKVAPYBGAVhAMbBQQAewEAdgCbpTZQD8UdMABOAS3YBzKAC4SZPizZceIiHE7l2AGxBQ47EAG0AugKgBRViLgNMAazTkAZrwA0UAAYASAN7sAVwBbSggRAF9PfAAfKABlAMpUDBwPK1FbYAcnV2wPH39g0Iio-DkyXiZWDm4KGnpGQXSbO0cQF3chUQlJGPjE5Kw8y2tM7Pbcj2FxKVwy+VJ2CAA3MIBuIiJQSH6ktCGPZCrlWume-AIoI6UanjaOvkEC5HCAOj94JEGcI2QTXEisigS1WIg2W3A0BgInIYGwkNSsAQiGOty6M16hAWSKQqJUUHuuXM2CMn0QJnKZDJeNqBQkzjCVzefnpjIASoDBNdqvjCZVBNDYfDID8-h42WUoAF2PZ2OQAO7sSmkaWyhXscGcejaOBqKDOaUMMRaKCSCDAQVgREwGk8MnfPC4AAUVGoMk6YGR7pgAEpvTC4QjhjBcOC6FphFAgiAAPL1BiEKC+bHOcjkd0AIjg6J6Gbc2MouvdABYAEz5ipLYQQTju5MVCqp9NQDNgbSwvPYiqFkQl8tdsjaMTCd1GACMHnLUAAzGY4Dxw+xhBWG6QDOQkGEADJwEBhOsD1ftduZugGKDtAJQTRQMTAfgZw9QcLYl8voiLyPZy5mi0Bp3RnGtAMB4GZVmwnCvOum4iDue4iK8x7kBmPpQAA9GhUBIMOt48JkARwNouj6DmUhQIAvBuAIx7QA

**Comment by mauroerta** [comment]
> Just for sharing, I found how to solve this problem during the last TSConf on Anders Hejlsberg keynote: https://youtu.be/V5OnAN63vls?t=1471
> 
> https://www.typescriptlang.org/play?#code/C4TwDgpgBACghsAFgaQiAzgHgCoD4oC8AUFKVAPYBGAVhAMbBQQAewEAdgCbpTZQD8UdMABOAS3YBzKAC4SZPizZceIiHE7l2AGxBQ47EAG0AugKgBRViLgNMAazTkAZrwA0UAAYASAN7sAVwBbSggRAF9PfAAfKABlAMpUDBwPK1FbYAcnV2wPH39g0Iio-DkyXiZWDm4KGnpGQXSbO0cQF3chUQlJGPjE5Kw8y2tM7Pbcj2FxKVwy+VJ2CAA3MIBuIiJQSH6ktCGPZCrlWume-AIoI6UanjaOvkEC5HCAOj94JEGcI2QTXEisigS1WIg2W3A0BgInIYGwkNSsAQiGOty6M16hAWSKQqJUUHuuXM2CMn0QJnKZDJeNqBQkzjCVzefnpjIASoDBNdqvjCZVBNDYfDID8-h42WUoAF2PZ2OQAO7sSmkaWyhXscGcejaOBqKDOaUMMRaKCSCDAQVgREwGk8MnfPC4AAUVGoMk6YGR7pgAEpvTC4QjhjBcOC6FphFAgiAAPL1BiEKC+bHOcjkd0AIjg6J6Gbc2MouvdABYAEz5ipLYQQTju5MVCqp9NQDNgbSwvPYiqFkQl8tdsjaMTCd1GACMHnLUAAzGY4Dxw+xhBWG6QDOQkGEADJwEBhOsD1ftduZugGKDtAJQTRQMTAfgZw9QcLYl8voiLyPZy5mi0Bp3RnGtAMB4GZVmwnCvOum4iDue4iK8x7kBmPpQAA9GhUBIMOt48JkARwNouj6DmUhQIAvBuAIx7QA

Cool, thanks for sharing!
My only critique of his approach is that his type is not Tail Recursive, which means that technically if applied to really big and nested objects, will not work (more infos [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#tail-recursion-elimination-on-conditional-types))
