### ISSUE TITLE
4 - Pick

### ISSUE THREAD

**Issue by Oaphi** [type-challenges/type-challenges#744]
```ts
type MyPick<T, K> = { [ P in keyof T as P extends K ? P : never ] : T[P] };

type a = { a : 1, b : 2, c : 3 };
type b = MyPick<a, "a" | "c">; // { a : 1, c : 3 };
type c = MyPick<a, "a" | "d">; // { a : 1 }
```

With an introduction of the `as` [clause](https://github.com/microsoft/TypeScript/pull/40336), it is easy to map and filter a type in one go. The `{ [ k in K ] : T[k] }` solutions require the signature to be modified to constrain `K` to `keyof T`, which is not ideal. This solution avoids that by creating a mapped type with keys assignable to `K` and removes the leftover properties mapped to `never`.

The solution also works for `K` that do not satisfy the constraint `keyof T` by omitting them from the output.

**Comment by drzamich** [comment]
That's clever!
