### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by LoTwT** [type-challenges/type-challenges#7559]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium # medium / hard / extreme
title: Addition
tags: tuple # separate by comma
```

## Question

Implement the type Addition that is ` + ` in Javascript by using BuildTuple.

0 <= addend <= 999, limited by Typescript v4.6.2

It's a simple version of [ 476-Sum ](https://github.com/type-challenges/type-challenges/blob/master/questions/476-extreme-sum/README.md).

For example

```ts
Addition<10, 10> // expect to be 20
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Addition<A extends number, B extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Addition<0, 0>, 0>>,
  Expect<Equal<Addition<10, 10>, 20>>,
  Expect<Equal<Addition<999, 999>, 1998>>,
  // @ts-expect-error
  Expect<Equal<Addition<1000, 999>, 1999>>
]
```

**Comment by antfu** [comment]
Thanks but duplicated with https://github.com/type-challenges/type-challenges/blob/master/questions/476-extreme-sum/README.md
