### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by LoTwT** [type-challenges/type-challenges#7563]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium # medium / hard / extreme
title: Multiplication
tags: tuple # separate by comma
```

## Question

Implement the type Multiplication that is ` * ` in Javascript by using BuildTuple.

0 <= multiplier <= 999, 0 <= product <= 9999, limited by Typescript v4.6.2.

If the length of a tuple is greater than 9999, it will show 'Type produces a tuple type that is too large to represent. ts(2799)'... 🤔

It's a simple version of [ 517 - Multiply ](https://github.com/type-challenges/type-challenges/blob/master/questions/517-extreme-multiply/README.md).

For example

```ts
Multiplication<2, 5> // expect to be 10
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Multiplication<A extends number, B extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Multiplication<10, 10>, 100>>,
  Expect<Equal<Multiplication<10, 0>, 0>>,
  Expect<Equal<Multiplication<2, 5>, 10>>,
  // @ts-expect-error
  Expect<Equal<Multiplication<100, 100>, 10000>>
]
```

**Comment by antfu** [comment]
Duplicated with https://github.com/type-challenges/type-challenges/blob/master/questions/517-extreme-multiply/README.md
