### ISSUE TITLE
3057 - Push

### ISSUE THREAD

**Issue by pbambusek** [type-challenges/type-challenges#7727]
Haven't seen this kind of solution among the submitted yet:

```ts
type Push<T extends unknown[], U> = T extends [...any, U] ? T : [...T, U]
```

**Comment by Meglody** [comment]
If we need to guarantee a no-repeat result, then it is error, when use this case:
```ts
type cases = [
  Expect<Equal<Push<['1', 2, '3', '4'], '3'>, ['1', 2, '3']>>
]
```
because `U` just represents the last item. @pbambusek

**Comment by pbambusek** [comment]
@Meglody yeah, make sense, I was fitting it to the tests and didn't realize it's about repetiveness.

**Comment by Meglody** [comment]
Okey, maybe your answer is right again 😂 , it seems they have had a wrong merge and i misunderstand with the Array.push type,  -> heres a revert pull in #7624 @pbambusek
