### ISSUE TITLE
3060 - Unshift

### ISSUE THREAD

**Issue by RennCheung** [type-challenges/type-challenges#7909]
```ts
// your answers
type Unshift<T extends unknown[], U> = [U] extends [T[number]] ? T : [U, ...T];

```

**Comment by 942368681** [comment]
will be wrong in this case:
Expect<Equal<Unshift<[1, 2], 1>, [1, 1, 2]>>,

**Comment by bolosea** [comment]
> will be wrong in this case: Expect<Equal<Unshift<[1, 2], 1>, [1, 1, 2]>>,

这人做的是不能添加重复元素的
