### ISSUE TITLE
2946 - ObjectEntries

### ISSUE THREAD

**Issue by RennCheung** [type-challenges/type-challenges#8143]
```ts
// your answers
type ObjectEntries<T extends object, U = keyof T> = U extends U
  ? [U] extends [keyof T]
    ? [U, T[U]]
    : never
  : never;
```

**Comment by dagda1** [comment]
This was similar to my attempt but you do not need `[U] extends [keyof T]`

It can be

```ts
type ObjectEntries<T, U = keyof T> = U extends keyof T
                                        ? [U, T[U]]
                                        : never;
```

But both fail this test

```ts
Expect<Equal<ObjectEntries<Partial<Model>>, ModelEntries>>,
```

It is not clear in the explanation of the question what should be done with undefined in the question.

**Comment by RennCheung** [comment]
Thank you, your answer has made me learn more concisely.

The reason for not passing the test may be caused by the different version of the TS. I can pass these two answers.

I use V4.6.3 version of TypeScript in VSCODE

**Comment by dagda1** [comment]
@RennCheung thank you for the reply, here is a [playground](https://www.typescriptlang.org/play?ts=4.6.2#code/PQKgUABBBMCcAsA2CBaCB5ARgKwKYGMAXAUQDtCAnAS1wGdJUUnmHMBPCbKgQ1IHNaAC14QAFAAEuvAcNIBbXIW4BKCAGIFAEyoBXOeoD2OAoQYM1FiAEUddQlQOkzUAJJyADgBtcC8hEKCuP5s7kEAbrgUtA6kEAYAZhAABilYeEQAdLjk1HQpSc4QAGIGFBC4AB7cHt4QhfmEIXT41O6mUFTkkfHc+EEAsgaauJ4QAN4MUKTVuABcELSUnXwA3JMQ3HxzEKR6mJFrUFCeBvjc9o6084vU-ADaALoQAD47Op6ehxAAvgyNoRA5EMRmQlnQIABeDDGIig3K0AA8g2GngAfBBgMAIHcAOTTBQ4gA0CyW-Cer1xm1wRLecn2FHJ2JxJzOF1ItBpN2Wjxebw+Dy++UK6IAajQAO5xWIAcSohAAEjpMPNBIRCO4rpjCLR8IIMthaBlSnxgHAkGAQMAwNbQBAAPoOx1Ox0QACaBh0ZQAwsCIPLIkFnUGHRBLdawP8gmkTHCaIiACrEgCqkIgAGtcGwEhB4+ioSnKoRsppaOnM9n4+sjtWa7W6-WjgB+bFJ4nxu5Jh4PKsN3t9mvzUi4CIUNbh23BoM5uwQL3cWjgyfO0NWqgeUqEYIAsYQYgARx03E8xOIFVCRB+EHiFAM+hx4kjKF1R+8-DowB09k8HLAa-cG-GXczxMIojwXYkADkDBIA8j0va9bwge9H2fD5si2WgPy-H9fy6Cgej6CBkRGcYGHxbYuX4BgqUHPZIgYFlzhiK4SVuPgeVeXYPjAX4IyaIjgU8WNwShXFyM5Uk+EZSkthpXY6UiaTmVOJjLgktiOL5Txuz4gF0H01No1hHI4wRAAFbgKHsI8kUE1FUTHXSgjOBdS1EhhT3PQgEX3Q9PARIySBMuhbJRVFiWIoTgtoezCQ84CiB82D-MC4TEQsqyeH8yLYoElE0ti+KvKSvyAphIKwURHcMzYRt5h0UhhniTpcE0H5wqZGqaQapqWs0B5CqgTyTBKmzUuihFqszerGtwZqhza74OtxLriR6ua+oG8KwB0m0QHtJcXSKT0AkiCAAGUiw1A7DrtFcwFABh0XO4QKCCLNPQWAxPE-ZiVTVDVZi1HU9QNI0KBNM1EGAXhaHFeioFFCUvp+tkWNVdVNWAbVdX1Q1jVNBBodob7fsuJ6BLe2dhDQt90YBrGcdB-GIYtK0wCAA) with 4.6.2 and it does not work.

You definitely need to do something to remove undefined from the union but the question does not make it clear that, this is required.  Other solutions do, do this, e.g.

```ts
type ObjectEntries<T> = {
  [P in keyof T]-?: [P, Exclude<T[P], undefined> extends never ? T[P] : Exclude<T[P], undefined>]
}[keyof T]
```

**Comment by lorainwings** [comment]
type NoUndefined<T> = T extends undefined ? never : T
type ObjectEntries<T, U extends keyof T = keyof T> = U extends U ? [U, T[U] extends undefined ? T[U] : NoUndefined<T[U]>] : never
