### ISSUE TITLE
White labels with numbers

### ISSUE THREAD

**Issue by turtleflyer** [type-challenges/type-challenges#834]
Issues from https://github.com/type-challenges/type-challenges/issues/808 to https://github.com/type-challenges/type-challenges/issues/818 have no attached white labels with numbers. Maybe it`s connected to that, none of them are listed as a solution to the related challenges.

Example: [Sameone`s answer on Merge](https://github.com/type-challenges/type-challenges/issues/817) - [List of answers on Merge](https://github.com/type-challenges/type-challenges/issues?q=label%3A599+label%3Aanswer)

**Comment by antfu** [comment]
I think it was the time that GitHub Actions went down. Fixed now.

**Comment by turtleflyer** [comment]
https://github.com/type-challenges/type-challenges/issues/809, https://github.com/type-challenges/type-challenges/issues/810, https://github.com/type-challenges/type-challenges/issues/811, https://github.com/type-challenges/type-challenges/issues/812, https://github.com/type-challenges/type-challenges/issues/813, https://github.com/type-challenges/type-challenges/issues/814, https://github.com/type-challenges/type-challenges/issues/815, https://github.com/type-challenges/type-challenges/issues/817 still need to be fixed as well.

**Comment by turtleflyer** [comment]
@antfu Do you mind reopening the issue to fix the remaining labels?

**Comment by antfu** [comment]
fixed now, thanks
