### ISSUE TITLE
11 - Tuple to Object

### ISSUE THREAD

**Issue by SB-SLIM** [type-challenges/type-challenges#8371]
```ts
// your answers
```
type TupleToObject<T extends readonly PropertyKey[]> = {
  [Key in T[number] ]: Key
}

**Comment by glushkina1** [comment]
@SB-SLIM hi, could you explain what is 'number' here?

**Comment by SB-SLIM** [comment]
hi @glushkina1, indexing with an arbitrary type  using number to get the type of an array’s elements.

https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html
