### ISSUE TITLE
9 - Deep Readonly

### ISSUE THREAD

**Issue by vaakian** [type-challenges/type-challenges#8426]
```ts
type DeepReadonly<T> = {
   readonly [k in keyof T]: T[k] extends {} ? DeepReadonly<T[k]>: T[k]
}
```
is the `extends {}` contains any potential issue?

**Comment by Muffinmann** [comment]
While I was trying it out, I noticed that the assertion 'T extends {}' returns almost always true. Maybe use 'object' or 'Record<string, never>' instead
![image](https://user-images.githubusercontent.com/24995804/163340747-33886aa0-d5b0-44bf-86f6-e18fbfe43c22.png)

**Comment by vaakian** [comment]
>

**Comment by vaakian** [comment]
> While I was trying it out, I noticed that the assertion 'T extends {}' returns almost always true. Maybe use 'object' or 'Record<string, never>' instead ![image](https://user-images.githubusercontent.com/24995804/163340747-33886aa0-d5b0-44bf-86f6-e18fbfe43c22.png)

thanks! and in addition, I found that`{[k: string]: never}` also works.
