### ISSUE TITLE
新题目 ArrayOfLength

### ISSUE THREAD

**Issue by masx200** [type-challenges/type-challenges#8532]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: hard

# 题目标题
title: Array Of Length

# 题目标签
tags: array
```

## 题目

```ts
export let aaa: [number, number, number, number] = [1, 2, 3, 45];
export let bbb: ArrayOfLength<number, 4> = [1, 2, 3, 45];

aaa = bbb;
bbb = aaa;
```

## 题目模版

以下是给予挑战者开始做题的代码模版，在大部分情况下你只需要修改类型名称使其符合你的题目与判题测试，实现的部分保持 `any` 即可。

```ts
type ArrayOfLength= any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import { Equal, Expect, ExpectFalse, NotEqual,ExpectExtends } from '@type-challenges/utils'

type cases = [
  Expect<ExpectExtends<ArrayOfLength<number, 4> , [number, number, number, number]>>,
  Expect<ExpectExtends<[number, number, number, number],ArrayOfLength<number, 4>  >>,
Expect<ExpectExtends<ArrayOfLength<number, 3> , [number, number, number]>>,
  Expect<ExpectExtends<[number, number, number],ArrayOfLength<number, 3>  >>
]
```

**Comment by antfu** [comment]
可以给题目加一些说明么？

**Comment by masx200** [comment]
> 可以给题目加一些说明么？

第二个参数代表数组的长度

**Comment by jiangshanmeta** [comment]
@masx200  Actually there is a [similar question](https://github.com/type-challenges/type-challenges/blob/main/questions/07544-medium-construct-tuple/README.md)

**Comment by jiangshanmeta** [comment]
duplicated with [Construct Tuple](https://github.com/type-challenges/type-challenges/blob/main/questions/07544-medium-construct-tuple/README.md)
