### ISSUE TITLE
Permuatation&Combination

### ISSUE THREAD

**Issue by HomyeeKing** [type-challenges/type-challenges#8767]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: meduim # medium / hard / extreme
title: Permuatation & Combination
tags: array, application, string # separate by comma
```

## Question

Give an array of strings, then do Permutation & Combination.
It's also useful for the prop types like video [controlsList](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList)

```ts
// expected to be `"foo" | "bar" | "baz" | "foo bar baz" | "bar foo" | "baz foo" | "bar baz" | "baz bar"`
type Keys = PermutationCombination<['foo', 'bar', 'baz']>
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave it to implementation `any`.

```ts
type PermutationCombination<T extends string[]> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<PermutationCombination<['foo', 'bar', 'baz']>,
  'foo' | 'bar' | 'baz' | 'foo bar baz' | 'bar foo' | 'baz foo' | 'bar baz' | 'baz bar'>>,
]

```

**Comment by Lionad-Morotar** [comment]
也许是我理解有误，我觉得题目的测试用例存在问题。HTML 的 video control list 是顺序不相关的属性集，但是题目中的测试用例确实顺序相关的。

=============

Translations:

I wonder if there is something wrong with my understanding, maybe this test case is specifically misleading?

```ts
// expected to be `"foo" | "bar" | "baz" | "foo bar baz" | "bar foo" | "baz foo" | "bar baz" | "baz bar"`
type Keys = PermutationCombination<['foo', 'bar', 'baz']>
```

but why not:

```ts
// expected to be `"foo" | "bar" | "baz" | "baz bar foo" | "bar foo" | "baz foo" | "bar baz" | "baz bar"`
type Keys = PermutationCombination<['foo', 'bar', 'baz']>
```

or others. Could you add more test cases to clear the meaning of this topic?
