### ISSUE TITLE
Convert

### ISSUE THREAD

**Issue by kynefuk** [type-challenges/type-challenges#895]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info
Basic info of your challenge questions,

```yaml
difficulty: easy
title: Convert
tags: template-literal
tsconfig: 
  ts: 4.1.0-pr-40336-88
```

## Question

Implement `Convert<S, T, U>` which takes three strings and convert `T` to `U` if `S` contains `T`.
For example

```
type HyphenToUnderScore = Convert<'Content-Type', '-', '_'> // expected to be 'Content_Type'
```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Convert<S extends string, T extends string, U extends string> = any;
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Convert<'Content-Type', '-', '_'>, 'Content_Type'>>,
  Expect<Equal<Convert<'Content-Type', 'x', 'y'>, 'Content-Type'>>,
  Expect<Equal<Convert<'Access-Control-Allow-Origin', '-', '_'>, 'Access_Control_Allow_Origin'>>,
]
```

**Comment by antfu** [comment]
How about name it as `Replace`?

**Comment by antfu** [comment]
Where we already had it on https://tsch.js.org/116.

**Comment by kynefuk** [comment]
@antfu 
Sorry for my lack of Description.
The difference between `Replace` and `Convert` is that `Replace` replace`T` to `U`  just once and `Convert` replace all `T`  to `U`.

**Comment by antfu** [comment]
#119?
