### ISSUE TITLE
TwoSum

### ISSUE THREAD

**Issue by qianxi0410** [type-challenges/type-challenges#8954]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: TwoSum
tags: union, array # separate by comma
```

## Question

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice. 

## Template 
```ts
type TwoSum<Arr extends number[], target extends number> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<TwoSum<[2, 7, 11, 5], 9>, [0, 1]>>,
  Expect<Equal<TwoSum<[3, 2, 4], 6>, [1, 2]>>,
  Expect<Equal<TwoSum<[3, 3], 6>, [0, 1]>>,
  Expect<Equal<TwoSum<[2, 7, 11, 5], 10>, []>>,
  Expect<Equal<TwoSum<[1, 3, 6, 7, 9], 10>, [0, 4]>>,
]
```

**Comment by antfu** [comment]
Close in favor of #8804
