### ISSUE TITLE
527 - Append to object -- What's wrong with this solution

### ISSUE THREAD

**Issue by pzhasaki** [type-challenges/type-challenges#9115]
```ts
type AppendToObject<T, U extends string, V> = {
  [K in U]: V
} & T;    

type TestAppendToObject = { id: '1' }

type ResultAppendToObject = AppendToObject<TestAppendToObject, 'value', 4>;

const resultAppendToObject: ResultAppendToObject = {
    id: '1',
    value: 4
}
```

**Comment by bigbee** [comment]
In most cases it will be the same, since it will structurally end up as the same type.

There are edge cases though. Try `type ResultAppendToObject = AppendToObject<TestAppendToObject, 'id', '2'>;` and you will see the `ResultAppendToObject['id']` will be `never`. That is because there is no union between the string literals `'1'` and `'2'`.

Whether that really is relevant for this exercise is another matter. I think this exercise is just requiring your final type not to be a union. Having it as a mapped type instead of a union might also result in a bit better intellisense. YMMV.

**Comment by pzhasaki** [comment]
> In most cases it will be the same, since it will structurally end up as the same type.
> 
> There are edge cases though. Try `type ResultAppendToObject = AppendToObject<TestAppendToObject, 'id', '2'>;` and you will see the `ResultAppendToObject['id']` will be `never`. That is because there is no union between the string literals `'1'` and `'2'`.
> 
> Whether that really is relevant for this exercise is another matter. I think this exercise is just requiring your final type not to be a union. Having it as a mapped type instead of a union might also result in a bit better intellisense. YMMV.

**Comment by motionrus** [comment]
@pzhasaki @bigbee sorry, but can you help me describe this case?

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type test1 = {
    key: 'cat'
    value: 'green',
    home: string,
}

type testExpect1 = {
    key: 'cat'
    value: 'green'
    home: boolean
}

type AppendToObject<T, U extends keyof any, V> = Omit<T, U> & Record<U, V>
type myObject = AppendToObject<test1, 'home', boolean>

// Duck test: If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
type cases = [
    Expect<Equal<testExpect1["key"], myObject["key"]>>,
    Expect<Equal<testExpect1["value"], myObject["value"]>>,
    Expect<Equal<testExpect1["home"], myObject["home"]>>,
    Expect<Equal<keyof testExpect1, keyof myObject>>
]

// But 
type v = [Expect<Equal<myObject, testExpect1>>, ] //  Type 'false' does not satisfy the constraint 'true'.
```

**Comment by lio-mengxiang** [comment]
> 
Is it possible to add an auxiliary type, so as to have a better experience?
for example
`
type ShowObj<T> = {
 [key in keyof T]∶ T[key]
}
`

**Comment by furkandmrblk** [comment]
> @pzhasaki @bigbee sorry, but can you help me describe this case?
> 
> ```ts
> import type { Equal, Expect } from '@type-challenges/utils'
> 
> type test1 = {
>     key: 'cat'
>     value: 'green',
>     home: string,
> }
> 
> type testExpect1 = {
>     key: 'cat'
>     value: 'green'
>     home: boolean
> }
> 
> type AppendToObject<T, U extends keyof any, V> = Omit<T, U> & Record<U, V>
> type myObject = AppendToObject<test1, 'home', boolean>
> 
> // Duck test: If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
> type cases = [
>     Expect<Equal<testExpect1["key"], myObject["key"]>>,
>     Expect<Equal<testExpect1["value"], myObject["value"]>>,
>     Expect<Equal<testExpect1["home"], myObject["home"]>>,
>     Expect<Equal<keyof testExpect1, keyof myObject>>
> ]
> 
> // But 
> type v = [Expect<Equal<myObject, testExpect1>>, ] //  Type 'false' does not satisfy the constraint 'true'.
> ```

Hey, as @bigbee said, this exercise does not want your final type to be an intersection. I tested your solution and when you adjust `testExpect1` so that it has an intersection, the test case will pass.

Here's the code:
```ts

type AppendToObject<T, U extends keyof any, V> = {
  [K in keyof T | U]: K extends keyof T ? T[K] : V
}

type AppendToObject2<T, U extends keyof any, V> = Omit<T, U> & Record<U, V>

type Result1 = AppendToObject<test1, 'home', boolean>

type Result2 = AppendToObject2<test1, 'home', boolean>

// The types are the same, but `Result2` has an intersection.

const a: Result1 = { key: 'cat', value: 'green', home: true }

const b: Result2 = { key: 'cat', value: 'green', home: true }

/* _____________ Test Cases _____________ */
import type { Equal, Expect } from '@type-challenges/utils'

type results = [
  Expect<Equal<AppendToObject<test1, 'home', boolean>, testExpect1>> // works (first solution without intersection),
  Expect<Equal<AppendToObject2<test1, 'home', boolean>, testExpect1>>, // throws error
  Expect<Equal<AppendToObject2<test1, 'home', boolean>, testExpect1b>>, // works properly (second solution with intersection, but expected test was adjusted)
]

type test1 = {
  key: 'cat'
  value: 'green'
}

type testExpect1 = {
  key: 'cat'
  value: 'green'
  home: boolean
}

type testExpect1b = {
  key: 'cat'
  value: 'green'
} & {
  home: boolean
}
```

**Comment by webdingens** [comment]
That is not the same. The idea was to override preexisting properties (not a requirement for the test). This would work:

```typescript
type AppendToObject<T, U extends keyof any, V> = {
  [k in keyof T | U]: k extends U
    ? V
    : k extends keyof T
      ? T[k]
      : never
}
```

The `Omit & Record` should be correct but throws an error. Unless there is supposed to be a distinction between intersection types and mapped types, this should be fixed.

**Comment by fdc-viktor-luft** [comment]
This will work:

```ts
type AppendToObject<T, U extends string, V> = Omit<T & { [key in U]: V }, never>
```
