### ISSUE TITLE
8 - Readonly 2

### ISSUE THREAD

**Issue by Tommy0604** [type-challenges/type-challenges#9124]
```ts

type MyReadonly2<T, K extends keyof T = keyof T> = 
  { readonly [key in K]: T[key] } 
  & { [key in keyof T as (key extends K ? never : key)]: T[key] }
```

**Comment by tongchaowang** [comment]
@Tommy0604 你好，有两个知识点需要想你请教一下，谢谢
1. K extends keyof T = keyof T 这里=的作用是什么意思？
2. as在type中作用是什么呢？

**Comment by Tommy0604** [comment]
> @Tommy0604 你好，有两个知识点需要想你请教一下，谢谢
> 
> 1. K extends keyof T = keyof T 这里=的作用是什么意思？
> 2. as在type中作用是什么呢？

1. 因为第二个泛型K可能为空，所以要给默认值。
2. as可以把的泛型T断言成 K

**Comment by abigmiu** [comment]
> Tommy0604
请问下
Expect<Alike<MyReadonly2<Todo1>, Readonly<Todo1>>>,
`Readonly <Todo1>` 的不为空吧， 为啥加上`K extends keyof T = keyof T ` 的 `keyof T` 是正确的

**Comment by astak16** [comment]
> @Tommy0604 你好，有两个知识点需要想你请教一下，谢谢
> 
> 1. K extends keyof T = keyof T 这里=的作用是什么意思？
> 2. as在type中作用是什么呢？

1. `=` 是给默认值，或者叫默认约束

2. 这个 `as` 是 4.1 的功能：https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types

`P in keyof T`, 这个 `P` 是 `T` 的属性，有时候你想对 `P` 进行额外的处理，比如添加前缀后缀，过滤出符合条件的 `P` 等，就可以用 `as` 连接后面的子句，用子句去完成这个操作。

**Comment by astak16** [comment]
> > Tommy0604
> 
> 请问下 Expect<Alike<MyReadonly2, Readonly>>, `Readonly <Todo1>` 的不为空吧， 为啥加上`K extends keyof T = keyof T ` 的 `keyof T` 是正确的

不传就需要默认值，`K` 不传的时候默认值是 `keyof of T`

**Comment by wang-panfeng** [comment]
> * K extends keyof T = keyof T 这里=的作用是什么意思？
> * as在type中作用是什么呢？

K extends keyof T = keyof T 这里=的作用是什么意思？ -- 这是默认赋值，不传参的话就表示所有属性readonly
as 是断言，当做语法规则理解吧
