### ISSUE TITLE
Maximum

### ISSUE THREAD

**Issue by ch3cknull** [type-challenges/type-challenges#9384]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: hard
title: Maximum
tags: array
```

### Description
Implements a type `Maximum`,  get array like type `T`, and return max value in `T`

`0 <= T[number] < 1000`, so **nagative number not considered**.

If `T` is a empty array `[]`, just reutrn `never`

```ts
Maximum<[]> // never
Maximum<[0, 2, 1]> // 2
Maximum<[1, 20, 200, 150]> // 200
```
### Advanced
Can you implement type `Minimum` inspired by `Maximum`?

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type Maximum<T extends any[]> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Maximum<[]>, never>>,
  Expect<Equal<Maximum<[0, 2, 1]>, 2>>,
  Expect<Equal<Maximum<[1, 20, 200, 150]>, 200>>,
]
```

**Comment by jiangshanmeta** [comment]
```typescript
type Filter<T extends number[],L extends number,R extends number[] = []> = T extends [infer F extends number,...infer O extends number[] ]? Filter<O,L,F extends L?R:[...R,F] >  :R
type Maximum<T extends number[],S extends number[]= []> = T['length'] extends 0? never:T['length'] extends 1? T[0]:Maximum<Filter<T,S['length']>,[...S,0] >
```

**Comment by ch3cknull** [comment]
inspired by
```hs
maximum :: (Ord a) => [a] -> a  
maximum [] = error "maximum of empty list"  
maximum [x] = x  
maximum (x:xs) = max x (maximum' xs)
```

my solution
```ts

type toTuple<A extends number | string, R extends any[] = []> =
`${R['length']}` extends `${A}`
  ? R
  : toTuple<A, [...R, 0]>

type Max<A extends any[], B extends any[]> = A extends [...B, ...infer _] ? A : B

type Maximum<
  T extends any[],
  Curr extends any[] = [],
  Original = true
> = T extends [infer L, ...infer R]
  ? Maximum<R, Max<toTuple<L & number>, Curr>, false>
  : Original extends true
    ? never
    : Curr['length']
```
