### ISSUE TITLE
TypeScript Playground cannot find the module @type-challenges/utils

### ISSUE THREAD

**Issue by LittleSound** [type-challenges/type-challenges#9400]
# Summary

TypeScript Playground suddenly cannot find the module `@type-challenges/utils`, it worked yesterday.

# Description

The Typescript Playground editor throw an error says: `Cannot find module '@type-challenges/utils' or its corresponding type declarations.(2307)`

Screenshots below: 

![image](https://user-images.githubusercontent.com/19204772/165420788-a339b943-092c-45c6-bd1c-44052534a29b.png)

And the other questions have the same issue, such as [Question: Hello World](https://www.typescriptlang.org/play?#code/PQKgUABBCMDMEFoIAkCmAbdB7CB1LATugCaSIIWVkBGAnhAIIB2ALgBZZP0BiArhAAoAAgENWAM14BKCAGIA7iIIBbBLwAOEMmVm6IARV6oAziwCWnbVDSYsAGjyESAQisQAkkwgAVWutQQAMJsIpioTADmJg7yAbzGAeyJfgHGtKaoyhBmLAno4hAsOMQ4SRAixgkE5pwAdFpQZNyEhWxmxhAAxiFhkagOtFj88maYEEyoqMSFON1iUa0B4li2I5FdWMSJOMoiANaJbIkmuRDqFR0CTKUpXUedexCoBASExlK1bgAGP7lkwMAngAPfydFhTGYQaipFgEMyRMgsW42bD4IjTAC85S4ZB+X2+v2M-0Bg34xg4vBIEF2B1a7Qg8kIe0Rt3BpggWIAoiDUGCADycgCOvFCfJRWDRJAcpjhkQAfHLcT83IF0GYHosIF9vPtDgFgqF0OEol8obwWEUvEUIKYlCwNsR4RFnCgROp1PRkCIHk7XI0oHKIAA1MyoeQQTgQADiOWQvGoAC4IGwLepjAmAblurUAFbGWqECLAOBgEDAMAV0AQAD6tbr9brEAAmkMCEFNgE0AQAg3e7WIGWK0j-CgMKinJjsfQAcDQeDptboeUbbCnRWwFW+72fCcghUTDWt-WB+WzMp1IR7cOAgBvCBCkXoBzcucOAByWBYzHoAF8IOJXiyAByIRrwQOZeiiYxgHNUZjCAodbk6fcOixABtMgX15Fg+Q-L8uDFMcJQnBU7Ewnl+QfUVxUlYhpVXeU5TIgBddcNxAQ8j37PhqiONsAGVwTTTiuJPdiyEDfiQm7CBSTbYwVlgzh02TVN00zYxszzAsCCLOBgDEYxYgICTg1DcMFPQJSmBUlMWDTDNgCzNhc3zQti1gYBLOsokAwgABZQh9R6I0+lstTHOc1ydIiUtyzAIA)

**Comment by jiangshanmeta** [comment]
呃 我之前网络不好的时候会出现这个问题

**Comment by LittleSound** [comment]
> 呃 我之前网络不好的时候会出现这个问题

可能是这个问题，现在错误又消失了。

**Comment by yukinotech** [comment]
you can try get `@type-challenges/utils` with npm in local to avoid net problems
