### ISSUE TITLE
DeepPick

### ISSUE THREAD

**Issue by hiroyaiizuka** [type-challenges/type-challenges#956]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty:  hard 
title: DeepPick
tags: deep
```

## Question

Implement a type DeepPick, that extends Utility types `Pick`.
A type takes two arguments.

For example:

```

type obj = {
  name: 'hoge', 
  age: 20,
  friend: {
    name: 'fuga',
    age: 30,
    family: {
      name: 'baz',  
      age: 1 
    }
  }
}

type T1 = DeepPick<obj, 'name'>   // { name : 'hoge' }
type T2 = DeepPick<obj, 'name' | 'friend.name'>  // { name : 'hoge' } & { friend: { name: 'fuga' }}
type T3 = DeepPick<obj, 'name' | 'friend.name' |  'friend.family.name'>  // { name : 'hoge' } &  { friend: { name: 'fuga' }} & { friend: { family: { name: 'baz' }}}

```

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type DeepPick = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type Obj = {
  a: number,
  b: string,
  c:  boolean,
  obj: {
    d: number,
    e: string,
    f:  boolean,
    obj2: {
      g: number,
      h: string,
      i: boolean,
    }
  },
  obj3: {
    j: number,
    k: string,
    l: boolean,
  }
}

type cases = [
  Expect<Equal<DeepPick<Obj, ''>, unknown >>,
  Expect<Equal<DeepPick<Obj, 'a'>, { a: number }>>,
  Expect<Equal<DeepPick<Obj, 'a' | 'obj.e'>, { a: number } & { obj: { e: string }}>>,
  Expect<Equal<DeepPick<Obj, 'a' | 'obj.e' | 'obj.obj2.i'>, { a: number } & { obj: { e: string }} & { obj: { obj2: { i: boolean } }}>>,
]
```

**Comment by antfu** [comment]
Hey, @hiroyaiizuka this looks great and I am happy to have it!

Got a few small concerns about it tho:

- The mention of the original tweet is nice, but as it contains a solution, thinking maybe we can move it to somewhere that the participants can't see it directly?
- I like the idea of you using names from the family for example, however, I am a bit concern about privacy issues, can you maybe remove the comments mention about your daughter?

Many thanks

**Comment by hiroyaiizuka** [comment]
@antfu 

Thank you very much for your nice feedbacks.

・You are right, I will delete tweet link !
・Agree, I will change the comment！
