### ISSUE TITLE
CapitalizeNestObjectKeys

### ISSUE THREAD

**Issue by Mayandev** [type-challenges/type-challenges#9775]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Capitalize nested object keys.

```yaml
difficulty: hard
title: Capitalize Nest Object Keys
tags: object, array
```

## Question

Capitalize the key of the object, and if the value is an array, iterate through the objects in the array.

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type CapitalizeNestObjectKeys<T> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type foo = {
    foo: string;
    bars: [{ foo: string }];
};

type Foo =  {
    Foo: string;
    Bars: [{
        Foo: string;
    }];
}

type cases = [
  Expect<Equal<Foo, CapitalizeNestObjectKeys<foo>>>
]
```

**Comment by jiangshanmeta** [comment]
```typescript
type CapitalizeNestObjectKeys<T> = T extends readonly any[]
  ? {
      [K in keyof T]: CapitalizeNestObjectKeys<T[K]>;
    }
  : T extends Record<keyof any, any>
  ? {
      [K in keyof T as Capitalize<K & string>]: CapitalizeNestObjectKeys<T[K]>;
    }
  : T;
```
