### ISSUE TITLE
14 - First of Array

### ISSUE THREAD

**Issue by mistlog** [type-challenges/type-challenges#985]
use typetype:
* repo https://github.com/mistlog/typetype
* solution: https://github.com/mistlog/typetype-examples/blob/main/examples/type-challenges/14-easy-first.type

```ts
export type function First = (T extends any[]) => ^{
    if(T[number] extends never) {
        return never
    } else {
        return T[0]
    }
}
```

**Comment by chbinghu** [comment]
type First<T extends any[]> = T extends [] ? never : T[0];
