### ISSUE TITLE
New Challange: Two Sum

### ISSUE THREAD

**Issue by HerringtonDarkholme** [type-challenges/type-challenges#9908]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Given an tuple of  integer `nums` and an integer target, return a boolean literal type that indicates whether there are two numbers such that they add up to `target`.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

```yaml
difficulty: hard 
title: Two Sum
# tags: array, math # separate by comma
```

## Question

Given an tuple of  integer `nums` and an integer target, return a boolean literal type that indicates whether there are two numbers such that they add up to `target`.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type TwoSum<Nums, Target> = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<TwoSum<[1,2,3,4], 6>, true>>,
  Expect<Equal<TwoSum<[1,2,3,4], 9>, false>>,
  Expect<Equal<TwoSum<[1,9], 2>, false>>,
  Expect<Equal<TwoSum<[1,1,9], 2>, true>>,
]
```

**Comment by jiangshanmeta** [comment]
[Duplicated](https://github.com/type-challenges/type-challenges/blob/main/questions/08804-hard-two-sum/README.md)
